### ISSUE TITLE
java.lang.IllegalAccessError: ... cannot access its superinterface .....

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#107]
_From [leon.oos...@gmail.com](https://code.google.com/u/109690981829239627626/) on December 17, 2008 00:26:52_

What steps will reproduce the problem? 1. try to mock a static class with a private interface What is the expected output? What do you see instead? It should return void What version of the product are you using? On what operating system? powermock 1.1.1. on XP Please provide any additional information below. here's the stack trace:
java.lang.IllegalAccessError: class XXXX$4 cannot access its superinterface
XXXXX$PRIVATEINFTERFACE

	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:620)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:465)
	at
org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:201)
	at
org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:140)
	at
org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:251)
	at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:319)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2395)
	at java.lang.Class.getDeclaredMethods(Class.java:1763)
	at org.powermock.core.WhiteboxImpl.getAllMethods(WhiteboxImpl.java:873)
	at org.powermock.core.WhiteboxImpl.getMethods(WhiteboxImpl.java:1038)
	at org.powermock.Whitebox.getMethods(Whitebox.java:412)
	at org.powermock.PowerMock.mockStaticPartial(PowerMock.java:579)

_Original issue: http://code.google.com/p/powermock/issues/detail?id=87_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on December 17, 2008 07:33:30_

Could you please join our mailing-list (go to http://groups.google.com/group/powermock ) and post questions there instead? Then I
would have discovered this much faster. 

Anyway I don't quite understand what you mean by "try to mock a static class with a
private interface". Are you saying that you're trying to mock an inner class that is
static that implements some interface?

Please respond on the mailing list instead of here.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on December 24, 2008 12:55:18_

The reason was that inner classes/interface didn't work well with PowerMock. It has
been improved in trunk and the above use case should now work.

**Status:** Fixed
