### ISSUE TITLE
Exception when using powermock with a jboss bootstrap instance

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#110]
_From [nikesh.midha](https://code.google.com/u/nikesh.midha/) on January 22, 2009 11:18:58_

I am using PowerMock with jboss bootstrap instance. My testcase uses
powermock (version 1.1.1) for junit3 (by having a static suite() API). The
test case extends a org.jboss.embedded.junit.BaseTestCase to start a jboss
bootstrap instance in setup. During startup itself, it fails giving the
following exception : 

Unable to create a KernelInitializer based on the specified KernelConfig
java.lang.RuntimeException: Unable to create a KernelInitializer based on
the specified KernelConfig
        at
org.jboss.kernel.KernelFactory.createKernelInitializer(KernelFactory.java:156)
        at
org.jboss.kernel.KernelFactory.assembleNewKernel(KernelFactory.java:99)
        at org.jboss.kernel.KernelFactory.newInstance(KernelFactory.java:67)
        at
org.jboss.kernel.plugins.bootstrap.AbstractBootstrap.bootstrap(AbstractBootstrap.java:120)
        at
org.jboss.kernel.plugins.bootstrap.AbstractBootstrap.run(AbstractBootstrap.java:89)
        at org.jboss.embedded.Bootstrap.createKernel(Bootstrap.java:131)
        at org.jboss.embedded.Bootstrap.getInstance(Bootstrap.java:76)
        at
org.jboss.embedded.junit.BaseTestCase.bootstrap(BaseTestCase.java:95)
        at org.jboss.embedded.junit.BaseTestCase.setUp(BaseTestCase.java:66)
        at
com.digite.platform.common.DigiteEJBTestCase.setUp(DigiteEJBTestCase.java:79)
        at
com.digite.platform.common.DigiteEJBTxTestCase.setUp(DigiteEJBTxTestCase.java:25)
        at
com.digite.platform.task.mspintegration.checkin.AssignmentBaselineCheckinAdaptorTest.setUp(AssignmentBaselineCheckinAdaptorTest.java:47)
        at
org.powermock.modules.junit3.internal.impl.JUnit3TestSuiteChunkerImpl.run(JUnit3TestSuiteChunkerImpl.java:157)
        at
org.powermock.modules.junit3.PowerMockSuite.run(PowerMockSuite.java:52)
Caused by: java.lang.ClassCastException:
org.jboss.kernel.plugins.bootstrap.basic.BasicKernelInitializer
        at
org.jboss.kernel.plugins.config.property.PropertyKernelConfig.createKernelInitializer(PropertyKernelConfig.java:118)
        at
org.jboss.kernel.KernelFactory.createKernelInitializer(KernelFactory.java:150)

Additional Info : 
Powermock is working fine for cases where i don't need the jboss bootstrap
instance and extend my test case from TestCase.

_Original issue: http://code.google.com/p/powermock/issues/detail?id=90_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 22, 2009 05:45:27_

Hi, could you please bring this up on our mailing list (goto http://groups.google.com/group/powermock ) so that we can discuss it there? (Just
paste everything you wrote here). That way more people can follow the discussion.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 24, 2009 10:54:05_

@PowerMockIgnore("org.jboss") could be used to get around the problem. This is a
known side-effect when using PowerMock.

**Status:** Invalid
