### ISSUE TITLE
Reflection invokation for fails for X.class.Y

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#130]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 25, 2009 20:18:58_

What steps will reproduce the problem? 1. Modify the GreeterTest from SuppressStaticInitializer to PrepareForTest
2. Execute the test What is the expected output? What do you see instead? Caused by: org.powermock.reflect.exceptions.MethodNotFoundException: No
method found with name 'getClassLoader' with argument types: [
[Ljava.lang.Class; ] in class demo.org.powermock.examples.simple.SimpleConfig
	at
org.powermock.reflect.internal.WhiteboxImpl.throwExceptionIfMethodWasNotFound(WhiteboxImpl.java:898)
	at
org.powermock.reflect.internal.WhiteboxImpl.getMethod(WhiteboxImpl.java:178)
	at org.powermock.core.MockGateway.doMethodCall(MockGateway.java:66)
	at org.powermock.core.MockGateway.methodCall(MockGateway.java:86)
	at
demo.org.powermock.examples.simple.SimpleConfig.<clinit>(SimpleConfig.java:26)
	... 38 more

The error message is also wrong (shouldn't be Ljava.lang.Class;)

_Original issue: http://code.google.com/p/powermock/issues/detail?id=110_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 25, 2009 11:19:47_

The reason for this is the changes that allows for mocking of system classes (public
void edit(MethodCall m), if this is disabled it works)

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 25, 2009 11:44:39_

**Status:** Fixed
