### ISSUE TITLE
Invoke on Varargs Constructor Taking Wrong Argument as the Varags

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#138]
_From [cemca...@gmail.com](https://code.google.com/u/111469112600083617691/) on June 13, 2009 01:02:26_

When you have a constructor with multiple arguments AND varargs, then 
NewInvocationControlImpl assumes the first argument is the varargs. It should pick 
the last argument since varags argument can only be the last in the list of 
arguments. The code only works if the constructor has only one argument which is 
varargs.

Here is the snippet that causes this 
(org.powermock.api.easymock.internal.invocationcontrol.NewInvocationControlImpl.java
 line 41 - 49)
\<snip>
public Object invoke(Class<?> type, Object[] args, Class<?>[] sig) throws Exception 
{
    Constructor<?> constructor = WhiteboxImpl.getConstructor(type, sig);
    if (constructor.isVarArgs()) {
    /*
     * Get the first argument because this contains the actual varargs
     * arguments.
     */
    args = (Object[]) args[0];
    }
\</snip>

Fix should be to replace args = (Object) args[0]; with

    args = (Object[]) args[args.length - 1]; // varargs is the last argument What steps will reproduce the problem? 1. Assume a class Bom like this:
public class Bom {
    private String firstArg;
    private String[] args;
    
    public Bom(String firstArg, String... args) {
        firstArg = firstArg;
        args = args;
    }
}

2. And a Test class like this:
import org.junit.Test;
import org.junit.runner.RunWith;
import org.powermock.api.easymock.PowerMock;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;

@RunWith(PowerMockRunner.class)
@PrepareForTest(Bom.class)
public class BomTest {
    @Test
    public void test() throws Exception {
        PowerMock.createMockAndExpectNew(Bom.class, "abc", "xyz", "123");
        PowerMock.replayAll();
        
        Bom b = new Bom("abc", "xyz", "123");
        
        PowerMock.verifyAll();
    }
}

3. Then running this test will result in the following stacktrace:
java.lang.ClassCastException: java.lang.String cannot be cast to [Ljava.lang.Object;
	at 
org.powermock.api.easymock.internal.invocationcontrol.NewInvocationControlImpl.invok
e(NewInvocationControlImpl.java:48)
	at org.powermock.core.MockGateway.newInstanceCall(MockGateway.java:107)
	at rf.actors.BomTest.test(BomTest.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:59)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$2.runT
estMethod(PowerMockJUnit44RunnerDelegateImpl.java:222)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:79)
	at 
org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.ja
va:87)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$2.runB
eforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:212)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:77)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:42)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invoke
TestMethod(PowerMockJUnit44RunnerDelegateImpl.java:205)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMet
hods(PowerMockJUnit44RunnerDelegateImpl.java:159)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(
PowerMockJUnit44RunnerDelegateImpl.java:133)
	at 
org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:27)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:37)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(Po
werMockJUnit44RunnerDelegateImpl.java:131)
	at 
org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUn
it4TestSuiteChunkerImpl.java:112)
	at 
org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(
AbstractCommonPowerMockRunner.java:44)
	at 
org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.j
ava:45)
	at 
org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at 
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.jav
a:460)
	at 
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.jav
a:673)
	at 
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386
)
	at 
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:19
6) What is the expected output? What do you see instead? What version of the product are you using? On what operating system? 1.2.5 on Java 1.6.0_13 on Windows. Please provide any additional information below.

_Original issue: http://code.google.com/p/powermock/issues/detail?id=118_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on June 15, 2009 01:58:09_

Thanks for reporting this

**Labels:** Milestone-Release1.3

**Comment by johanhaleby** [comment]
_From [cemca...@gmail.com](https://code.google.com/u/111469112600083617691/) on June 15, 2009 10:56:47_

Work around for now is to change the vararg contructor argument to an array a la:

public Bom(String firstArg, String[] args) {
    firstArg = firstArg;
    args = args;
}

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on June 15, 2009 14:32:54_

This has now been fixed in trunk.

**Status:** Fixed

**Comment by johanhaleby** [comment]
_From [spring8...@gmail.com](https://code.google.com/u/115266263719265219776/) on December 10, 2011 07:34:51_

The Bom and BomTest code have new problem on 1.4.10 on Java 1.7 on Windows:

java.lang.AssertionError: 
  Unexpected constructor call begin.Bom("xyz", "123"):
    begin.Bom("abc", "xyz", "123"): expected: 1, actual: 0
	at org.powermock.api.easymock.internal.invocationcontrol.NewInvocationControlAssertionError.throwAssertionErrorForNewSubstitutionFailure(NewInvocationControlAssertionError.java:20)
	at org.powermock.api.easymock.internal.invocationcontrol.NewInvocationControlImpl.invoke(NewInvocationControlImpl.java:66)
	at org.powermock.core.MockGateway.newInstanceCall(MockGateway.java:189)
	at begin.BomTest.test(BomTest.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:66)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:307)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:86)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:94)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:294)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:112)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:73)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:282)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:84)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:49)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:207)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:146)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:120)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:118)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:102)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on December 11, 2011 23:09:25_

Is it really a Java 7 issue only?

**Comment by johanhaleby** [comment]
_From [ronki...@gmail.com](https://code.google.com/u/100032663967160497480/) on December 18, 2011 03:42:08_

I'm getting it on with Java 6 as well.
Using release 1.4.9
