### ISSUE TITLE
Upgrade to Javassist 3.11.0.GA

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#150]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 08, 2009 22:42:44_

do it.

_Original issue: http://code.google.com/p/powermock/issues/detail?id=130_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 08, 2009 15:05:05_

This produces errors in PowerMock when doing byte-code manipulation. Probably a bug
in 3.11. I've upgraded to 3.10 in the meantime.

**Status:** Started

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 08, 2009 15:14:06_

The error happens in PrepareForTestAnnotationTest and looks like:
java.lang.ClassFormatError: Invalid length 636 in LocalVariableTable in class file
org/apache/mina/core/session/AbstractIoSession
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:466)
	at
org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:206)
	at
org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:150)
	at
org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:57)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:252)
	at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:466)
	at
org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:206)
	at
org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:150)
	at
org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:57)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:252)
	at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:466)
	at
org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:206)
	at
org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:150)
	at
org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:57)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:252)
	at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:247)
	at
sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:95)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:107)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:31)
	at sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:370)
	at sun.reflect.annotation.AnnotationParser.parseClassValue(AnnotationParser.java:351)
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:653)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:460)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:222)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:69)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:52)
	at java.lang.Class.initAnnotationsIfNecessary(Class.java:3072)
	at java.lang.Class.getAnnotations(Class.java:3052)
	at
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.classAnnotations(PowerMockJUnit44RunnerDelegateImpl.java:177)
	at
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.getDescription(PowerMockJUnit44RunnerDelegateImpl.java:169)
	at
org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.getDescription(JUnit4TestSuiteChunkerImpl.java:173)
	at
org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.getDescription(AbstractCommonPowerMockRunner.java:39)
	at
org.eclipse.jdt.internal.junit4.runner.JUnit4TestClassReference.sendTree(JUnit4TestClassReference.java:38)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.sendTrees(RemoteTestRunner.java:476)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:464)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 07, 2009 12:23:17_

**Labels:** -Milestone-Release1.3 Milestone-Release2.0

**Comment by johanhaleby** [comment]
_From [dmitry.k...@gmail.com](https://code.google.com/u/113265701349933664773/) on November 16, 2009 00:32:27_

Any updates on this?

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 16, 2009 01:28:44_

Unfortunately not. Guess we have to wait for the next version. You can of course
override the dependency and use 3.11 yourself if you like since most things work.

**Comment by johanhaleby** [comment]
_From [andrei.i...@gmail.com](https://code.google.com/u/102678131244317362177/) on November 26, 2009 03:09:48_

btw, have you reported this problem to the javassist JIRA?

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 26, 2009 04:36:13_

No I haven't but we probably should. The thing is that's it's difficult to give a
good description of what's causing the problem.

**Comment by johanhaleby** [comment]
_From [andrei.i...@gmail.com](https://code.google.com/u/102678131244317362177/) on January 05, 2010 07:38:38_

I hope you can manage to get that description after all... as I've reported, I've
managed to run into a case where the jvm crashes with 3.10

**Comment by johanhaleby** [comment]
_From [eeckhout...@gmail.com](https://code.google.com/u/104856219532457121472/) on March 18, 2010 09:28:23_

I've seem to have run into the same situation. One of my classes, that were
instrumented with @PrepareForTest, called the length() method on a StringBuilder,
which caused the bug with javassist 3.10.0
( https://jira.jboss.org/jira/browse/JASSIST-76 ). So, I switched javassist 3.10.0 with
3.11.0.GA, but that caused the "java.lang.ClassFormatError: Invalid length 636 in
LocalVariableTable in class file" as described above, so I had to go back to 3.10.0.

I managed to get around the issue by casting the StringBuilder to a CharSequence
first (INVOKEVIRTUAL vs INVOKEINTERFACE?). This means that I had to change my code to
make tests work :<

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 21, 2010 01:18:06_

Sorry to hear that but thanks for reporting about your findings. It's been a while
since javassist released anything..

**Comment by johanhaleby** [comment]
_From [daniel.b...@gmail.com](https://code.google.com/u/108009083950969479628/) on April 22, 2010 05:10:43_

I had the same problem with both JA 3.10.0 and 3.11.0. Now I upgraded to 3.12.0.GA
which was released on april 16, this solved the problem for me.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on April 22, 2010 05:37:52_

That's great news. Didn't know that it was released! I'll and an issue for updating to 
that version. Thanks for letting us know.

**Comment by johanhaleby** [comment]
_From [ankurmit...@gmail.com](https://code.google.com/u/104099008656493498335/) on July 01, 2010 22:42:27_

It exists in 3.12.0.GA as well :(

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 23, 2010 01:44:57_

Does it happen with Javassist 3.14 as well?

**Comment by johanhaleby** [comment]
_From [gavin.tr...@gmail.com](https://code.google.com/u/112603888548333510582/) on February 24, 2011 07:26:46_

I am getting the same error (java.lang.ClassFormatError: Invalid method Code length 70878 in class file) with the currently available download for powermockito (1,4,7) which uses javasisit 1.14.0-GA.

**Comment by johanhaleby** [comment]
_From [gavin.tr...@gmail.com](https://code.google.com/u/112603888548333510582/) on February 24, 2011 07:30:03_

Additional:
I am using org.powermock.modules.junit4.PowerMockRunner

and attempting a whenNew:
whenNew(ccPop.class).withArguments(anyInt()).thenThrow(new RuntimeException("BooHoo"));

ccPop.class is a class created with the main method of the class X defined in the @PrepareForTest annotation.

Thanks
Gavin

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 19, 2011 00:12:39_

We're using 3.14 now

**Status:** Fixed
