### ISSUE TITLE
PowerMockRunner throws UnsatisfiedLinkError with ImageIO.write()

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#161]
_From [james.de...@gmail.com](https://code.google.com/u/100394265811431995386/) on August 24, 2009 23:48:28_

What steps will reproduce the problem? 1) Create a JUnit4.4 unit test using 1.2.5 and EasyMock 2.4
2) Create a new File object, and simply make a JPEG image like this:

BufferedImage testImage = new BufferedImage(width, height,
BufferedImage.TYPE_3BYTE_BGR);
ImageIO.write(testImage, "jpeg", startFile); What is the expected output? What do you see instead? It's expected that the ImageIO will create a new JPG image. What happens,
is an exception is thrown:

Caused by: java.lang.UnsatisfiedLinkError:
com.sun.imageio.plugins.jpeg.JPEGImageWriter.initWriterIDs(Ljava/lang/Class;Ljava/lang/Class;Ljava/lang/Class;)V
	at com.sun.imageio.plugins.jpeg.JPEGImageWriter.initWriterIDs(Native Method)
	at
com.sun.imageio.plugins.jpeg.JPEGImageWriter.<clinit>(JPEGImageWriter.java:163)
	at
com.sun.imageio.plugins.jpeg.JPEGImageWriterSpi.createWriterInstance(JPEGImageWriterSpi.java:96)
	at
javax.imageio.spi.ImageWriterSpi.createWriterInstance(ImageWriterSpi.java:327)
	at javax.imageio.ImageIO$ImageWriterIterator.next(ImageIO.java:817)
	at javax.imageio.ImageIO$ImageWriterIterator.next(ImageIO.java:801)
	at javax.imageio.ImageIO.write(ImageIO.java:1471)
	at javax.imageio.ImageIO.write(ImageIO.java:1521)
	at redfin.util.ImageUtilTest.createTempJpeg(ImageUtilTest.java:17)
	at
com.redfin.uploader.photoServiceWS.PhotoServiceImplTest$DataHandlerMyMock.<init>(PhotoServiceImplTest.java:260)
	at
com.redfin.uploader.photoServiceWS.PhotoServiceImplTest.testUploadFailTwo(PhotoServiceImplTest.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:59)
	at
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$2.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:222)
	... 19 more What version of the product are you using? On what operating system? Create a JUnit4.4 unit test using 1.2.5 and EasyMock 2.4 with Java 6 and on
Windows XP

_Original issue: http://code.google.com/p/powermock/issues/detail?id=141_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on August 24, 2009 23:41:38_

Thanks for reporting this. How does your test look like? What have you prepared for test?

**Comment by johanhaleby** [comment]
_From [ask.mi...@gmail.com](https://code.google.com/u/109513406380618867527/) on August 15, 2012 09:31:05_

I get the same exact thing.  Trying to generate a receipt image that includes text and a barcode image, but get the UnsatisfiedLinkError for the JPEG writer.

**Comment by johanhaleby** [comment]
_From [ishai...@gmail.com](https://code.google.com/u/116082461651077134432/) on March 13, 2013 14:16:31_

The API that triggers an issue is only supported on 32 bit JRE on Windows as explained here: http://stackoverflow.com/questions/5207145/jai-and-imageio-for-64-bit-windows . If you are running 64 bit windows JDK/JRE - you'll have to switch to 32 bit.

**Comment by johanhaleby** [comment]
_From [james.de...@gmail.com](https://code.google.com/u/100394265811431995386/) on March 13, 2013 14:17:22_

Uh that seems like a bad "solution" don't you think?

**Comment by johanhaleby** [comment]
_From [alg...@gmail.com](https://code.google.com/u/110157750226367560430/) on March 13, 2013 14:52:47_

That doesn't really seem like a solution at all :)

**Comment by StuAtGit** [comment]
I ran into a similar problem:
  - two test suites that call different code. Doesn't matter what the test does, as long as it invokes ImageIO methods that read or write jpeg files.
  - each test suite is fine on it's own
  - run both, together, however, and you get:

```
java.lang.UnsatisfiedLinkError: Native Library /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/libjavajpeg.so already loaded in another classloader
```

The test that actually needs ImageIO to work is something like this:

```
public class ImageUtilTest {
    private static String testFile = "fluffyCloudCat.jpeg";
    private static String testFile2 = "logo.png";

    @Test
    public void jpegDecode() throws IOException, URISyntaxException {
        Path testPicture = Paths.get(ClassLoader.getSystemResource(testFile2).toURI());
        if (testPicture == null) {
            throw new IOException("Could not load test file: " + testFile2);
        }
        byte[] rawBytes = Files.readAllBytes(testPicture);
        BufferedImage rawImage = ImageUtil.read(new ByteArrayInputStream(rawBytes));

        ByteArrayOutputStream jpegScreenshot = new ByteArrayOutputStream();
        ImageUtil.encodeImageAsJpeg(rawImage, 0.7F, jpegScreenshot);
   ...
```

I tried adding the following annotations at the top of all of the tests (except the one above, that needed to test that I called ImageIO methods correctly - example, if you encode a PNG into a JPEG, it's a fairly complicated series of calls to get correct, so you really want to test you did it correctly):

```
@RunWith(PowerMockRunner.class)
@SuppressStaticInitializationFor("com.sun.imageio.plugins.jpeg.JPEGImageWriter")
```
All tests with the static initializer suppressed will need anything invoking ImageIO mocked out (or you'll get a string of weird failures about things not initializing)

This *almost* works - in that it was working fine for a while.. until I called

```
@RunWith(PowerMockRunner.class)
@SuppressStaticInitializationFor("com.sun.imageio.plugins.jpeg.JPEGImageWriter")
@PrepareForTest({ImageUtil.class})
public class GetFeatureTest {

    private static String testFile = "fluffyCloudCat.jpeg";
    private static BufferedImage bufferedImage;

    public GetFeatureTest() throws IOException {
        InputStream testPicture = ClassLoader.getSystemResourceAsStream(testFile);
        bufferedImage = ImageUtil.read(testPicture);
    }

...
```
where ImageUtil.read() is just a wrapper (so I can mock!) around:
```
    public static synchronized BufferedImage read(InputStream stream) throws IOException {
        BufferedImage image;
        image = ImageIO.read(stream);
        return image;
    }
```


In the constructor of one of the tests with the static initializer suppressed. Weirdly, the read worked in that case (despite the fact that it shouldn't have been able to load the jpeg library and therefore the plugin should fail!!!), but the original error returned in the class that does not suppress the initializer - it appears the initializer is *not* suppressed if you invoke it via the constructor of a test??

So it appear that the 
```
@SuppressStaticInitializationFor("com.sun.imageio.plugins.jpeg.JPEGImageWriter")
```
fails under some conditions. Other people have seen similar issues:
https://stackoverflow.com/questions/15830679/powermock-supressstaticinitializationfor-is-not-working

Note that *all* of this was working fine *until I used a powermock runner* (which I needed to mock out some static methods (in Selenium)).

I don't hold out too much hope for getting a real fix here, because, while powermock is usually really quite great about realizing that sometimes the answer "do don't that" is just ignorance, they appear to not have realized that sometimes, yes, initializing a shared library in a static initializer is _really what you want to do_ (at least the writers of the JDK seem to think so!!!!), given that their documentation on this subject scatters words like "EvilStaticInitializer" around the docs, which is just silly and annoying. 

https://github.com/powermock/powermock/wiki/Suppress-Unwanted-Behavior

But, hey, maybe at least understanding what's going on will help the next person to stumble onto this open bug, and maybe one day Powermock will get around to acknowledging the issue :)

**Comment by StuAtGit** [comment]
Note that if you run into unsatisfied link errors - one of the key things to do is to look at *other* tests, not the one with the error.

**Comment by StuAtGit** [comment]
Finally, the workaround to the problem I had (the one that happened when I read in the jpeg in the constructor, and the static initializer failed to be suppressed), was to move all the tests that needed any functionality into the one suite that did *not* suppress the initializer (note that, even if the static initializer suppression *had* worked, you need to do this).

In short, if you run into issues with static initializers loading a shared library:
  - put all the tests that need the functionality from the initializer/shared library in one suite/class
  - make *sure* you don't invoke that initializer anywhere: the  SuppressStaticInitializationFor annotation helps, but it is no guarantee...
