### ISSUE TITLE
Exception when stubbing static: GloballyConfiguredAnswer cannot be cast to org.mockito.ReturnValues

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#164]
_From [grant.va...@googlemail.com](https://code.google.com/u/102616953995341032579/) on September 02, 2009 11:29:50_

What steps will reproduce the problem? 1. Attempting to stub a getInstance() method of a factory to return a stub.
2. Using Junit 4.4, execute the test.
3. Issue starts from: PowerMockito.mockStatic(InvokerFactory.class); What is the expected output? What do you see instead? I expect a mock to created and usuable in the later calls:

        Mockito.when(InvokerFactory.getInvoker()).thenReturn("1"); 
        InvokerFactory.getInvoker(); What version of the product are you using? On what operating system? - Windows XP (SP1)
 - PowerMock 1.2.5.
 - Junit 4.4
 - Eclipse 3.4.2. Please provide any additional information below. ====

public class InvokerFactory
{
    private InvokerFactory(){}
    
    public static String getInvoker()
    {
        return "ret";
    }
}

====

@RunWith( PowerMockRunner.class)
@PrepareForTest({InvokerFactory.class})
public class FactorTest extends TestCase
{
    public void testd() throws ServiceException
    {     
        PowerMockito.mockStatic(InvokerFactory.class); // \<-- Error
        Mockito.when(InvokerFactory.getInvoker()).thenReturn("1"); 
        InvokerFactory.getInvoker();
    }
}

_Original issue: http://code.google.com/p/powermock/issues/detail?id=144_

**Comment by johanhaleby** [comment]
_From [grant.va...@googlemail.com](https://code.google.com/u/102616953995341032579/) on September 02, 2009 02:32:03_

Would help if I added the stack trace:

java.lang.ClassCastException: 
org.mockito.internal.stubbing.defaultanswers.GloballyConfiguredAnswer cannot be cast 
to org.mockito.ReturnValues
	at org.powermock.api.mockito.PowerMockito.createMethodInvocationControl
(PowerMockito.java:236)
	at org.powermock.api.mockito.PowerMockito.doMock(PowerMockito.java:150)
	at org.powermock.api.mockito.PowerMockito.mockStatic(PowerMockito.java:67)
	at com.rsa.core.service.wm.integration.FactorTest.testd(FactorTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke
(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke
(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:59)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$2.runTe
stMethod(PowerMockJUnit44RunnerDelegateImpl.java:222)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:79)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters
(MethodRoadie.java:87)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$2.runBe
foresThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:212)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:77)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:42)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeT
estMethod(PowerMockJUnit44RunnerDelegateImpl.java:205)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMeth
ods(PowerMockJUnit44RunnerDelegateImpl.java:159)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run
(PowerMockJUnit44RunnerDelegateImpl.java:133)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:27)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:37)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run
(PowerMockJUnit44RunnerDelegateImpl.java:131)
	at 
org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run
(JUnit4TestSuiteChunkerImpl.java:112)
	at 
org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run
(AbstractCommonPowerMockRunner.java:44)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run
(JUnit4TestReference.java:45)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run
(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests
(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests
(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run
(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main
(RemoteTestRunner.java:196)

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 02, 2009 03:30:44_

Are you using Mockito 1.8? It's not yet supported. We're working to upgrading our
PowerMock to work with Mockito 1.8 but right now it only works with 1.7.

**Comment by johanhaleby** [comment]
_From [grant.va...@googlemail.com](https://code.google.com/u/102616953995341032579/) on September 02, 2009 07:08:18_

Great stuff.  Thank you.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 02, 2009 07:42:09_

**Status:** Invalid

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 02, 2009 12:21:02_

Mockito 1.8 support is now available in the trunk
