### ISSUE TITLE
ExpectNew doesn't work properly when throwing exceptions!

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#23]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 08, 2008 09:56:10_

Method looks like:
private Target createDomainTarget(ITarget target, boolean connecting) {
        Target domainTarget = null;
        try {
            domainTarget = new Target(getTargetName(target, connecting),
target.getId());
        } catch (MyException e) {
            log.warn("Failed to get the target data from service");
            domainTarget = new Target("Unknown", -1);
        }
        return domainTarget;
    }

test looks like:

    expectNew(Target.class).andThrow(new MyException("error!"));

        final String getTargetNameMethodName = "getTargetName";
        tested =
            mockMethod(ServiceTracker.class, new String[] {
                getTargetNameMethodName}, mServiceMock,
mAutoOpenDataStreamServiceMock,
                mDataProviderAddedOrRemovedNotifierMock,
mTargetAddedOrRemovedNotifierMock);

        final boolean connecting = true;
        final String expectedTargetName = "Unknown";
        final int expectedId = -1;

        expectPrivate(tested, getTargetNameMethodName, mTargetMock1,
connecting).andReturn("A name");
        expect(mTargetMock1.getId()).andReturn(2);

        replayAll();

        Target actual = (Target) Whitebox.invokeMethod(tested,
"createDomainTarget", new Class<?>[] {
            ITarget.class, boolean.class}, mTargetMock1, connecting);

        verifyAll();

        assertEquals(expectedTargetName, actual.getName());
        assertEquals(expectedId, actual.getId());

Causes error stack:
java.lang.NullPointerException
	at
se.ericsson.eab.sdk.logcoordinator.service.DebugMuxServiceTrackerTest.testCreateDomainTarget_ITarget_fails(DebugMuxServiceTrackerTest.java:545)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:59)
	at org.junit.internal.runners.MethodRoadie.runTestMethod(MethodRoadie.java:98)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:79)
	at
org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:87)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:77)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:42)
	at
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:162)
	at
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:119)
	at
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:112)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:27)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:37)
	at
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:110)
	at
org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:74)
	at
org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:43)
	at
org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:45)
	at
org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)

The problem is that when invoking new Target(..) the exception doesn't seem
to be thrown or at least the execution is not reflected in the code, i.e.
log.warn(..) etc is never called. A new target is never created though.

_Original issue: http://code.google.com/p/powermock/issues/detail?id=3_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 13, 2008 02:52:35_

This is not an issue. This happens because the class has not been loaded by the
correct classloader since @PrepareForTest are missing classes or the user has forgot
to replay them. One needs to supply both the class that does new as well as the class
being "newed". Both has to be replayed as well.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 13, 2008 02:52:54_

**Status:** Invalid
