### ISSUE TITLE
Integration PowerMock and testNG Issues

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#244]
_From [reddy...@gmail.com](https://code.google.com/u/106938572037591757008/) on January 11, 2010 05:36:40_

What steps will reproduce the problem? 1.created a object factory in the testNG.xml file 
\<!DOCTYPE suite SYSTEM " http://testng.org/testng-1.0.dtd " >
\<suite name = "EmpappSuite" verbose = "1" 
        object-factory="org.powermock.modules.testng.PowerMockObjectFactory">
  \<test name = "daos">
     \<classes>
         \<class name = "com.DAOTest"/>
     \</classes>
  \</test>
\</suite>
2.and had a test class with a dataprovider

@PrepareForTest(DBUtil.class)
public class DAOTest {

	private EmpDAO empDAO;
	
	@Mock
	private CallableStatement cs;
	
	@Mock
	private DBUtil dbUtil;

	@BeforeMethod
	public void setUp() throws Exception {
		empDAO= new EmpDAO();
		MockitoAnnotations.initMocks(this);
	}

	/* Custom one time tearDown() implementation after test method. */
	@AfterMethod
	public void tearDownAfterTest() throws Exception {
		empDAO = null;
		cs = null;
	}

	@Test(dataProviderClass = EmpDaoDataProvider.class,
			dataProvider = "empDaorequest")
	public void testCheckoutStatus(
			CheckoutStatusRequest request) throws Exception {
		Assert.assertNotNull(request);	
		some testmethod which will take the reqest
	}
} 3. What is the expected output? What do you see instead? when i run the testNG suite i am getting the following error

java.lang.RuntimeException: Can't invoke method public void
com.DAOTest.testCheckoutStatus(the method name in that) throws
java.lang.Exception on this instance of class com.DAOTest_$$_javassist_0
due to class mismatch
	at org.testng.internal.MethodHelper.invokeMethod(MethodHelper.java:629)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:557)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:711)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1013)
	at
org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:137)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:121)
	at org.testng.TestRunner.runWorkers(TestRunner.java:908)
	at org.testng.TestRunner.privateRun(TestRunner.java:617)
	at org.testng.TestRunner.run(TestRunner.java:498)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:329)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:324)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:296)
	at org.testng.SuiteRunner.run(SuiteRunner.java:201)
	at org.testng.TestNG.createAndRunSuiteRunners(TestNG.java:915)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:879)
	at org.testng.TestNG.run(TestNG.java:787)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:75)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:127) What version of the product are you using? On what operating system? testNG 5.11, powermock-mockito-1.3.5, eclipse 3.5.1,javaassist 3.10.0
these are the jar and plugins i am using Please provide any additional information below. appreciate your help if you can help me out in this issue

_Original issue: http://code.google.com/p/powermock/issues/detail?id=224_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 13, 2010 00:32:12_

Are you using TestNG 5.11? Could you provide the class you're trying to test as well?

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 10, 2010 05:30:00_

Won't fix due to no response from user.

**Status:** WontFix

**Comment by johanhaleby** [comment]
_From [prama.an...@gmail.com](https://code.google.com/u/108698633287243981952/) on September 13, 2011 15:41:57_

I see the same error. 
The only difference is that I don't use a dataProvider.
@ObjectFactory
	public IObjectFactory getObjectFactory() {
	    return new org.powermock.modules.testng.PowerMockObjectFactory();
	    
	}
Just these lines produce a class mismatch error. 
I am using TestNG  5.13.1

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 13, 2011 23:36:20_

Unfortunately PowerMock doesn't support DataProviders with TestNG. It would be very much appreciated if you could provide a patch.

**Comment by johanhaleby** [comment]
_From [prama.an...@gmail.com](https://code.google.com/u/108698633287243981952/) on September 14, 2011 09:33:48_

I did not use a dataprovider. The problem got resolved when I updated my powermock version to 1.4.10

Thanks!

**Comment by johanhaleby** [comment]
_From [benhamid...@gmail.com](https://code.google.com/u/103476638360987803834/) on January 15, 2012 22:54:16_

I have the same error using PowerMock and TestNG DataProviders. It would be really great if you could provide a patch for this issue.
I am using TestNG 6.3.1 and powermock 1.4.11.

Regards

**Comment by johanhaleby** [comment]
_From [liu.hai...@gmail.com](https://code.google.com/u/117940592001010409379/) on November 11, 2012 19:41:26_

I have this same issue with DataProviders in testng 6.0.1 and powermock 1.4.10

**Comment by johanhaleby** [comment]
_From [dce.arc...@gmail.com](https://code.google.com/u/104674463586384243964/) on August 10, 2013 18:44:23_

I have this same issue with DataProviders in testng  and powermock. A patch would be highly appreciated.

**Comment by johanhaleby** [comment]
_From [christia...@gmail.com](https://code.google.com/u/104303689734541762059/) on October 28, 2013 15:16:48_

I have also same problems with dataproviders in testng and powermock
