### ISSUE TITLE
Cannot mock final classes that reside in packages *.junit.*, *.sun.*, and *.java.*

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#245]
_From [ash...@gmail.com](https://code.google.com/u/104493242179075932587/) on January 14, 2010 03:12:04_

What steps will reproduce the problem? 1. Create a final class in package something.junit.anything.
2. Mock the class using PowerMock. What is the expected output? What do you see instead? Mocking should succeed with Mockito despite the class being final. Instead
Mockito cannot mock the class and I get the following stacktrace:

java.lang.IllegalArgumentException: Cannot subclass final class class
somepackage.junit.SomeFinalClass
	at org.mockito.cglib.proxy.Enhancer.generateClass(Enhancer.java:447)
	at
org.mockito.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at
org.mockito.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:217)
	at org.mockito.cglib.proxy.Enhancer.createHelper(Enhancer.java:378)
	at org.mockito.cglib.proxy.Enhancer.createClass(Enhancer.java:318)
	at
org.mockito.internal.creation.jmock.ClassImposterizer.createProxyClass(ClassImposterizer.java:93)
	at
org.mockito.internal.creation.jmock.ClassImposterizer.imposterise(ClassImposterizer.java:50)
	at
org.powermock.api.mockito.internal.mockcreation.MockCreator.createMethodInvocationControl(MockCreator.java:79)
	at
org.powermock.api.mockito.internal.mockcreation.MockCreator.mock(MockCreator.java:53)
	at org.powermock.api.mockito.PowerMockito.mock(PowerMockito.java:80)
	at SomeFinalClassTest.test(SomeFinalClassTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:66)
	at
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:322)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:86)
	at
org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:94)
	at
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:309)
	at
org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:112)
	at
org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:73)
	at
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:297)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:84)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:49)
	at
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:222)
	at
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:161)
	at
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:135)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	at
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:133)
	at
org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:112)
	at
org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:55)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:60) What version of the product are you using? On what operating system? Problem occurs in most (probably all) versions of PowerMock that support
Mockito. Yes, I really tried most of them. OS: Snow Leopard. Please provide any additional information below. I did a lot of legwork to track down this problem (looking at ClassLoader
code is FUN!). 

The MockClassLoader is deciding to defer any class that matches "junit." to
the system ClassLoader. The problem arises from the WildcardMatcher
successfully matching "junit." with
"something.junit.anything.MyJUnitSupportClass".

I understand the desire; however the side effect is that anyone that uses
"junit", "sun", or "java" package names are left in the dark.

_Original issue: http://code.google.com/p/powermock/issues/detail?id=225_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 14, 2010 13:31:54_

I could have guessed this would turn up some day :) I suppose we should at least 
change it delegate packages _starting with_ org.junit, java etc? That would probably 
be enough to solve your problems I suppose?

**Status:** Accepted  
  **Labels:** Milestone-Release1.4

**Comment by johanhaleby** [comment]
_From [ash...@gmail.com](https://code.google.com/u/104493242179075932587/) on January 14, 2010 15:10:14_

Yes that would be a sufficient fix for my problem.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 22, 2010 01:08:34_

Actually it was not the problem that I expected. Th problem was in the Wildcard 
matcher because it didn't work properly. This bug was introduced in PowerMock 1.3. It 
should now have been fixed (please verify it if you like). 

Thanks!

**Status:** Fixed

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 11, 2010 13:19:22_

Issue 231 has been merged into this issue.
