### ISSUE TITLE
Spying on anonymous inner class causes StringIndexOutOfBoundsException in Mockito

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#247]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 21, 2010 10:28:47_

When sut is created using: 
tested = new AbstractSomething() {
			@Override
			protected void something throws Exception {
			}
		};

We get:
java.lang.StringIndexOutOfBoundsException: String index out of range: 1
	at java.lang.String.substring(String.java:1934)
	at 
org.powermock.api.mockito.internal.mockcreation.MockCreator.toInstanceName(
MockCreator.java:88)
	at 
org.powermock.api.mockito.internal.mockcreation.MockCreator.mock(MockCreato
r.java:44)
	at org.powermock.api.mockito.PowerMockito.spy(PowerMockito.java:97)
	at 
com.dts.infrastructure.support.event.AbstractEventHandlerTest.delegatesEven

This is because getSimpleName is empty.

_Original issue: http://code.google.com/p/powermock/issues/detail?id=227_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 21, 2010 01:29:02_

**Summary:** Spying on anonymous inner class causes StringIndexOutOfBoundsException in Mockito

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 22, 2010 02:12:03_

**Status:** Fixed
