### ISSUE TITLE
Improve TestNG exception messages

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#250]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on February 01, 2010 08:32:00_

When an exception occurs in the method you get an InvocationTargetException 
instead of the actual exception in TestNG. E.g.:

java.lang.reflect.InvocationTargetException
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke
(NativeMethodAccessorImpl.java:39)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke
(DelegatingMethodAccessorImpl.java:25)
       at java.lang.reflect.Method.invoke(Method.java:597)
       at
org.powermock.modules.testng.internal.PowerMockTestNGMethodHandler.invoke
(PowerMockTestNGMethodHandler.java:48)
       at org.abqjug.testingtools.JukeboxTest_$
$_javassist_1.testGetExternalServiceInformation(JukeboxTest_$
$_javassist_1.java)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke
(NativeMethodAccessorImpl.java:39)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke
(DelegatingMethodAccessorImpl.java:25)
       at java.lang.reflect.Method.invoke(Method.java:597)
       at org.testng.internal.MethodHelper.invokeMethod(MethodHelper.java:
644)
       at org.testng.internal.Invoker.invokeMethod(Invoker.java:546)
       at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:700)
       at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1002)
       at org.testng.internal.TestMethodWorker.invokeTestMethods
(TestMethodWorker.java:137)
       at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:
121)
       at org.testng.TestRunner.runWorkers(TestRunner.java:909)
       at org.testng.TestRunner.privateRun(TestRunner.java:618)
       at org.testng.TestRunner.run(TestRunner.java:499)
       at org.testng.SuiteRunner.runTest(SuiteRunner.java:332)
       at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:327)
       at org.testng.SuiteRunner.privateRun(SuiteRunner.java:299)
       at org.testng.SuiteRunner.run(SuiteRunner.java:204)
       at org.testng.TestNG.createAndRunSuiteRunners(TestNG.java:915)
       at org.testng.TestNG.runSuitesLocally(TestNG.java:879)
       at org.testng.TestNG.run(TestNG.java:787)
       at org.apache.maven.surefire.testng.TestNGExecutor.run
(TestNGExecutor.java:74)
       at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute
(TestNGXmlTestSuite.java:92)
       at org.apache.maven.surefire.Surefire.run(Surefire.java:180)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke
(NativeMethodAccessorImpl.java:39)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke
(DelegatingMethodAccessorImpl.java:25)
       at java.lang.reflect.Method.invoke(Method.java:597)
       at 
org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess
(SurefireBooter.java:350)
       at org.apache.maven.surefire.booter.SurefireBooter.main
(SurefireBooter.java:1021)
Caused by:
org.mockito.exceptions.misusing.MissingMethodInvocationException:
when() requires an argument which has to be a method call on a mock.
For example:
   when(mock.getArticles()).thenReturn(articles);

Also, this error might show up because you stub final/private/equals()
or hashCode() method.
Those methods *cannot* be stubbed/verified.

       at 
org.powermock.api.mockito.PowerMockito.when(PowerMockito.java:343)
       at
org.abqjug.testingtools.JukeboxTest.testGetExternalServiceInformation
(JukeboxTest.java:35)
       at org.abqjug.testingtools.JukeboxTest_$
$_javassist_1._d3testGetExternalServiceInformation(JukeboxTest_$
$_javassist_1.java)
       ... 35 more

_Original issue: http://code.google.com/p/powermock/issues/detail?id=230_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 20, 2010 15:12:56_

Fixed in 1.3.8

**Status:** Fixed
