### ISSUE TITLE
Illegal class modifiers in class when modifying interfaces

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#262]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 21, 2010 09:12:53_

java.lang.ClassFormatError: Illegal class modifiers in class com/
liveops/integration/util/LOIntegrationServiceSetter: 0x621
       at java.lang.ClassLoader.defineClass1(Native Method)
       at java.lang.ClassLoader.defineClass(ClassLoader.java:698)
       at java.lang.ClassLoader.defineClass(ClassLoader.java:544)
       at
org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:
211)
       at
org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:
146)
       at
org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:
63)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:250)
       at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:398)
       at java.lang.Class.forName0(Native Method)
       at java.lang.Class.forName(Class.java:247)
       at
sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:
95)
       at
sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:
107)
       at
sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:
31)
       at
sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:
370)
       at
sun.reflect.annotation.AnnotationParser.parseClassValue(AnnotationParser.java:
351)
       at
sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:
653)
       at
sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:
460)
       at
sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:
286)
       at
sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:
222)
       at
sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:
69)
       at
sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:
52)
       at java.lang.Class.initAnnotationsIfNecessary(Class.java:3070)
       at java.lang.Class.getAnnotations(Class.java:3050)
       at
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.classAnnotations(PowerMockJUnit44RunnerDelegateImpl.java:
178)
       at
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.getDescription(PowerMockJUnit44RunnerDelegateImpl.java:
170)
       at
org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.getDescription(JUnit4TestSuiteChunkerImpl.java:
173)
       at
org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.getDescription(AbstractCommonPowerMockRunner.java:
50)
       at
org.eclipse.jdt.internal.junit4.runner.JUnit4TestClassReference.sendTree(JUnit4TestClassReference.java:
38)
       at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.sendTrees(RemoteTestRunner.java:
476)
       at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:
464)
       at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:
683)
       at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:
390)
       at
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:
197)

The interface in question is quite simple:

package com.liveops.integration.util;

public interface LOIntegrationServiceSetter {
       void setService(Class<?> serviceClass, Object serviceInstance);
       void clearService(Class<?> serviceClass);
}

_Original issue: http://code.google.com/p/powermock/issues/detail?id=242_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on April 10, 2011 05:50:27_

**Labels:** -Milestone-Release1.5 Milestone-Release1.6

**Comment by plum117** [comment]
Is there any work around?
