### ISSUE TITLE
NullPointerException on verifyNew

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#264]
_From [Alexandr...@gmail.com](https://code.google.com/u/100899915105869891957/) on March 24, 2010 15:51:04_

What steps will reproduce the problem? Calling verifyNew to check for constructor call will generate a
NullPointerException, unless you also call whenNew on the same constructor
(of course, with the correct timing, meaning before the call to the method
being tested). What is the expected output? What do you see instead? If I don't want to specifically mock a constructor (with whenNew) in order
to use a verifyNew on it, then PowerMock should do it automatically, not
throw NullPointerException. What version of the product are you using? On what operating system? 1.3.6 on Windows XP 32 bits, with SP2 Please provide any additional information below. After watching the PowerMock code a bit, I realized that verifyNew is
looking for a mock substitute in some sort of "Mockings container". A
friend came up with the idea that there should be a check (inside the
verifyNew method implementation) before calling the assert on the mocked
object.

_Original issue: http://code.google.com/p/powermock/issues/detail?id=244_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 24, 2010 08:16:17_

Could you provide a test case that demonstrates the issue? Would be awesome and would 
really help us to solve it faster

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 25, 2010 05:36:34_

From Adrian Smith:

I have 2 classes:

public class Test1 {
    public void doit() {
        new Test2();
    }
}


public class Test2 {

}

and a test class :

import org.junit.Test;
import org.junit.runner.RunWith;
import org.powermock.api.mockito.PowerMockito;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;

@RunWith(PowerMockRunner.class)
@PrepareForTest(Test1.class)
public class Test1Test {

    private Test1 test1;

    @Test
    public void testDoit() throws Exception {
        test1 = new Test1();

        test1.doit();

        PowerMockito.verifyNew(Test2.class).withNoArguments();
    }

}

When I run the test I get:

java.lang.IllegalArgumentException: A constructor invocation in class 
com.bt.pi.app.instancemanager.Test2 was unexpected.
	at org.powermock.api.mockito.PowerMockito.verifyNew(PowerMockito.java:361)
	at com.bt.pi.app.instancemanager.Test1Test.testDoit(Test1Test.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at 
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:66)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMo
ckJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:322)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:86)
	at 
org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.jav
a:94)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMo
ckJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:309)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMo
ckJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:112)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMo
ckJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:73)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMo
ckJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl
.java:297)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:84)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:49)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeT
estMethod(PowerMockJUnit44RunnerDelegateImpl.java:222)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMeth
ods(PowerMockJUnit44RunnerDelegateImpl.java:161)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(P
owerMockJUnit44RunnerDelegateImpl.java:135)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(Pow
erMockJUnit44RunnerDelegateImpl.java:133)
	at 
org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUni
t4TestSuiteChunkerImpl.java:112)
	at 
org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(A
bstractCommonPowerMockRunner.java:55)
	at 
org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.ja
va:46)
	at 
org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at 
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java
:467)
	at 
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java
:683)
	at 
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at 
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197
)

If I change the verifyNew line to

        PowerMockito.verifyNew(Test2.class, times(1)).withNoArguments();

I get:

java.lang.NullPointerException
	at org.powermock.api.mockito.PowerMockito.verifyNew(PowerMockito.java:395)
	at com.bt.pi.app.instancemanager.Test1Test.testDoit(Test1Test.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at 
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:66)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMo
ckJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:322)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:86)
	at 
org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.jav
a:94)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMo
ckJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:309)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMo
ckJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:112)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMo
ckJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:73)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMo
ckJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl
.java:297)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:84)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:49)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeT
estMethod(PowerMockJUnit44RunnerDelegateImpl.java:222)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMeth
ods(PowerMockJUnit44RunnerDelegateImpl.java:161)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(P
owerMockJUnit44RunnerDelegateImpl.java:135)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	at 
org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(Pow
erMockJUnit44RunnerDelegateImpl.java:133)
	at 
org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUni
t4TestSuiteChunkerImpl.java:112)
	at 
org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(A
bstractCom...

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 25, 2010 05:36:34_

...monPowerMockRunner.java:55)
	at 
org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.ja
va:46)
	at 
org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at 
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java
:467)
	at 
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java
:683)
	at 
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at 
org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197
)

**Status:** Accepted  
  **Labels:** Milestone-Release1.4

**Comment by johanhaleby** [comment]
_From [Alexandr...@gmail.com](https://code.google.com/u/100899915105869891957/) on March 25, 2010 07:12:01_

it seems that in version 1.3.6 one part of this problem has been fixed. 


1. the method verifyNew with no verificationMode

  public static synchronized \<T> ConstructorArgumentsVerification verifyNew(Class<T>
mock)

does a check now and then throws Exception (** Although the message wrong, since the
call was expected **)

  if (invocationControl == null) {
			throw new IllegalArgumentException(String.format("A constructor invocation in %s
was unexpected.", Whitebox.getType(mock)));
		}

2. but, the verifyNew with a verificationMode

public static \<T> ConstructorArgumentsVerification verifyNew(Class<?> mock,
VerificationMode mode)

still throws NullPointerException

**Attachment:** [ClassUnderTesting.java CompositeClass.java ExampleTest.java](http://code.google.com/p/powermock/issues/detail?id=244#hc4)

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 25, 2010 10:50:36_

PowerMock doesn't have support verifying new object instances when they haven't been 
verified. That's why it doesn't work.

**Status:** Duplicate  
  **Mergedinto:** 248

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 25, 2010 12:43:48_

I've committed a patch for the NPE bug in r1287 .
