### ISSUE TITLE
@PrepareForTest causes LocalVariableTable error when using log4j

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#286]
_From [kevin.ki...@gmail.com](https://code.google.com/u/111821237685742939965/) on July 09, 2010 23:12:47_

What steps will reproduce the problem? 1. Create a class to test that defines Logger from log4j
2. Create a unit test for that class with the @PrepareForTest Attribute
3. Run the test case with the "Run as JUnit" in eclipse
4. Error occurs with "Invalid length XXXX in LocalVariableTable" What is the expected output? What do you see instead? It should not throw an exception What version of the product are you using? On what operating system? powermock-mockito-1.3.8-full.jar Please provide any additional information below. *Removing the Logger prevents the exception.
*Removing the Attribute prevents the exception.

_Original issue: http://code.google.com/p/powermock/issues/detail?id=266_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 14, 2010 05:18:31_

Could it be a bug in Javassist?

**Comment by johanhaleby** [comment]
_From [kevin.ki...@gmail.com](https://code.google.com/u/111821237685742939965/) on July 14, 2010 15:16:16_

I don't think so. Here is the stack trace:java.lang.ClassFormatError: Invalid length 493 in LocalVariableTable in class file com/inlethd/grapeshot/library/element/Channel
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:632)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:616)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:466)
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:211)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:146)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:247)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:95)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:107)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:31)
	at sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:370)
	at sun.reflect.annotation.AnnotationParser.parseClassValue(AnnotationParser.java:351)
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:653)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:460)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:222)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:69)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:52)
	at java.lang.Class.initAnnotationsIfNecessary(Class.java:3070)
	at java.lang.Class.getAnnotations(Class.java:3050)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.classAnnotations(PowerMockJUnit44RunnerDelegateImpl.java:178)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.getDescription(PowerMockJUnit44RunnerDelegateImpl.java:170)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.getDescription(JUnit4TestSuiteChunkerImpl.java:182)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.getDescription(AbstractCommonPowerMockRunner.java:50)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestClassReference.sendTree(JUnit4TestClassReference.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.sendTrees(RemoteTestRunner.java:476)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 15, 2010 02:09:59_

Looks similar to https://jira.jboss.org/browse/JASSIST-99 but it should be fixed in version 3.12.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 15, 2010 02:12:19_

Which version of javassist are you using?

**Comment by johanhaleby** [comment]
_From [kevin.ki...@gmail.com](https://code.google.com/u/111821237685742939965/) on July 16, 2010 09:18:04_

Don't know. How do I find out?

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 20, 2010 12:23:37_

You need to check in your classpath. If you're using Maven do "mvn dependency:tree". A new version of Javassist (3.13) was just released. Please try if you have the same issue with that version.

**Comment by johanhaleby** [comment]
_From [kevin.ki...@gmail.com](https://code.google.com/u/111821237685742939965/) on September 03, 2010 04:54:17_

Looks like this is fixed in the new release. powermock-mockito-1.4 using the new javassist-3.13.0.GA.jar.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 08, 2010 02:11:48_

Great, then I close this issue.

**Status:** Fixed

**Comment by johanhaleby** [comment]
_From [lin.xing...@gmail.com](https://code.google.com/u/104640163254852912434/) on March 10, 2014 12:16:31_

Hi, I'm still getting this error. I'm using powermock-core-1.5.1.jar and javassist-3.16.1-GA.jar.

java.lang.ClassFormatError: Invalid length 4012 in LocalVariableTable in class file lc/commonservice/repository/LCActorRepository
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:465)
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:222)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:147)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:67)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:247)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:95)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:107)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:31)
	at sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:370)
	at sun.reflect.annotation.AnnotationParser.parseClassValue(AnnotationParser.java:351)
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:653)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:460)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:222)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:69)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:52)
	at java.lang.Class.initAnnotationsIfNecessary(Class.java:3070)
	at java.lang.Class.getAnnotations(Class.java:3050)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.classAnnotations(PowerMockJUnit44RunnerDelegateImpl.java:165)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.getDescription(PowerMockJUnit44RunnerDelegateImpl.java:157)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.getDescription(JUnit4TestSuiteChunkerImpl.java:171)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.getDescription(AbstractCommonPowerMockRunner.java:47)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestClassReference.sendTree(JUnit4TestClassReference.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.sendTrees(RemoteTestRunner.java:476)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

**Comment by johanhaleby** [comment]
_From [lin.xing...@gmail.com](https://code.google.com/u/104640163254852912434/) on March 10, 2014 14:20:09_

Sorry, I was using javassist-3.11 actually. After using javassist-3.12.1.GA.jar, I make it working fine. Thanks.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 11, 2014 04:28:19_

Javassist 3.11 is really old, please use the latest version

**Comment by johanhaleby** [comment]
_From [Ferrucci...@gmail.com](https://code.google.com/u/115929389490724795639/) on May 06, 2014 20:09:12_

hi,guys
I am getting this issue with javassist3.15GA
anyone can help~

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 06, 2014 21:48:29_

Upgrade to a newer Javassist release.

**Comment by johanhaleby** [comment]
_From [ashok.k...@gmail.com](https://code.google.com/u/111348232504336031712/) on May 29, 2014 00:19:28_

Hi,

This error exists even with the latest version powermock & javassist.

Versions of libs:
powermock-core-1.5.4.jar and javassist-3.18.1-GA.jar.

Is there a remedy for this problem?

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 29, 2014 07:37:37_

Not that I know of, there may be some tips here: https://code.google.com/p/powermock/issues/detail?id=355
