### ISSUE TITLE
 Strange Console behavior on Powermock 1.4 

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#292]
_From [chiiwen@gmail.com](https://code.google.com/u/chiiwen@gmail.com/) on August 13, 2010 00:44:38_

What steps will reproduce the problem? 1. Have following powermock code 
 Console console=createMock(Console.class); What is the expected output? What do you see instead? It compile ok under 1.3.9, Get following error on 1.4.0
java.lang.RuntimeException: javassist.CannotCompileException: by
javassist.CannotCompileException: no inheritable constructor in
java.lang.Appendable
        at
org.powermock.core.ConcreteClassGenerator.createConcreteSubClass(ConcreteClassGenerator.java:
63)
        at
org.powermock.core.DefaultFieldValueGenerator.instantiateFieldType(DefaultFieldValueGenerator.java:
56)
        at
org.powermock.core.DefaultFieldValueGenerator.fillWithDefaultValues(DefaultFieldValueGenerator.java:
38)
        at
org.powermock.core.DefaultFieldValueGenerator.fillWithDefaultValues(DefaultFieldValueGenerator.java:
39)
        at
org.powermock.core.DefaultFieldValueGenerator.fillWithDefaultValues(DefaultFieldValueGenerator.java:
39)
        at org.powermock.api.easymock.PowerMock.doMock(PowerMock.java:2146)
        at org.powermock.api.easymock.PowerMock.createMock(PowerMock.java:98) What version of the product are you using? On what operating system? Powermock 1.4 under Windows XP. Please provide any additional information below.

_Original issue: http://code.google.com/p/powermock/issues/detail?id=272_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on August 13, 2010 06:20:16_

Is this the standard Console class from Java 6?

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on August 23, 2010 00:15:49_

**Status:** Fixed
