### ISSUE TITLE
Unit Test initialization Error when unit testing MongoDB Java Driver

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#297]
_From [kevin.ki...@gmail.com](https://code.google.com/u/111821237685742939965/) on September 03, 2010 14:40:49_

What steps will reproduce the problem? 1. Create a class that uses MongoDB Java Driver v2.1
2. Create a unit test for class that uses MongoDB
3. Run unit test What is the expected output? What do you see instead? Test execution successful What version of the product are you using? On what operating system? Linux, powermock-mockito-1.4 Please provide any additional information below. I've attached an eclipse project that I was able to reproduce the issue with.

Stack Trace.
java.lang.LinkageError: loader constraint violation: loader (instance of org/powermock/core/classloader/MockClassLoader) previously initiated loading for a different type with name "javax/management/MBeanServer"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:632)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:616)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:466)
	at org.powermock.core.classloader.MockClassLoader.loadUnmockedClass(MockClassLoader.java:190)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:148)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
	at com.mongodb.DBPortPool$Holder.get(DBPortPool.java:58)
	at com.mongodb.DBTCPConnector._set(DBTCPConnector.java:458)
	at com.mongodb.DBTCPConnector.<init>(DBTCPConnector.java:46)
	at com.mongodb.Mongo.<init>(Mongo.java:137)
	at com.mongodb.Mongo.<init>(Mongo.java:123)
	at com.mongodb.Mongo.<init>(Mongo.java:113)

**Attachment:** [PowerMockError.tar.gz](http://code.google.com/p/powermock/issues/detail?id=277)

_Original issue: http://code.google.com/p/powermock/issues/detail?id=277_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 12, 2010 07:51:19_

I've seen several reports of this kind lately. It could be a Javassist issue actually and in that case we'll have to wait until the next version of Javassist to be released and hope that they've fixed it. It would be of great interest for us if you could try to run the code in PowerMock 1.3.9 with Javassist 3.13 and see if it makes any difference? It could also be a problem that MongoDB instantiates classes using reflection with a different classloader. You could try to make use of the @PowerMockIgnore annotation to see if you can get around it. For example try using @PowerMockIgnore("javax.management.MBeanServer").

**Status:** Accepted

**Comment by johanhaleby** [comment]
_From [yishi...@gmail.com](https://code.google.com/u/102957691498543265549/) on October 07, 2010 20:09:45_

should some one familiar with powermock and Javassist fix it? We all bocked at this issue.
Thank you very much.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 07, 2010 22:42:55_

Hmm I think I was a bit fast blaming Javassist. I think it must be an error in the MockClassloader. Could you try using @PowerMockIgnore("javax.management.*")?

**Comment by johanhaleby** [comment]
_From [Cesar.Al...@gmail.com](https://code.google.com/u/103740526430257579704/) on October 28, 2010 10:42:15_

I have found the same problem and [@PowerMockIgnore("javax.management.*")] solves it.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 28, 2010 11:40:50_

Thanks a lot for sharing!

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 14, 2010 23:48:28_

**Status:** WontFix

**Comment by johanhaleby** [comment]
_From [ranjith1...@gmail.com](https://code.google.com/u/106709941051083230870/) on September 27, 2012 21:49:06_

Thanks, my problem is solved with @PowerMockIgnore("javax.management.*")

**Comment by johanhaleby** [comment]
_From [aram.ope...@gmail.com](https://code.google.com/u/114319298694243104843/) on November 01, 2012 07:11:30_

Yeah.  I also found that this worked to fix the same issue: @PowerMockIgnore("javax.management.*").

Although note that in Scala, the syntax is slightly different for all of the class annotations:

@RunWith(classOf[PowerMockRunner])
@PrepareForTest(Array(classOf[Broker]))
@PowerMockIgnore(Array("javax.management.*"))

**Comment by johanhaleby** [comment]
_From [StatueOf...@gmail.com](https://code.google.com/u/106324076688393526973/) on January 13, 2015 16:47:47_

I have a similar problem. The difference for me is that it is causing an error in a logback-classic class. The result is that my tests still run and pass, but errors are reported.

`@PowerMockIgnore("javax.management.*")` with my other test class annotations fixes it for me too!

I'll attach my error log in case it is helpful for anyone here.

**Attachment:** [Logback-PowerMock-LinkageError.log.txt](http://code.google.com/p/powermock/issues/detail?id=277#hc9)

**Comment by johanhaleby** [comment]
_From [StatueOf...@gmail.com](https://code.google.com/u/106324076688393526973/) on January 13, 2015 17:06:07_

Is my error, from https://code.google.com/p/powermock/issues/detail?id=277#c9 A separate issue? Should I make a new ticket for it?
