### ISSUE TITLE
We need a better error message when expectNew fails due to too many calls to new.

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#30]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 11, 2008 10:59:31_

If we do expectNew(MyClass.class) once but it's called twice we should get
a more descriptive error message than the following: 

java.lang.RuntimeException: java.lang.AssertionError: 
  Unexpected method call createInstance():
    createInstance(): expected: 1, actual: 1 (+1)
	at org.powermock.Whitebox.performMethodInvocation(Whitebox.java:788)
	at org.powermock.Whitebox.invokeMethod(Whitebox.java:268)
	at se.myapp.MyTest.testCreateDomainTarget(MyTest.java:577)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

We could perhaps catch the AssertionError in MockGateway line 117 (	return
newInvocationControl.createInstance()) and throw another AssertionError
with a better description instead.

_Original issue: http://code.google.com/p/powermock/issues/detail?id=10_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 11, 2008 02:03:57_

**Labels:** -Type-Defect Type-Enhancement

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 13, 2008 04:06:15_

Better error message when expectNew fails due to too many calls to new when a method
was invoked using reflection.

**Status:** Fixed
