### ISSUE TITLE
Verification of instance methods in final system classes is not possible in the Mockito API extension

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#317]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on December 02, 2010 15:14:22_

@Test
	public void mockingURLWorks() throws Exception {
		URL url = mock(URL.class);
		URLConnection urlConnectionMock = mock(URLConnection.class);

		when(url.openConnection()).thenReturn(urlConnectionMock);

		URLConnection openConnection = url.openConnection();

		assertSame(openConnection, urlConnectionMock);
        verify(url).openConnection(); // This causes the problem because url is NOT a mock.
    }

Possible solution: We could create a replica class which we mock and return which delegates all instance calls to the final system class instance.

_Original issue: http://code.google.com/p/powermock/issues/detail?id=297_

**Comment by johanhaleby** [comment]
_From [datangli...@gmail.com](https://code.google.com/u/110669498715278348469/) on March 18, 2011 03:08:09_

Does it support currently?

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 18, 2011 03:15:29_

This is not implemented yet and unfortunately it's not prioritized either. But that could change if there are many people interested in the fix.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on April 10, 2011 05:48:09_

**Labels:** -Milestone-Release1.5 Milestone-Release1.6

**Comment by johanhaleby** [comment]
_From [marceloverdijk](https://code.google.com/u/marceloverdijk/) on November 02, 2011 13:34:07_

I have a similar problem with mocking UUID classes.

UUID uuid = org.powermock.api.mockito.PowerMockito.mock(UUID.class) returns an actual UUID instance and not a mock.

Hope priority can be reaised for this issue.

**Comment by johanhaleby** [comment]
_From [m.jedy...@gmail.com](https://code.google.com/u/107002048342271862915/) on November 19, 2011 08:36:37_

Please increase its priority. I'm developing Intellij IDEA plugin, and this bug prevents me from testing a lot of methods (IDEA api uses static stuff a lot :-( ).

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 19, 2011 09:15:39_

It should be possible to verify methods in the IDEA api. The issue here is only for final system classes (i.e. classes in the "java.*" package (e.g. java.lang)).

**Comment by johanhaleby** [comment]
_From [m.jedy...@gmail.com](https://code.google.com/u/107002048342271862915/) on November 26, 2011 05:56:55_

A lot of static methods in IDEA api has inside calls to java.lang. 

I'm getting:
java.lang.VerifyError: (class: javax/swing/plaf/metal/MetalLookAndFeel, method: getLayoutStyle signature: ()Ljavax/swing/LayoutStyle;) Wrong return type in function
	at javax.swing.UIManager.setLookAndFeel(UIManager.java:554)
	at javax.swing.UIManager.initializeDefaultLAF(UIManager.java:1317)
	at javax.swing.UIManager.initialize(UIManager.java:1406)
	at javax.swing.UIManager.maybeInitialize(UIManager.java:1394)
	at javax.swing.UIManager.getUI(UIManager.java:980)
	at javax.swing.JLabel.updateUI(JLabel.java:256)
	at javax.swing.JLabel.<init>(JLabel.java:145)
	at javax.swing.JLabel.<init>(JLabel.java:216)
	at com.intellij.openapi.util.IconLoader.<clinit>(IconLoader.java:50)
	at com.intellij.openapi.ui.DialogWrapper.<clinit>(DialogWrapper.java:202)
I thought that it's because of this issue, maybe I'm wrong?

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 27, 2011 23:20:11_

But can't you mock the IDEA classes instead? Or are you writing some sort of integration test?

**Comment by johanhaleby** [comment]
_From [m.jedy...@gmail.com](https://code.google.com/u/107002048342271862915/) on November 29, 2011 16:36:07_

Sorry, I made wrong assumptions and didn't express myself clearly.
In my production code I'm instantiating com.intellij.ide.util.PackageChooserDialog class (I can't use any dependency injection framework, so I separated it to a factory). In my test I want to mock instantiation of it using 'whenNew'. In order to do that, I need to return a mock of this class, but when I'm trying to mock it (Mockito.mock(PackageChooserDialog.class)) it throws the stack from above. When I'm using Mockito alone (without Powermock with PrepareForTest annotation), mock is created correctly (but I cannot use 'whenNew').
Should be probably reported as a new issue?

**Comment by ZhongchaoZhao** [comment]
I'm trying to mock Thread.sleep(). Failed every way copied from wiki. 
For example:
PowerMockito.doNothing().when(Thread.sleep(1000)); // Got this from wiki of mockito, not compile.
