### ISSUE TITLE
problem in using PowerMock

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#321]
_From [cndoublehero@gmail.com](https://code.google.com/u/cndoublehero@gmail.com/) on December 20, 2010 11:47:00_

Hi, I get a problem in using the PowerMock suite. You can copy my Junit test file into your project. When you run the BTestForJunit3 class as a Java Application, the result will be passed, but when you run the BTestForJunit3 class as a Junit Test, the result will be failed and a exception will print at the console page. I think it is not a correct behavior, what do you think? The detail of exception as follow:

java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.LinkedList.entry(LinkedList.java:368)
	at java.util.LinkedList.get(LinkedList.java:313)
	at org.powermock.modules.junit3.internal.impl.JUnit3TestSuiteChunkerImpl.testAt(JUnit3TestSuiteChunkerImpl.java:199)
	at org.powermock.modules.junit3.PowerMockSuite.testAt(PowerMockSuite.java:97)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.sendTree(JUnit3TestReference.java:142)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.sendTrees(RemoteTestRunner.java:469)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:457)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)

As you see, the version of the junit framework which I'm using is Junit3.8.2. Thank you.

**Attachment:** [PowerMockTest.rar](http://code.google.com/p/powermock/issues/detail?id=301)

_Original issue: http://code.google.com/p/powermock/issues/detail?id=301_

**Comment by johanhaleby** [comment]
_From [cndoublehero@gmail.com](https://code.google.com/u/cndoublehero@gmail.com/) on December 20, 2010 03:06:11_

I use the latest version of powermock.I download a  powermock-easymock-junit-1.4.6.zip file from this site.Thank you.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on December 26, 2010 01:55:25_

This is a bug, thanks for your example. A work-around is to move the PrepareToTest annotation to the class-level instead of method-level.

Would also really encourage you to upgrade to JUnit 4.

**Status:** Accepted  
  **Labels:** Milestone-Release2.0
