### ISSUE TITLE
TooManyConstructorsFoundException in Using MemberModifier.suppress method

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#322]
_From [cndoublehero@gmail.com](https://code.google.com/u/cndoublehero@gmail.com/) on December 22, 2010 11:20:07_

Hi, I get a problem in using the PowerMock suite. You can copy my Junit test file into your project. When you run the AppaleListTest class as a Junit Test, the result will be failed and a exception will print at the console page. 
The situation is like this:
You have two constructors in your class, one constructor have no arguments and the other has some arguments, when you want to suppress the constructor with no arguments and write your code like this:

MemberModifier.suppress(MemberModifier.constructor(AppaleList.class));

The Junit test can't passed. Although there are other solution to solve this problem, like write code as this : 
MemberModifier.suppress(AppaleList.class.getConstructor(null));

But I think may be MemberModifier can do a better job. So I think it is a problem. Thank you.

The detail of exception as follow:

org.powermock.reflect.exceptions.TooManyConstructorsFoundException: Several matching constructors found, please specify the argument parameter types so that PowerMock can determine which method you're refering to.
Matching constructors in class org.apache.test.Constructor.AppaleList were:
org.apache.test.Constructor.AppaleList( )
org.apache.test.Constructor.AppaleList( java.lang.String.class )

	at org.powermock.reflect.internal.WhiteboxImpl.throwExceptionWhenMultipleConstructorMatchesFound(WhiteboxImpl.java:1874)
	at org.powermock.reflect.internal.WhiteboxImpl.findConstructorOrThrowException(WhiteboxImpl.java:1112)
	at org.powermock.api.support.membermodification.MemberMatcher.constructor(MemberMatcher.java:277)
	at org.apache.test.Constructor.AppaleListTest.list3(AppaleListTest.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:585)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:66)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:322)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:86)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:94)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:309)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:112)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:73)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:297)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:84)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:49)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:222)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:161)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:135)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:133)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:112)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:57)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:45)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:673)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:386)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:196)

Ps: I use the latest version of powermock.I download a  powermock-easymock-junit-1.4.6.zip file from this site.Thank you.

**Attachment:** [PowerMockTest1.rar](http://code.google.com/p/powermock/issues/detail?id=302)

_Original issue: http://code.google.com/p/powermock/issues/detail?id=302_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on December 26, 2010 02:29:04_

Actually the javadoc is lying for MemberMatcher.constructor(..). It does not return the default constructor but ANY constructor. Thus you get the error. The javadoc has now been corrected a new method, MemberMatcher.defaultConstructorIn(..), has now been added. Until the next version is released you can use:

suppress(constructor(AppaleList.class, new Class[0])); // Suppress only the default ctor
suppress(constructorsDeclaredIn(AppaleList.class); // Suppress all constructors in AppaleList

Thanks for reporting.

**Status:** Fixed  
  **Labels:** Milestone-Release1.4
