### ISSUE TITLE
MockStaticTest.testMockStatic failing with IllegalStateException: no last call on a mock available

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#330]
_From [satya1...@gmail.com](https://code.google.com/u/101185683620560696824/) on January 27, 2011 08:49:08_

What steps will reproduce the problem? 1.downloaded powermock-easymock-junit-1.4.7.zip
2. download the files StaticService.class, StaticHelper.class
3.Run the test class MockStaticTest
4. test case fails with
java.lang.IllegalStateException: no last call on a mock available
	at org.easymock. EasyMock .getControlForLastCall( EasyMock .java:521)
	at org.easymock. EasyMock .expect( EasyMock .java:499)
	at com.westgroup.novus.migratescheduler.MockStaticTest.test MockStatic (MockStaticTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) What version of the product are you using? On what operating system? powermock-easymock-junit-1.4.7.zip on windows xp Please provide any additional information below. I am trying ot use powermock to mock the static class, i wanted to take help from working example from MockStaticTest.

_Original issue: http://code.google.com/p/powermock/issues/detail?id=310_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on February 09, 2011 23:10:02_

This is usually a user error. "MockStaticTest" is executed on every PowerMock release so it should work. Please provide a running example if you think there's a problem.

Thanks

**Comment by johanhaleby** [comment]
_From [sesam...@googlemail.com](https://code.google.com/u/116293032946671853400/) on April 07, 2011 04:13:54_

I think that this issue is related to Issue 309
