### ISSUE TITLE
NoClassDefFoundError: org/powermock/modules/testng/PowerMockTestCase

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#347]
_From [ohayon....@gmail.com](https://code.google.com/u/108847503706916123657/) on May 08, 2011 15:24:36_

What steps will reproduce the problem? 1. 2. 3. What is the expected output? What do you see instead? System.out.println(p.getPublicName()); --> expected : kuku
System.out.println(p.getPrivateName()); --> expected : myPrivateName What version of the product are you using? On what operating system? 1.4.9 Please provide any additional information below. With the last version (1.4.8) i didn't have this exception.
 here is the exception that i got:
org.testng.TestNGException: 
An error occurred while instantiating class com.sample.PersonTester: org/powermock/modules/testng/PowerMockTestCase
 at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:342)
 at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:89)
 at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:107)
 at org.testng.internal.TestNGClassFinder.<init>(TestNGClassFinder.java:117)
 at org.testng.TestRunner.initMethods(TestRunner.java:394)
 at org.testng.TestRunner.init(TestRunner.java:228)
 at org.testng.TestRunner.init(TestRunner.java:198)
 at org.testng.TestRunner.<init>(TestRunner.java:154)
 at org.testng.remote.RemoteTestNG$1.newTestRunner(RemoteTestNG.java:129)
 at org.testng.remote.RemoteTestNG$DelegatingTestRunnerFactory.newTestRunner(RemoteTestNG.java:237)
 at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:540)
 at org.testng.SuiteRunner.init(SuiteRunner.java:140)
 at org.testng.SuiteRunner.<init>(SuiteRunner.java:104)
 at org.testng.TestNG.createSuiteRunner(TestNG.java:1039)
 at org.testng.TestNG.createSuiteRunners(TestNG.java:1025)
 at org.testng.TestNG.runSuitesLocally(TestNG.java:875)
 at org.testng.TestNG.run(TestNG.java:818)
 at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:96)
 at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:179)
Caused by: java.lang.NoClassDefFoundError: org/powermock/modules/testng/PowerMockTestCase
 at org.powermock.modules.testng.internal.PowerMockClassloaderObjectFactory.extendsPowerMockTestCase(PowerMockClassloaderObjectFactory.java:121)
 at org.powermock.modules.testng.internal.PowerMockClassloaderObjectFactory.createTestClass(PowerMockClassloaderObjectFactory.java:104)
 at org.powermock.modules.testng.internal.PowerMockClassloaderObjectFactory.newInstance(PowerMockClassloaderObjectFactory.java:76)
 at org.powermock.modules.testng.PowerMockObjectFactory.newInstance(PowerMockObjectFactory.java:42)
 at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:330)
 ... 18 more
Caused by: java.lang.ClassNotFoundException: org.powermock.modules.testng.PowerMockTestCase
 at java.net.URLClassLoader$1.run(URLClassLoader.java:200)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:303)
 at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
 at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:316)
 ... 23 more

**Attachment:** [PersonTester.java Person.java Man.java](http://code.google.com/p/powermock/issues/detail?id=327)

_Original issue: http://code.google.com/p/powermock/issues/detail?id=327_

**Comment by johanhaleby** [comment]
_From [ohayon....@gmail.com](https://code.google.com/u/108847503706916123657/) on May 08, 2011 06:31:54_

when i open the jar powermock-mockito-1.4.9.jar i didn't found PowerMockTestCase.class under the package org.powermock.modules.testng

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 08, 2011 23:35:00_

Hi, 

Yes this was an issue in the release project where this dependency was missing. Please have a look at https://code.google.com/p/powermock/wiki/TestNG_usage#Using_1.4.9_without_Maven to solve it. The next release will bundle the file. Thanks for pointing out.

**Status:** Fixed  
  **Labels:** -Priority-Medium Priority-High

**Comment by johanhaleby** [comment]
_From [jonas.po...@gmail.com](https://code.google.com/u/104042305078065689836/) on September 27, 2011 07:46:55_

Hello,

I'm sorry but I believe the problem still exists in 1.4.10.

I unzipped the .zip Download "powermock-mockito-1.4.10.zip" and had a look at the jar files:

$ jar tf powermock-mockito-1.4.10-full.jar | grep "TestCase"
org/powermock/tests/utils/impl/TestCaseEntry.class
org/powermock/tests/utils/impl/TestCaseEntry.java

Not too much to be found :/
