### ISSUE TITLE
Test initialization error (ClassNotFoundException)

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#353]
_From [mikemad...@gmail.com](https://code.google.com/u/109147311719244585825/) on June 17, 2011 20:15:27_

What steps will reproduce the problem? 1. Please see http://groups.google.com/group/powermock/browse_thread/thread/2ce5f86ad4a8f030/0653c54d8b59e4d9?#0653c54d8b59e4d9 2. Use his test classes or the provided Test.zip (same thing, just slightly modified).

What is the expected output?
All classes should get loaded either by the system class loader or the same class.getClassLoader()

What do you see instead?
System class loader cannot find classes and there is no other fall back mechanism. What version of the product are you using? On what operating system? 1. PowerMock 1.4.9 with Mockito API extension (including source but excluding dependencies) 
2. mockito-core-1.8.5
3. junit-4.8.2
4. Windows 7
4. Java 1.6 Please provide any additional information below. NOTE1: 
I was having the same issue as Mikael.  However I was running my test via a web container (an e-commerce platform with a built in junit apache test servlet).

NOTE2:
This is the root of the problem:

org.powermock.api.mockito.internal.mockcreation.MockCreator.MockitoStateCleaner.clearThreadLocalIn(Class<?> cls)...
final Class<?> clazz = ClassLoaderUtil.loadClass(cls, ClassLoader.getSystemClassLoader());

I have made the following modification to the class and it now works.  This may not be the final fix that the powermock developers might use, but its a step in the right direction.
 
private void clearThreadLocalIn(Class<?> cls) 
{
  Whitebox.getInternalState(cls, ThreadLocal.class).set(null);
  final Class<?> clazz;
  if(cls != null && cls.getClassLoader() != null) 
  {
    clazz = ClassLoaderUtil.loadClass(cls, cls.getClassLoader());
  }
  else
  {
    clazz = ClassLoaderUtil.loadClass(cls, ClassLoader.getSystemClassLoader());
  }
  Whitebox.getInternalState(clazz, ThreadLocal.class).set(null);
}

**Attachment:** [Test.zip](http://code.google.com/p/powermock/issues/detail?id=333)

_Original issue: http://code.google.com/p/powermock/issues/detail?id=333_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on June 18, 2011 03:20:41_

Thanks for investigating this and thanks for fixing it. I've modified the code a bit and committed it to trunk. Please help me verify whether it works or not.

**Status:** Accepted

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on August 21, 2011 14:35:39_

I consider this fixed since I haven't heard anything.

**Status:** Fixed

**Comment by johanhaleby** [comment]
_From [sjgadh...@gmail.com](https://code.google.com/u/107951590195199722702/) on August 25, 2011 10:22:33_

I'm getting similar problem, basically test written with powermock runs in eclipse but fails with ant

I'm using 
mockito-all-1.8.5 jar
javassist-3.14.0.-GA.jar
powermock-mockito-1.4.9.-full.jar (I also tried 1.4.10 version of this but getting the same problem)

I'm getting the below problem 

java.lang.ClassNotFoundException: org.mockito.internal.progress.ThreadSafeMockingProgress

java.lang.RuntimeException: java.lang.ClassNotFoundException: org.mockito.internal.progress.ThreadSafeMockingProgress
at org.powermock.api.support.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:52)
at org.powermock.api.support.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:26)
at org.powermock.api.mockito.internal.mockcreation.MockCreator$MockitoStateCleaner.clearThreadLocalIn(MockCreator.java:157)
at org.powermock.api.mockito.internal.mockcreation.MockCreator$MockitoStateCleaner.clearMockProgress(MockCreator.java:148)
at org.powermock.api.mockito.internal.mockcreation.MockCreator$MockitoStateCleaner.run(MockCreator.java:143)
at org.powermock.core.MockRepository.clear(MockRepository.java:121)
at org.powermock.reflect.internal.WhiteboxImpl.performMethodInvocation(WhiteboxImpl.java:2014)
at org.powermock.reflect.internal.WhiteboxImpl.doInvokeMethod(WhiteboxImpl.java:885)
at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:859)
at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:466)
at org.powermock.modules.junit4.common.internal.impl.PowerMockJUnit4RunListener.testFinished(PowerMockJUnit4RunListener.java:55)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:208)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:146)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:121)
at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:123)
at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:102)
at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
at net.sf.antcontrib.logic.For$Reflector.call(Unknown Source)
at net.sf.antcontrib.logic.For.doSequentialIteration(Unknown Source)
at net.sf.antcontrib.logic.For.doTheTasks(Unknown Source)
at net.sf.antcontrib.logic.For.execute(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.mockito.internal.progress.ThreadSafeMockingProgress
at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
at java.lang.ClassLoader.loadClass(ClassLoader.java:305)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
at java.lang.ClassLoader.loadClass(ClassLoader.java:246)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:247)
at org.powermock.api.support.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:50)
at org.powermock.api.support.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:26)
at org.powermock.api.mockito.internal.mockcreation.MockCreator$MockitoStateCleaner.clearThreadLocalIn(MockCreator.java:158)

Appreciate any help.

**Comment by johanhaleby** [comment]
_From [saiprane...@gmail.com](https://code.google.com/u/115121149439324076164/) on August 26, 2011 05:31:32_

I think the issue is still existing because when i came to know about power mock a couple of days back the latest version was 1.4.9 and it was working fine for me in the eclipse IDE for an individual test suit but facing the problem when running through the ant. And i posted the same problem in the new posts follow the link http://groups.google.com/group/powermock/browse_thread/thread/4c87a3e01fd72bca?hl=en After going through this issue i noticed it has been closed on Aug 21st and i downloaded the latest version 1.4.10 but still i am facing the same problem, Johan please look into this before closing this defect. I am working with this and will provide any updates if i am successful.

**Comment by johanhaleby** [comment]
_From [saiprane...@gmail.com](https://code.google.com/u/115121149439324076164/) on August 29, 2011 04:24:08_

I am sorry johan, the issue is not with power mock i am able to solve it, it is due to some other conflicts with the other jars in my app. 

This is working fine and this defect can be considered fixed.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on August 29, 2011 10:51:15_

Glad you sorted it out. Thanks for letting us know.

**Comment by johanhaleby** [comment]
_From [sjgadh...@gmail.com](https://code.google.com/u/107951590195199722702/) on August 29, 2011 20:33:30_

if you can please elaborate on conficting jar(s), that would be really helpful

**Comment by johanhaleby** [comment]
_From [sjgadh...@gmail.com](https://code.google.com/u/107951590195199722702/) on September 02, 2011 16:48:09_

Yes it worked with powermock1.4.10
