### ISSUE TITLE
Failed to transform class with name foo.TempTest Reason: 3 

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#369]
_From [zhaoshan...@gmail.com](https://code.google.com/u/117710579479258069090/) on October 12, 2011 17:44:01_

I'm getting a "Failed to transform class with name foo.TempTest Reason: 3" error when mocking a static method. 

My test is this:

@RunWith(PowerMockRunner.class)  
@PrepareForTest({Utils2.class})  
public class TempTest {

    @Test
    public void say() {
    }
}

And Utils2 class:

public class Utils2 {
	public static String say(String s) {
		return s;
	}
}

The stack trace when exception is thrown is:

java.lang.IllegalStateException: Failed to transform class with name com.crossfence.service.TempTest. Reason: 3
	...
Caused by: java.lang.ArrayIndexOutOfBoundsException: 3
	at javassist.bytecode.ByteArray.write16bit(ByteArray.java:40)
	at javassist.bytecode.StackMapTable$Shifter.update(StackMapTable.java:744)
	...
	at javassist.expr.FieldAccess.replace(FieldAccess.java:213)
	at org.powermock.core.transformers.impl.MainMockTransformer$PowerMockExpressionEditor.edit(MainMockTransformer.java:267)
	...
	at javassist.CtClassType.instrument(CtClassType.java:1288)
	at org.powermock.core.transformers.impl.MainMockTransformer.transform(MainMockTransformer.java:75)
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:203)
	... 29 more

I got the exception when adding this test to an existing project. However, it works fine if I create a new project with just these two classes. Therefore this could be an envrionement issue. 

I'm using these verions:
junit 4.8.2, easymock 3.0, powermock 1.4.10, and javassist 3.12.0.GA.

The operating system is Windows 7.

How do I troubleshoot this? Are there loggings I can turn on?

Let me know if you need more information.

Thanks!

_Original issue: http://code.google.com/p/powermock/issues/detail?id=349_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 12, 2011 23:57:58_

Hi, 

Try upgraded to Javassist 3.15 GA and see if it works

**Comment by johanhaleby** [comment]
_From [zhaoshan...@gmail.com](https://code.google.com/u/117710579479258069090/) on October 13, 2011 07:27:02_

Worked. Thanks! Actually Javassist 3.6 was used. 3.12 GA works as well.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 13, 2011 07:35:54_

It's important that you use the correct dependencies otherwise PowerMock won't work.

**Status:** Invalid
