### ISSUE TITLE
ClassFormatError

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#373]
_From [xinweic...@gmail.com](https://code.google.com/u/112461273252131239266/) on October 28, 2011 23:54:57_

I got ClassFormatError in my test using Powermock 1.4.10. The problem class is javax.security.auth.x500.X500Principal. I simplified the test code as:

@PrepareForTest(EncryptUsage.class)
@RunWith(PowerMockRunner.class)
public class TestEncryptedFileUtil {

	@Test
	public void constructorTest(){
		try{
			EncryptUsage efu = new EncryptUsage();
			assertTrue("EncryptedFileUtil instance not null", efu != null);
		}catch(Throwable t){
			t.printStackTrace();
			fail("Got error: " + t.getMessage());
		}
	}
}

public class EncryptUsage{
	
	public EncryptUsage() throws Exception{
		byte[] myCipher = "theCipher".getBytes();
		DESKeySpec sks = new DESKeySpec(myCipher);
		SecretKeyFactory skf = SecretKeyFactory.getInstance("DES");
		skf.generateSecret(sks);
	}
	
}

The error is:
java.lang.ClassFormatError
	at java.lang.ClassLoader.defineClass(ClassLoader.java:222)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:158)
	at org.powermock.core.classloader.MockClassLoader.loadUnmockedClass(MockClassLoader.java)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:152)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:561)
	at com.ibm.security.validator.SimpleValidator.engineValidate(Unknown Source)
	at com.ibm.security.validator.Validator.validate(Unknown Source)
	at com.ibm.security.validator.Validator.validate(Unknown Source)
	at javax.crypto.a.a(Unknown Source)
	at javax.crypto.a.a(Unknown Source)
	at javax.crypto.a.a(Unknown Source)
	at javax.crypto.a.a(Unknown Source)
	at javax.crypto.b.b(Unknown Source)
	at javax.crypto.b.a(Unknown Source)
	at javax.crypto.b.b(Unknown Source)
	at javax.crypto.b.a(Unknown Source)
	at javax.crypto.SecretKeyFactory.getInstance(Unknown Source)
	at powerMockTest.EncryptUsage.<init>(EncryptUsage.java:11)
	at powerMockTest.TestEncryptedFileUtil.constructorTest(TestEncryptedFileUtil.java:18)

What's wrong? Looking forward to your reply. Thank you in advance.

_Original issue: http://code.google.com/p/powermock/issues/detail?id=353_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 31, 2011 00:18:04_

Try to use @PowerMockIgnore("javax.security.auth.*")

**Comment by johanhaleby** [comment]
_From [xinweic...@gmail.com](https://code.google.com/u/112461273252131239266/) on October 31, 2011 16:21:19_

Thank you for the quick replying. But after adding @PowerMockIgnore, I got:
JUnit version 4.8.2
.java.security.NoSuchAlgorithmException: DES SecretKeyFactory not available
        at javax.crypto.SecretKeyFactory.<init>(DashoA13*..)
        at javax.crypto.SecretKeyFactory.getInstance(DashoA13*..)
        at powerMockTest.EncryptUsage.<init>(EncryptUsage.java:11)
        at powerMockTest.TestEncryptedFileUtil.constructorTest(TestEncryptedFileUtil.java:20)
...

**Comment by johanhaleby** [comment]
_From [xinweic...@gmail.com](https://code.google.com/u/112461273252131239266/) on November 03, 2011 10:29:00_

since I do test the encryption part, the defer loading of security package doesn't help here.

Knowing nothing about what's inside powermock, I still tried to debug its code until reach the calling to javaassit's (3.15-GA) CtClass.toBytecode for the class javax.security.auth.x500.X500Principal. The following ClassLoader.defineClass failed with ClassFormatError, and actually before that, calling CtClass.toClass failed with the same error. The byte[] are correct, and the separate test of javaassit's CtClass has no problem.

Then I stopped. Johan, please help take a look. Thank you very much.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 03, 2011 12:59:46_

I appreciate your help in trying to figure things out, I know it's not always easy. Unfortunately I don't have the time needed to investigate such complex things. I'm maintaining PowerMock totally in my spare time and it takes a great amount time as it is. Sorry :/

**Comment by johanhaleby** [comment]
_From [com...@gmail.com](https://code.google.com/u/108751971092104151333/) on September 26, 2012 14:50:45_

I had the same issue with PomerMockRunner and the same error:
XYZ SecretKeyFactory not available

adding

@PowerMockIgnore( {..... , "javax.crypto.*" })

solved the issue for me, and the SecretKeyFactory.getInstance() starting working for me.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 26, 2012 23:08:42_

Thanks for sharing
