### ISSUE TITLE
Suppression not working for overridden Methods

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#384]
_From [gloeckne...@gmail.com](https://code.google.com/u/116867748864641808723/) on January 25, 2012 13:11:48_

Suppression doesn't work if the method that should be suppressed is overridden. 

Example class structure:
class A {

  public void dontCallMe(Object someParameter) {...}
    ...
  }
}

public final class B extends A {
  @Override
  public void dontCallMe(Object someParameter) {...}
    ...
  }  
}

I try suppressing dontCallMe using "suppress(method(B.class, "someMethod", Object.class))". This results in the following exception given below.

Workaround: suppress all methods with the same signature ("suppress(method(B.class, Object.class));"). 

Several matching methods found, please specify the argument parameter types so that PowerMock can determine which method you're referring to.
Matching methods in class B were:
void dontCallMe( java.lang.Object.class )
void dontCallMe( java.lang.Object.class )

	at org.powermock.reflect.internal.WhiteboxImpl.throwExceptionWhenMultipleMethodMatchesFound(WhiteboxImpl.java:1821)
	at org.powermock.reflect.internal.WhiteboxImpl.findMethod(WhiteboxImpl.java:1749)
	at org.powermock.api.support.membermodification.MemberMatcher.method(MemberMatcher.java:81)
	at MockTest.hello(MockTest.java:45)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:312)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:296)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:284)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:209)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:148)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:122)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:120)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:102)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:42)

Maven dependencies:
\<dependency>
			\<groupId>org.mockito</groupId>
			\<artifactId>mockito-core</artifactId>
			\<version>1.9.0</version>
			\<scope>test</scope>
		\</dependency>
		\<dependency>
			\<groupId>org.powermock</groupId>
			\<artifactId>powermock-module-junit4</artifactId>
			\<version>1.4.11</version>
			\<scope>test</scope>
		\</dependency>
		\<dependency>
			\<groupId>org.powermock</groupId>
			\<artifactId>powermock-api-mockito</artifactId>
			\<version>1.4.11</version>
			\<scope>test</scope>
		\</dependency>

_Original issue: http://code.google.com/p/powermock/issues/detail?id=364_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 31, 2012 00:02:53_

Looks like a bug! Thanks for reporting. It would be really cool if you could help out with a patch.

**Status:** Accepted

**Comment by johanhaleby** [comment]
_From [hpb...@gmail.com](https://code.google.com/u/103254250676298271970/) on July 25, 2012 02:38:50_

I've uploaded a patch for issue #51 that solves this issue.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 25, 2012 04:23:44_

**Status:** Duplicate  
  **Mergedinto:** 51

**Comment by adaher** [comment]
Still stuck with this problem using the latest version of powermockito (1.6.2), any plan to release a new version soon ?
@johanhaleby 
Thank you!

**Comment by johanhaleby** [comment]
Could you help out and convert the patch to a pull request?! That would make it much easier for me.

**Comment by jenimi** [comment]
I still experience this problem with PowerMock 1.6.6 
"Problem with PowerMocking overridden methods (createToDoItemView). See: https://github.com/jayway/powermock/issues/384"
I was not able to find the patch attached to #51, in #51 it says it works with EasyMock, but I get similar Error in EasyMock (Multiple definitions of the method found)
Is there a way I can fix this problem, as this is a real stopper for my tests.
