### ISSUE TITLE
Test case with expectedExceptions fails when using PowerMock with TestNG.

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#386]
_From [archanar...@gmail.com](https://code.google.com/u/108412640355375632241/) on February 02, 2012 20:37:36_

What steps will reproduce the problem? 1. Create a Test class which has the below method 
@ObjectFactory
	public IObjectFactory getObjectFactory() {
		return new org.powermock.modules.testng.PowerMockObjectFactory();
	}
2. Create a test case with expectedExceptions annotation 
3. Run it using Eclipse TestNG plugin. What is the expected output? What do you see instead? We are expecting the test case to pass but test case fails and gives the below message . 
Expected exception com.org.test.DAOException but got org.testng.TestException: 
Expected exception com.org.test.DAOException but got com.org.test.DAOException: com.org.test.DAOException
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1459)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1222) What version of the product are you using? On what operating system? TestiNG 6.3.1
Power mock 1.4.11.
Eclipse Plugin for TestNG.
Windows XP. Please provide any additional information below. The same test case passes with TestNG when we don't use power mock. 

After debugging through the TestNG code, noticed that below line (#  1794) in isExpectedException method 
inside the testng/src/main/java/org/testng/internal/Invoker.java fails.

exception.isAssignableFrom(realExceptionClass):  this statement always returns false even if the exception and realExpectionClass are same.

_Original issue: http://code.google.com/p/powermock/issues/detail?id=366_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on February 03, 2012 01:09:10_

Hi, 

Could you debug and see which classloader loaded the "exception" and which classloader that loads the "realExceptionClass". Is it the same classloader instance?

**Comment by johanhaleby** [comment]
_From [archanar...@gmail.com](https://code.google.com/u/108412640355375632241/) on February 03, 2012 10:49:37_

I noticed that classloaders are different.

exception is loaded by sun.misc.Launcher$AppClassLoader@1ba34f2

realExceptionClass is loaded by org.powermock.core.classloader.MockClassLoader@121b59a

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on February 07, 2012 02:31:29_

Ok that's what I suspected. Thanks for reporting. As a work-around try to ignore the exception using @PowerMockIgnore and see if that helps.

**Status:** Accepted

**Comment by johanhaleby** [comment]
_From [archanar...@gmail.com](https://code.google.com/u/108412640355375632241/) on February 28, 2012 06:11:53_

@PowerMockIgnore is not ignoring the exception. This does not help me in passing the test case.

**Comment by johanhaleby** [comment]
_From [bugt...@gmail.com](https://code.google.com/u/115783665483512068432/) on August 22, 2012 08:17:42_

Any thoughts on how we could work around this?

**Comment by johanhaleby** [comment]
_From [Thomas.M...@gmail.com](https://code.google.com/u/111355646200670716725/) on October 14, 2012 01:32:32_

Same problem using:
testng-6.8.jar
powermock-mockito-1.4.12-full.jar

**Comment by johanhaleby** [comment]
_From [Thomas.M...@gmail.com](https://code.google.com/u/111355646200670716725/) on October 14, 2012 02:39:40_

and here is some example code https://gist.github.com/a3f464eb614a4a104482 And to be more concrete:
Exceptions from the jdk (and other external libs?) will correct catched but own exceptions will not.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 14, 2012 05:49:53_

You can try extending from PowerMockTestCase and see if that works any better.

**Comment by johanhaleby** [comment]
_From [majorpe...@gmail.com](https://code.google.com/u/104150745622850954138/) on October 14, 2012 06:33:57_

Did not help in my case.

**Comment by johanhaleby** [comment]
_From [Thomas.M...@gmail.com](https://code.google.com/u/111355646200670716725/) on October 16, 2012 08:37:10_

Did not change any thing in my case.
 
Also adding object-factory="org.powermock.modules.testng.PowerMockObjectFactory" to testNG suite.xml did not help.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 16, 2012 09:09:20_

Alright, thanks for trying out. I'd really appreciate if anyone could investigate a bit more in detail why this happens (and preferably create a patch as well :)).

**Comment by johanhaleby** [comment]
_From [kishore....@gmail.com](https://code.google.com/u/107063927838296543226/) on January 20, 2013 20:07:29_

The workaround I've been using for couple of more powermock tests. Have two test classes one with powermock and one without powermock. This allows me to avoid powemock issues temporarily.
e.g.
MyBeanTest.java
MyBeanStaticTest.java

**Comment by johanhaleby** [comment]
_From [mikaelpe...@gmail.com](https://code.google.com/u/108670665138738751682/) on December 20, 2013 07:15:17_

Can anyone tell how I, in Eclipse ( or any other 3rd party tool), can see which classloader is used for each class?

//mike

**Comment by johanhaleby** [comment]
_From [majorpe...@gmail.com](https://code.google.com/u/104150745622850954138/) on December 21, 2013 12:30:11_

Since there was absolutely no progress on this quite gamebreaking issue for almost two years now, here's a patch I just came up with after a days worth of investigation... Feel free to use it at your own risk..

**Attachment:** [powermock.diff](http://code.google.com/p/powermock/issues/detail?id=366#hc14)

**Comment by johanhaleby** [comment]
_From [bugt...@gmail.com](https://code.google.com/u/115783665483512068432/) on December 21, 2013 12:53:10_

Hahahahah THANK YOU!

**Comment by johanhaleby** [comment]
_From [mikaelpe...@gmail.com](https://code.google.com/u/108670665138738751682/) on December 22, 2013 22:52:05_

Looks good to me so I will try to verify it.

//mike

**Comment by johanhaleby** [comment]
_From [mikaelpe...@gmail.com](https://code.google.com/u/108670665138738751682/) on December 23, 2013 01:28:11_

I am trying to build 1.5.3-SNAPSHOT with this fix but I get the following error:

ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project powermock-api-mockito: Compilation failure
[ERROR] /mypath_to_home/powermock/api/mockito/src/main/java/org/powermock/api/mockito/internal/expectation/DelegatingToConstructorsOngoingStubbing.java:[115,31] type parameters of \<M>M cannot be determined; no unique maximal instance exists for type variable M with upper bounds M,java.lang.Object
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException Any ideas how I can fix it?

//mike

**Comment by johanhaleby** [comment]
_From [majorpe...@gmail.com](https://code.google.com/u/104150745622850954138/) on December 23, 2013 01:58:54_

This sounds like: http://stackoverflow.com/questions/314572/bug-in-eclipse-compiler-or-in-javac-type-parameters-of-t-cannot-be-determined FWIW building trunk with JDK7 indeed works. My patch was created against the 1.5.2 tag by the way.

**Comment by johanhaleby** [comment]
_From [mikaelpe...@gmail.com](https://code.google.com/u/108670665138738751682/) on December 23, 2013 05:44:33_

I am running 1.5.3-SNAPSHOT since I guess that is where it will be added or?Swithing to 1.7 helped to get by the error metioned but I got stuck with:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-5:attached (make-assembly) on project powermock-release-junit-without-mock-framework: Failed to create assembly: Error adding file-set for 'org.powermock:powermock-release-without-test-and-mock-framework:jar:1.5.3-SNAPSHOT' to archive: Expected org.codehaus.plexus.components.io.resources.PlexusIoArchivedResourceCollection, got org.codehaus.plexus.components.io.resources.PlexusIoFileResourceCollection -> [Help 1]

I need it packed to be able to test in my test project ( maven project).

Any more ideas?
//mike

**Comment by johanhaleby** [comment]
_From [mikaelpe...@gmail.com](https://code.google.com/u/108670665138738751682/) on December 23, 2013 06:48:04_

Don't seem to have the power to run it ....
ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project powermock-classloading-objenesis: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]

I used:

set MAVEN_OPTS=-Xmx2048m

//mike

Ps. you don't happen to have a prefixed jar file of powermock that I can test against?

**Comment by johanhaleby** [comment]
_From [majorpe...@gmail.com](https://code.google.com/u/104150745622850954138/) on December 23, 2013 07:05:33_

Here's a build I just made - first my build failed with a VM crash at objenesis, but afterwards the build succeeded with:
mvn clean install -rf :powermock-junit4-rule-objenesis-test
I've used MAVEN_OPTS="-Xmx1g -XX:MaxPermSize=256m". https://www.dropbox.com/s/x27b20jbp9npw0v/powermock-mockito-testng-1.5.3-SNAPSHOT.zip

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on December 25, 2013 07:05:34_

I've applied the patch to trunk now, thanks!

To build PowerMock you must use JDK 6 otherwise you'll likely run into VM crashes.

**Status:** Fixed

**Comment by johanhaleby** [comment]
_From [mikaelpe...@gmail.com](https://code.google.com/u/108670665138738751682/) on January 02, 2014 00:12:45_

When will there be a new delivery of powermock?

//mike

**Comment by johanhaleby** [comment]
_From [mikaelpe...@gmail.com](https://code.google.com/u/108670665138738751682/) on January 07, 2014 01:41:21_

Any idea how I can make a beta release ( to use in our team) of power-mock to see if we have all that we need?

//mike

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 07, 2014 04:06:20_

Well you could build it yourself from trunk using Java 6 (and skip javadoc generation) and then use it. Making a release of PowerMock takes me several hours so it's not something I enjoy doing. I'm thinking about making a new release soon so that you'll get this fix but I would _really_ like someone to try it out first so I don't have to make a new release again. This is how I (quickly) build PowerMock on my Mac:

JAVA_HOME="/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home" mvn clean install -Dmaven.javadoc.skip=true

**Comment by johanhaleby** [comment]
_From [mikaelpe...@gmail.com](https://code.google.com/u/108670665138738751682/) on January 09, 2014 04:25:38_

I used jdk1.6 and got the following test to fail:

INFO] powermock-junit4-rule-xstream-test ................ FAILURE [5.155s]

Failed tests:   testSupressStaticInitializer(org.powermock.modules.test.junit4.rule.xstream.StaticInitializerExampleTest): Should be null because the static initializer should be suppressed

Is this known? 

I added a @RunWith(PowerMockRunner.class) and it seems to pass. Is it ok?

//mike

//mike

**Comment by johanhaleby** [comment]
_From [mikaelpe...@gmail.com](https://code.google.com/u/108670665138738751682/) on January 09, 2014 06:04:41_

Got the same for:

Failed tests:   testSupressStaticInitializer(org.powermock.modules.test.junit4.rule.objenesis.StaticInitializerExampleTest): Should be null because the static initializer should be suppressed

I tried @RunWith(PowerMockRunner.class) but then compiler says:

src/test/java/org/powermock/modules/test/junit4/rule/objenesis/StaticInitializerExampleTest.java:[16,1] error: cannot find symbol

I will try to run it from command line. What version of maven are you using?

//mike

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 09, 2014 10:00:01_

I'm using Maven 3.1 on MacOSX. Try disabling the test if it doesn't work (although it should work).

**Comment by johanhaleby** [comment]
_From [mikaelpe...@gmail.com](https://code.google.com/u/108670665138738751682/) on January 09, 2014 23:49:13_

Yes selected a newer version of jdk1.6 ( 1.6.0_45) and used ( on SuSE linux 64 bit):

env MAVEN_OPTS="-Xmx1g -XX:MaxPermSize=256m" mvn clean install -Dmaven.javadoc.skip=true

And it worked nice.

//mike

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 10, 2014 00:38:48_

Great! Then I'll release a new version right away. It'll hopefully be available within a few hours.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 10, 2014 01:38:45_

It's now released in Maven. I'll update the documentation and upload the binaries etc later.
