### ISSUE TITLE
java.lang.IllegalStateException: Failed to transform class Reason: PowerMock internal error when modifying method.

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#392]
_From [petrkn...@gmail.com](https://code.google.com/u/104862038159999963299/) on February 21, 2012 21:31:58_

What steps will reproduce the problem? I am using the following code:
1) Class Debugger for which I would like to mock static void methods

package uk.ac.open.util;

public class Debugger {

   public static void debug(){System.err.println();}

}

2) My Test class
package uk.ac.open.util;

import junit.framework.Assert;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.junit.runner.RunWith;
//import org.junit.runner.RunWith;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;
//import static org.powermock.api.easymock.PowerMock.*;

import static org.powermock.api.mockito.PowerMockito.*;
import org.powermock.api.mockito.PowerMockito;

@RunWith( PowerMockRunner.class )
@PrepareForTest( Debugger.class )
public class DebuggerTest {
    
    public DebuggerTest() {
    }

    @BeforeClass
    public static void setUpClass() throws Exception {
    }

    @AfterClass
    public static void tearDownClass() throws Exception {
    }
    
    @Before
    public void setUp() {
    }
    
    @After
    public void tearDown() {
    }

    @Test
    public void testDebug() {
        mockStatic( Debugger.class );        
        spy(Debugger.class);
        
        doNothing().when(Debugger.class);
        //PowerMockito.suppress(Debugger.class.getMethods());
        Debugger.debug();

        boolean what = false;
        Assert.assertEquals(true, true);

    }
}

3) I am using the following jar files powermock-mockito-junit-1.4.11.zip downloaded today from here: https://code.google.com/p/powermock/downloads/detail?name=powermock-mockito-junit-1.4.11.zip&can=2&q= What is the expected output? What do you see instead? I woud expect the test to be successful. Instead the test ends with: 

Testsuite: uk.ac.open.util.DebuggerTest
Tests run: 1, Failures: 0, Errors: 1, Time elapsed: 0.18 sec

Testcase: initializationError(uk.ac.open.util.DebuggerTest):	Caused an ERROR
Failed to transform class with name uk.ac.open.util.DebuggerTest. Reason: PowerMock internal error when modifying method.
java.lang.IllegalStateException: Failed to transform class with name uk.ac.open.util.DebuggerTest. Reason: PowerMock internal error when modifying method.
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:207)
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:207)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:145)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:247)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:133)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:39)
	at org.powermock.tests.utils.impl.AbstractTestSuiteChunkerImpl.createTestDelegators(AbstractTestSuiteChunkerImpl.java:217)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.<init>(JUnit4TestSuiteChunkerImpl.java:59)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.<init>(AbstractCommonPowerMockRunner.java:32)
	at org.powermock.modules.junit4.PowerMockRunner.<init>(PowerMockRunner.java:31)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
Caused by: java.lang.RuntimeException: PowerMock internal error when modifying method.
	at org.powermock.core.transformers.impl.MainMockTransformer$PowerMockExpressionEditor.edit(MainMockTransformer.java:304)
	at javassist.expr.ExprEditor.loopBody(ExprEditor.java:191)
	at javassist.expr.ExprEditor.doit(ExprEditor.java:90)
	at javassist.CtClassType.instrument(CtClassType.java:1289)
	at org.powermock.core.transformers.impl.MainMockTransformer.transform(MainMockTransformer.java:75)
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:203)
Caused by: javassist.NotFoundException: debug(..) is not found in uk.ac.open.util.Debugger
	at javassist.CtClassType.getMethod(CtClassType.java:1042)
	at javassist.expr.MethodCall.getMethod(MethodCall.java:114)
	at org.powermock.core.transformers.impl.MainMockTransformer$PowerMockExpressionEditor.edit(MainMockTransformer.java:283)

Test uk.ac.open.util.DebuggerTest FAILED What version of the product are you using? On what operating system? I am testing on Mac, JDK 1.6.0 . Probably not important, but in Netbeans. Please provide any additional information below. I am a newbie to Powermock (so perhaps I am doing something stupid), but I was not able to find any solution to this problem anywhere. Seems to me the problem might be javaassist. I tried with different versions, but no result.

Many thanks,

Peter

_Original issue: http://code.google.com/p/powermock/issues/detail?id=372_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on February 22, 2012 01:36:40_

Can you provide an example test and code under test?

**Comment by johanhaleby** [comment]
_From [petrkn...@gmail.com](https://code.google.com/u/104862038159999963299/) on February 22, 2012 02:00:07_

I will, give me a couple of minutes to create a minimal project.

**Comment by johanhaleby** [comment]
_From [anandara...@gmail.com](https://code.google.com/u/104497460819964446700/) on February 27, 2012 13:41:37_

I did get the same issue. But after digging further we got figured it out. It is actually one of the interface change which caused the issue. Possibly you can look into sterotyped collection objects

**Comment by johanhaleby** [comment]
_From [bog...@gmail.com](https://code.google.com/u/110389857107993776756/) on May 23, 2012 10:18:19_

So what is the solution to this problem.  Is this an issue with PowerMock or is their something wrong with the code.  I'm facing this same issue and wondering what the solution is.  Thanks.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 23, 2012 22:04:56_

**Status:** Accepted

**Comment by johanhaleby** [comment]
_From [oghe...@gmail.com](https://code.google.com/u/109630558641088065189/) on June 28, 2012 06:49:16_

Did anybody find a solution to this? I'm experiencing the same issue when I try to run my tests from within Intellij IDEA 11.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on June 28, 2012 23:34:21_

Hmm if you remove @beforeclass and @afterclass does it make any difference?

**Comment by johanhaleby** [comment]
_From [oghe...@gmail.com](https://code.google.com/u/109630558641088065189/) on June 29, 2012 08:33:49_

I'm not using @BeforeClass or @AfterClass. I am however using inheritance in both the tests and the classes under test (the inheritance is mirrored across the source trees) with two @Override'd methods.

Do you think that may be causing the problem?

**Comment by johanhaleby** [comment]
_From [srohith85](https://code.google.com/u/srohith85/) on July 27, 2012 09:04:27_

I am using Intellij 10.5.4 and i dont get this issue. However, when i run it at the command line using Ant, this problem occurs.

**Comment by johanhaleby** [comment]
_From [santmatt...@gmail.com](https://code.google.com/u/102969152592546711028/) on August 01, 2012 14:58:24_

Maybe this helps. I had the same problem and I managed to solve it by not using static imports. In my case the issue was with PowerMockito static imports for 'mockStatic' and 'when' which I replace with direct calls as 'PowerMockito.mockStatic' and 'PowerMockito.when'.

**Comment by johanhaleby** [comment]
_From [mcherm](https://code.google.com/u/mcherm/) on September 26, 2012 06:55:48_

For what it's worth, I have what appears that it may be the same problem. I encounter the problem when running at the command line using Maven, but only when running the WHOLE test suite, not when running a single test. I am not using @beforeClass or @afterClass. Others building it (like our build server) do not encounter the same problem. I tried removing static imports and that didn't fix it. I'd love to follow up by saying what DID fix it, but I haven't been able to solve the problem.

**Comment by johanhaleby** [comment]
_From [vivek.na...@gmail.com](https://code.google.com/u/116066964476537247026/) on November 27, 2012 16:44:19_

Was a solution found for this problem?

**Comment by johanhaleby** [comment]
_From [vivek.na...@gmail.com](https://code.google.com/u/116066964476537247026/) on December 06, 2012 09:14:54_

I found the solution to my issue. I was using a different version of a jar in my build path. After cleaning the Maven repository, this error just disappeared. Hope this helps.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on December 06, 2012 11:22:47_

Thanks for sharing.

**Comment by johanhaleby** [comment]
_From [mpeters...@gmail.com](https://code.google.com/u/105169223487449689404/) on December 14, 2012 10:55:43_

I am getting this error when a colleague of mine using the same code is not.  I've looked through this list and 4 or 5 other proposed fixes.  It seems that a different thing fixes it for someone else, none of which worked for me.  I am starting to conclude that Powermock with javassist is not stable enough to be used.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on December 15, 2012 01:06:48_

Usually this turn out to be a classpath issue and PowerMock can do nothing about this. Are you using Maven? Even if you are you can run into nasty classpath issues that are not always easy to resolve if you're using frameworks that depend on different versions of the same jar files.

**Comment by johanhaleby** [comment]
_From [kareemel...@v-cumulus.com](https://code.google.com/u/104420569182627009373/) on November 21, 2013 06:08:06_

mvn clean install solved the problem for me

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 21, 2013 06:12:32_

Thanks for sharing.

**Comment by johanhaleby** [comment]
_From [umasanka...@gmail.com](https://code.google.com/u/118003982703517816564/) on July 17, 2014 03:30:45_

Is there any solution for this problem. I am also getting same problem?
initializationError (pakcage name): Failed to transform class with name XXXXX. Reason: javassist.bytecode.StringInfo cannot be cast to javassist.bytecode.MethodrefInfo

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 17, 2014 09:58:56_

What's the stacktrace?

**Comment by johanhaleby** [comment]
_From [umasanka...@gmail.com](https://code.google.com/u/117431268988559685850/) on July 18, 2014 03:55:02_

\<testcase time="0.001" classname=XXXTest" name="initializationError">
    \<error message="Failed to transform class with name YY. Reason: javassist.bytecode.StringInfo cannot be cast to javassist.bytecode.MethodrefInfo" type="java.lang.IllegalStateException">java.lang.IllegalStateException: Failed to transform class with name YY. Reason: javassist.bytecode.StringInfo cannot be cast to javassist.bytecode.MethodrefInfo
                at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:219)
                at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:147)
                at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:67)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
                at java.lang.Class.getDeclaredMethods0(Native Method)
                at java.lang.Class.privateGetDeclaredMethods(Class.java:2521)
                at java.lang.Class.privateGetPublicMethods(Class.java:2641)
                at java.lang.Class.getMethods(Class.java:1457)
                at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.getTestMethods(PowerMockJUnit44RunnerDelegateImpl.java:95)
                at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.&lt;init&gt;(PowerMockJUnit44RunnerDelegateImpl.java:71)
                at org.powermock.modules.junit4.internal.impl.PowerMockJUnit49RunnerDelegateImpl.&lt;init&gt;(PowerMockJUnit49RunnerDelegateImpl.java:29)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
                at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:143)
                at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:39)
                at org.powermock.tests.utils.impl.AbstractTestSuiteChunkerImpl.createTestDelegators(AbstractTestSuiteChunkerImpl.java:217)
                at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.&lt;init&gt;(JUnit4TestSuiteChunkerImpl.java:59)
                at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.&lt;init&gt;(AbstractCommonPowerMockRunner.java:32)
                at org.powermock.modules.junit4.PowerMockRunner.&lt;init&gt;(PowerMockRunner.java:33)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
                at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
                at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
                at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
                at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:29)
                at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:21)
                at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
                at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
                at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
                at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:26)
                at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:51)
                at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:119)
                at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:101)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:606)
                at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
                at com.sun.proxy.$Proxy0.invoke(Unknown Source)
                at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
                at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
                at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)
Caused by: java.lang.ClassCastException: javassist.bytecode.StringInfo cannot be cast to javassist.bytecode.MethodrefInfo
                at javassist.bytecode.ConstPool.getMethodrefType(ConstPool.java:383)
                at javassist.bytecode.stackmap.Tracer.doInvokeMethod(Tracer.java:812)
                at javassist.bytecode.stackmap.Tracer.doOpcode148_201(Tracer.java:617)
                at javassist.bytecode.stackmap.Tracer.doOpcode(Tracer.java:101)
                at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:161)
                at javassist.bytecode.stackmap.MapMaker.traceException(MapMaker.java:192)
                at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:154)
                at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:171)
                at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:171)
                at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:171)
                at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:120)
                at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:96)
                at javassist.bytecode.MethodInfo.rebuildStackMap(MethodInfo.java:404)
                at javassist.bytecode.MethodInfo.rebuildStackMapIf6(MethodInfo.java:389)
                at javassist.expr.ExprEditor.doit(ExprEditor.java:112)
                at javassist.CtClassType.instrument(CtClassType.java:1289)
                at org.powermock.core.transformers.impl.MainMockTransformer.transform(MainMockTransformer.java:75)
                at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:215)
                ... 42 more

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 18, 2014 04:48:44_

Hm are you using the latest version of PowerMock? When I check at line 75 in MainMockTransfomer all I see is a "}"

**Comment by johanhaleby** [comment]
_From [umasanka...@gmail.com](https://code.google.com/u/117431268988559685850/) on July 18, 2014 20:24:03_

I am using 1.5, below are the entries in pom.xml
\<dependency>
                \<groupId>org.powermock</groupId>
                \<artifactId>powermock-module-junit4</artifactId>
                \<version>1.5</version>
            \</dependency>
            \<dependency>
                \<groupId>org.powermock</groupId>
                \<artifactId>powermock-module-junit4-rule</artifactId>
                \<version>1.5</version>
            \</dependency>
            \<dependency>
                \<groupId>org.powermock</groupId>
                \<artifactId>powermock-classloading-xstream</artifactId>
                \<version>1.5</version>
            \</dependency>

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 18, 2014 23:12:22_

Try upgrading to version 1.5.5 and see if the problem still exist. If it does show me the stacktrace.

**Comment by johanhaleby** [comment]
_From [umasanka...@gmail.com](https://code.google.com/u/117431268988559685850/) on July 20, 2014 22:28:53_

No Luck..errors again upgrading to 1.5.5

java.lang.IllegalStateException: Failed to transform class with name XXX. Reason: bad LDC: 10
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:247)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:177)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2521)
	at java.lang.Class.privateGetPublicMethods(Class.java:2641)
	at java.lang.Class.getMethods(Class.java:1457)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.getTestMethods(PowerMockJUnit44RunnerDelegateImpl.java:93)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.<init>(PowerMockJUnit44RunnerDelegateImpl.java:69)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl.<init>(PowerMockJUnit47RunnerDelegateImpl.java:42)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit49RunnerDelegateImpl.<init>(PowerMockJUnit49RunnerDelegateImpl.java:25)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:149)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:39)
	at org.powermock.tests.utils.impl.AbstractTestSuiteChunkerImpl.createTestDelegators(AbstractTestSuiteChunkerImpl.java:218)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.<init>(JUnit4TestSuiteChunkerImpl.java:59)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.<init>(AbstractCommonPowerMockRunner.java:32)
	at org.powermock.modules.junit4.PowerMockRunner.<init>(PowerMockRunner.java:33)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:29)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:21)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:26)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:51)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:119)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.booter.ProviderFactory$ClassLoaderProxy.invoke(ProviderFactory.java:103)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:150)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcess(SurefireStarter.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:69)
Caused by: java.lang.RuntimeException: bad LDC: 10
	at javassist.bytecode.stackmap.Tracer.doLDC(Tracer.java:289)
	at javassist.bytecode.stackmap.Tracer.doOpcode0_53(Tracer.java:189)
	at javassist.bytecode.stackmap.Tracer.doOpcode(Tracer.java:94)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:161)
	at javassist.bytecode.stackmap.MapMaker.traceException(MapMaker.java:192)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:154)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:171)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:171)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:171)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:120)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:96)
	at javassist.bytecode.MethodInfo.rebuildStackMap(MethodInfo.java:404)
	at javassist.bytecode.MethodInfo.rebuildStackMapIf6(MethodInfo.java:389)
	at javassist.expr.ExprEditor.doit(ExprEditor.java:112)
	at javassist.CtClassType.instrument(CtClassType.java:1289)
	at org.powermock.core.transformers.impl.MainMockTransformer.transform(MainMockTransformer.java:74)
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:243)
	... 43 more

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 22, 2014 23:53:10_

Unfortunately I suspect that this is an issue with Javassist (the byte-code manipulation framework that PowerMock uses). It would be great if you could file an issue at Javassist with as much information as possible.

**Comment by IgorGanapolsky** [comment]
I am having the same error in Android Studio 3.2:
> com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : java.lang.IllegalStateException
reason: source error  is missing
