### ISSUE TITLE
PowerMock fails with InitializerException if ant version 1.8.2+ is used.

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#415]
_From [praya...@gmail.com](https://code.google.com/u/101528234671130470362/) on June 19, 2012 10:46:13_

What steps will reproduce the problem? 1. Use Ant version 1.8.2+
2. Use ant-junit target to run tests. 
3. All testcases that uses @PrepareTest ( tests final or static classes) fail with InitializerException - Cannot subclass final class. What is the expected output? What do you see instead? With Ant1.7.2 all test passes , when I use Ant 1.8.2+ tests fails with above error. What version of the product are you using? On what operating system? Powermock version 1.4.10

_Original issue: http://code.google.com/p/powermock/issues/detail?id=395_

**Comment by johanhaleby** [comment]
_From [praya...@gmail.com](https://code.google.com/u/101528234671130470362/) on June 19, 2012 02:00:24_

I get the error even if I use the latest binaries of Powermock and associated dependencies. I am attaching the error stack

java.lang.IllegalArgumentException: Cannot subclass final class class ...SessionManagerHelper at net.sf.cglib.proxy.Enhancer.generateClass(Enhancer.java:446) at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25) at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216) at net.sf.cglib.proxy.Enhancer.createHelper(Enhancer.java:377) at net.sf.cglib.proxy.Enhancer.createClass(Enhancer.java:317) at org.easymock.internal.ClassProxyFactory.createProxy(ClassProxyFactory.java:181) at org.easymock.internal.MocksControl.createMock(MocksControl.java:60) at org.powermock.api.easymock.PowerMock.doCreateMock(PowerMock.java:2212) at org.powermock.api.easymock.PowerMock.doMock(PowerMock.java:2163) at org.powermock.api.easymock.PowerMock.mockStatic(PowerMock.java:287) at ...ApplicationStateHelperTest.setUp(Unknown Source)

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 13, 2012 00:05:23_

Perhaps there's a JUnit conflict in the classpath?

**Comment by johanhaleby** [comment]
_From [bharath...@gmail.com](https://code.google.com/u/107323798782052521170/) on July 27, 2012 05:24:25_

Please use Powermock to resolve this issue.

For ex: if u are trying to mock URL (java.net.URL) class using easymock it will throw the above mentioned exception. Use Powermock instead of easymock.

URL url = EasyMock .createMock(URL.class) --> Will throw exception
URL url = PowerMock.createMock(URL.class) --> Works fine (But do not forget to add the class in @PrepareForTest).

**Comment by johanhaleby** [comment]
_From [ashishdu...@gmail.com](https://code.google.com/u/104011400446617746303/) on September 18, 2012 08:35:44_

I am facing the same problem with Ant 1.8.2+. In eclipse and Ant 1.7.1 every thing is working fine but not working in Ant 1.8.2 and above. I also tried PowerMock.createMock instead Mockito.createMock and @PrepareForTest on class level but no luck.

PowerMockito.mockStatic(StringUtils.class);
PowerMockito.when(StringUtils.getTerm("abcd")).thenReturn("xyz");

**Comment by johanhaleby** [comment]
_From [Benedett...@gmail.com](https://code.google.com/u/106247029640344817659/) on January 15, 2014 03:30:37_

Ehi guys ? Have you solved ?
I'm getting a lot of problem with Ant and @PrepareTest !

**Comment by johanhaleby** [comment]
_From [leonardo...@gmail.com](https://code.google.com/u/101778138962000057661/) on August 19, 2014 02:10:21_

Is your test case class extending from TestCase? 
Note that if you are using a mixed Junit3/4 style test then Ant will prioritise v3 over v4 and fail to invoke the PowerMock runner.
I had a very similar problem and sorted it out by converting the test case class  to annotations only.
Please see here for a related example that might help you: http://stackoverflow.com/questions/7796295/running-junit-through-ant-does-not-seem-to-use-custom-class-runner
