### ISSUE TITLE
PowerMock does not ignore JUnit Tests with assumeTrue(false)

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#428]
_From [funk.up...@gmail.com](https://code.google.com/u/112033284949043984133/) on November 13, 2012 12:39:45_

What steps will reproduce the problem? 1. create the following class

@RunWith(PowerMockRunner.class)
public class MyJunitTest {

   private static boolean condition = false;

   @Test
   public void myFirstTest() {
      assumeTrue(condition);
      //my mocking and junit stuff
   }
} What is the expected output? What do you see instead? The default JUnit runner treats tests with failing assumptions as ignored. But test status should be passed.

Instead the test failes What version of the product are you using? On what operating system? powermock-mockito-1.4.12-full with junit-4.8.2 Please provide any additional information below. Trace of the output
org.junit.internal.AssumptionViolatedException: got: \<false>, expected: is \<true>
	at org.junit.Assume.assumeThat(Assume.java:70)
	at org.junit.Assume.assumeTrue(Assume.java:39)
	at ......myFirstTest
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:66)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:312)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:86)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:94)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:296)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:112)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:73)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:284)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:84)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:49)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:209)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:148)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:122)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:120)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:102)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:42)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:49)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

_Original issue: http://code.google.com/p/powermock/issues/detail?id=408_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 29, 2012 10:45:24_

I'm not familiar with assumeTrue(..) and I've never used it. It would be cool if PowerMock could support it though. If you're up for it please help out and provide a patch to the PowerMockRunner.

**Comment by johanhaleby** [comment]
_From [openid4...@gmail.com](https://code.google.com/u/102723891794240846979/) on June 12, 2013 01:08:54_

Well, I have no patch, but perhaps some information:

The PowerMockJUnit44MethodRunner overrides the method runTestMethod of MethodRoadie.
In the original code (junit v4.11) there is an \<b>if</b> statement that catches those exceptions:
-------------------- 8< ------------------
    protected void runTestMethod() {
        try {
            fTestMethod.invoke(fTest);
            if (fTestMethod.expectsException()) {
                addFailure(new AssertionError("Expected exception: " + fTestMethod.getExpectedException().getName()));
            }
        } catch (InvocationTargetException e) {
            Throwable actual = e.getTargetException();

            *if (actual instanceof AssumptionViolatedException) {
                return;
            }* else if (!fTestMethod.expectsException()) {
                addFailure(actual);
            } else if (fTestMethod.isUnexpected(actual)) {
                String message = "Unexpected exception, expected<" + fTestMethod.getExpectedException().getName() + "> but was<"
                        + actual.getClass().getName() + ">";
                addFailure(new Exception(message, actual));
            }
        } catch (Throwable e) {
            addFailure(e);
        }
    }
-------------------- 8< ------------------

**Comment by johanhaleby** [comment]
_From [openid4...@gmail.com](https://code.google.com/u/102723891794240846979/) on June 12, 2013 01:59:07_

This patch works for me.
(org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl)

powermock 1.5
junit 4.11

**Attachment:** [patch.txt](http://code.google.com/p/powermock/issues/detail?id=408#hc5)

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on June 12, 2013 23:03:59_

Couldn't get the patch to work but I tried to implement it myself. Please try it out by building PowerMock from source. Thanks for your help!

**Status:** Fixed

**Comment by johanhaleby** [comment]
_From [openid4...@gmail.com](https://code.google.com/u/102723891794240846979/) on July 29, 2013 06:29:18_

Well, the exception has gone, but the test case is marked as passed, instead of skipped?

Looking into the source, there might be missing some skipping code (marked with XXX):
e.g. runNotifier.fireTestIgnored(description)

[org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl:343]
----------------------- 8< ----------------------
                if (throwableName.equals("org.junit.internal.AssumptionViolatedException") || throwableName.startsWith("org.junit.Assume$AssumptionViolatedException")) {
                    XXXXXXXXXXXX
                    return;
                } else if (!(Boolean) Whitebox.invokeMethod(testMethod, "expectsException")) {
----------------------- 8< ----------------------

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on July 30, 2013 10:04:32_

Please provide a patch  and I'll include it in the next release.

**Status:** Accepted

**Comment by rdiachenko** [comment]
+1 to fixing this problem. There is an issue in Checkstyle related to this bug: https://github.com/checkstyle/checkstyle/issues/2191

**Comment by darylducharme** [comment]
This still seems to be a problem in Powermock 1.6.6. The reason is that the throwable name it is looking for is org.junit.internal.AssumptionViolatedException but the one it is finding is org.junit.AssumptionViolatedException which is a child class of the junit.internal version.

The workaround for me is to use @PowerMockRunnerDelegate(...) with a runner that works (i.e. Junit4)

**Comment by JDFind** [comment]
This still happens on version 2.0.
Are there any updates?
