### ISSUE TITLE
ClassFormatError: Invalid this class index 50945 in constant pool in class file

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#429]
_From [ric.flai...@gmail.com](https://code.google.com/u/104213777758065142109/) on November 14, 2012 17:43:18_

Hi,

I wanted to test a class with PowerMock wich is quite big (approximately 6800 lines). I have to use the annotation SuppressStaticInitializationFor to suppress some static initialization of this class. I got the error below.

The version of PowerMock is 1.4.11. Javassist version is 3.15.0-GA (I tried the 3.16.1 too). The operatin system is Windows XP.

If I decreased the size of the class I didn't get the error.

java.lang.ClassFormatError: Invalid this class index 50945 in constant pool in class file com/virginmedia/pco/webserviceclients/SendEmail_V3
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:465)
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:210)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:145)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2291)
	at java.lang.Class.getDeclaredFields(Class.java:1743)
	at org.powermock.reflect.internal.WhiteboxImpl.findAllFieldsUsingStrategy(WhiteboxImpl.java:533)
	at org.powermock.reflect.internal.WhiteboxImpl.getFieldsAnnotatedWith(WhiteboxImpl.java:2343)
	at org.powermock.reflect.internal.WhiteboxImpl.getFieldsAnnotatedWith(WhiteboxImpl.java:2326)
	at org.powermock.reflect.Whitebox.getFieldsAnnotatedWith(Whitebox.java:568)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:70)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:284)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:84)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:49)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:209)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:148)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:122)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:120)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:102)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:42)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:172)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:104)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:70)

_Original issue: http://code.google.com/p/powermock/issues/detail?id=409_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 29, 2012 10:43:57_

What Java version are you using? Please try upgrading to the latest version of PowerMock and see if you get the same issue. If you're using java 7 you must use PowerMock trunk and Javassist 3.17.

**Comment by johanhaleby** [comment]
_From [ric.flai...@gmail.com](https://code.google.com/u/104213777758065142109/) on November 30, 2012 02:40:56_

Hi, thanks for the reply!
I am using jdk1.6.0_30. I tried the latest PowerMock too.
Is it possible that I get this error because the class is too big which I want to test?
Thanks,
V.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 30, 2012 03:14:53_

It could be, I remember there was someone a couple of years ago that had a similar problem when the class was huge. If it doesn't work with the latest version of Javassist then I think you should post a bug report on the Javassist bug tracker.

**Comment by johanhaleby** [comment]
_From [ric.flai...@gmail.com](https://code.google.com/u/104213777758065142109/) on November 30, 2012 03:19:32_

Ok, thank you for your help!
V.

**Comment by johanhaleby** [comment]
_From [mohamed....@gmail.com](https://code.google.com/u/113496429414382419601/) on May 08, 2013 07:59:48_

You can use this option to fix this problem: -XX:-UseSplitVerifier
If you run your test in eclipse : Windows-Preferences-Java-Installed JREs
Select your JDK and click on edit, in the defalut VM arguments add -XX:-UseSplitVerifier
I faced a similar problem and it works fine for me

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 28, 2014 06:13:00_

**Status:** Duplicate
