### ISSUE TITLE
powermock causes Mockito's initMocks to fail when using @Mock

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#434]
_From [jon.cho...@actifio.com](https://code.google.com/u/111074474560208848172/) on December 04, 2012 20:16:54_

Here is my class under test:

public class MockMe {

    private static final MockMe ME = new MockMe();

    public static MockMe getInstance() {
            return ME;
    }

}

And here is my test:

import static org.mockito.MockitoAnnotations.initMocks;
import static org.powermock.api.mockito.PowerMockito.mockStatic;
import static org.powermock.api.mockito.PowerMockito.when;
import static org.testng.Assert.assertEquals;

import org.powermock.core.classloader.annotations.Mock;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.testng.PowerMockObjectFactory;
import org.testng.IObjectFactory;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.ObjectFactory;
import org.testng.annotations.Test;

@PrepareForTest({MockMe.class})
public class TestTest {

    @ObjectFactory
    public IObjectFactory getObjectFactory() {
        return new PowerMockObjectFactory();
    }

    @Mock
    public MockMe mockMe;

    @BeforeTest
    public void init() {
        initMocks(this);
        mockStatic(MockMe.class);
        when(MockMe.getInstance()).thenReturn(mockMe);
    }

    @Test
    public void sampleTest() {
        MockMe mockMe1 = MockMe.getInstance();
        assertEquals(mockMe1, mockMe);
    }
}

When I run this test it succeeds but If I replace the deprecated 

org.powermock.core.classloader.annotations.Mock

with the appropriate

org.mockito.Mock

The test fails with the following stack trace:

FAILED CONFIGURATION: @BeforeTest init
java.lang.ExceptionInInitializerError
	at org.mockito.internal.exceptions.stacktrace.ConditionalStackTraceFilter.<init>(ConditionalStackTraceFilter.java:17)
	at org.mockito.exceptions.base.MockitoException.filterStackTrace(MockitoException.java:30)
	at org.mockito.exceptions.base.MockitoException.<init>(MockitoException.java:19)
	at org.mockito.exceptions.misusing.MockitoConfigurationException.<init>(MockitoConfigurationException.java:18)
	at org.mockito.internal.configuration.ClassPathLoader.loadImplementations(ClassPathLoader.java:145)
	at org.mockito.internal.configuration.ClassPathLoader.findPluginImplementation(ClassPathLoader.java:110)
	at org.mockito.internal.configuration.ClassPathLoader.findPlatformMockMaker(ClassPathLoader.java:106)
	at org.mockito.internal.configuration.ClassPathLoader.<clinit>(ClassPathLoader.java:59)
	at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:21)
	at org.mockito.internal.MockitoCore.<init>(MockitoCore.java:40)
	at org.mockito.internal.stubbing.defaultanswers.ReturnsMocks.<init>(ReturnsMocks.java:18)
	at org.mockito.Answers.<clinit>(Answers.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at java.lang.Class.getEnumConstantsShared(Class.java:2942)
	at java.lang.Class.enumConstantDirectory(Class.java:2963)
	at java.lang.Enum.valueOf(Enum.java:191)
	at sun.reflect.annotation.AnnotationParser.parseEnumValue(AnnotationParser.java:413)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:278)
	at java.lang.reflect.Method.getDefaultValue(Method.java:720)
	at sun.reflect.annotation.AnnotationType.<init>(AnnotationType.java:99)
	at sun.reflect.annotation.AnnotationType.getInstance(AnnotationType.java:66)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:202)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:69)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:52)
	at java.lang.reflect.Field.declaredAnnotations(Field.java:1014)
	at java.lang.reflect.Field.getAnnotation(Field.java:1000)
	at java.lang.reflect.AccessibleObject.isAnnotationPresent(AccessibleObject.java:168)
	at org.powermock.reflect.internal.matcherstrategies.FieldAnnotationMatcherStrategy.matches(FieldAnnotationMatcherStrategy.java:37)
	at org.powermock.reflect.internal.WhiteboxImpl.findAllFieldsUsingStrategy(WhiteboxImpl.java:535)
	at org.powermock.reflect.internal.WhiteboxImpl.getFieldsAnnotatedWith(WhiteboxImpl.java:2343)
	at org.powermock.reflect.Whitebox.getFieldsAnnotatedWith(Whitebox.java:585)
	at org.powermock.api.extension.listener.AnnotationEnabler.standardInject(AnnotationEnabler.java:70)
	at org.powermock.api.extension.listener.AnnotationEnabler.beforeTestMethod(AnnotationEnabler.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.powermock.reflect.internal.WhiteboxImpl.performMethodInvocation(WhiteboxImpl.java:2014)
	at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:744)
	at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:415)
	at org.powermock.modules.testng.internal.PowerMockTestNGMethodHandler.injectMocksUsingAnnotationEnabler(PowerMockTestNGMethodHandler.java:72)
	at org.powermock.modules.testng.internal.PowerMockTestNGMethodHandler.invoke(PowerMockTestNGMethodHandler.java:47)
	at com.actifio.psrv.util.analysis.TestTest_$$_javassist_0.init(TestTest_$$_javassist_0.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:641)
	at org.testng.TestRunner.run(TestRunner.java:609)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.TestNG.privateMain(TestNG.java:1338)
	at org.testng.TestNG.main(TestNG.java:1307)
Caused by: java.lang.NullPointerException
	at org.mockito.internal.exceptions.stacktrace.S...

_Original issue: http://code.google.com/p/powermock/issues/detail?id=414_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on December 05, 2012 12:59:31_

Try extending from PowerMockTestCase and see if you get the same error.

**Comment by johanhaleby** [comment]
_From [joelcap...@gmail.com](https://code.google.com/u/102199146124355822687/) on January 05, 2013 23:38:50_

Same (similar) issue here with PowerMock 1.5. See attached pom, test case and class under test.

Can confirm the problem disappears if I make the test case extend PowerMockTestCase.

**Attachment:** [pom.xml IdentifiableEntityTest.java IdentifiableEntity.java](http://code.google.com/p/powermock/issues/detail?id=414#hc2)

**Comment by johanhaleby** [comment]
_From [mahoney...@gmail.com](https://code.google.com/u/108154979926108717087/) on February 24, 2013 13:34:48_

I think I have a simpler test case. This seems to happen when a mock is created at instantation time. If I set up my mocks in an @Before method the issue goes away.

I believe this is a ClassLoader issue - PowerMockMaker is loaded by the system classloader, but org.mockito.plugins.MockMaker is also loaded by the org.powermock.core.classloader.MockClassLoader and so PowerMockMaker is not an instance of MockMaker.

It may be an unavoidable limitation of PowerMock, but the resulting exception is completely unhelpful and gives no hint of how to fix the issue.

Simpler example test exhibiting the symptoms:

import java.util.List;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;

import static org.junit.Assert.assertFalse;
import static org.mockito.Mockito.mock;

@RunWith(PowerMockRunner.class)
@PrepareForTest(SomeClass.class)
public class TestSomeClass {

    private final List list = mock(List.class);

    @Test
    public void invertTrue() {
        assertFalse(false);
    }
}

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on February 24, 2013 23:17:40_

Thanks for your example. People have run into simliar issues when using mock policies with PowerMock and Mockito 1.9.5. I've committed a work-around for that but I'm not sure if it's as easy in this case.

**Comment by johanhaleby** [comment]
_From [apw.desi...@gmail.com](https://code.google.com/u/109727435219823482454/) on April 17, 2013 03:53:36_

Any process here? Having the same issue, which is very annoying because we would like to upgrade to 1.9.5 to get Java 7 support. We can confirm that this seems to be a ClassLoading issue.

**Comment by johanhaleby** [comment]
_From [nfr...@gmail.com](https://code.google.com/u/103552940911507195155/) on September 23, 2013 10:04:43_

I am facing the same issue using Mockito + powerMock with TestNG. I can't use @RunWith since it is a JUnit annotation ; I use @ObjectFactory instead.


Here is my test class :

import org.mockito.MockitoAnnotations;
import org.powermock.api.mockito.PowerMockito;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.testng.PowerMockObjectFactory;
import org.testng.Assert;
import org.testng.IObjectFactory;
import org.testng.annotations.ObjectFactory;
import org.testng.annotations.Test;

@PrepareForTest(Static.class)
public class FakeForTestTest {

	@ObjectFactory
	public IObjectFactory setObjectFactory() {
		return new PowerMockObjectFactory();
	}

	@Test
	public void shouldBeValid() {
		PowerMockito.mockStatic(Static.class);
		MockitoAnnotations.initMocks(this);
		Object testObject = new Double(50);
		PowerMockito.when(Static.isValid(testObject)).thenReturn(true);

		FakeForTest fft = new FakeForTest();
		Boolean reel = fft.isValid(testObject);
		Assert.assertTrue(reel, "Error");
	}
}

**Comment by johanhaleby** [comment]
_From [hamish.t...@gmail.com](https://code.google.com/u/114503445545976175202/) on September 26, 2013 18:27:56_

Need help for this . using java 1.7

**Comment by johanhaleby** [comment]
_From [AZagorne...@gmail.com](https://code.google.com/u/113804023413479646909/) on September 26, 2013 23:26:34_

When using PowerMock with TestNG always extend your test from org.powermock.modules.testng.PowerMockTestCase. By doing this you don't have to bother about providing custom object factory, so you will not have @ObjectFactory in your test at all. For me this solved the problem.

**Comment by johanhaleby** [comment]
_From [robert....@gmail.com](https://code.google.com/u/110719374765861436065/) on October 09, 2013 10:48:46_

Any workarounds for JUnit? I don't have TestNG nor any of the Powermock TestNG libraries on the classpath. 

I've also noticed this issue comes up with @BeforeClass mock initialization.

**Comment by johanhaleby** [comment]
_From [arnaud.l...@gmail.com](https://code.google.com/u/100272693967231882147/) on October 28, 2013 08:52:59_

Same issue here with Junit.
Workaround is to add "org.mockito.*" in @PowerMockIgnore

**Comment by johanhaleby** [comment]
_From [hashbro...@gmail.com](https://code.google.com/u/106201673254480037557/) on November 01, 2013 09:09:07_

Looks like this same issue was fixed in gwtMockito, perhaps that can help here as well? https://github.com/google/gwtmockito/issues/14

**Comment by johanhaleby** [comment]
_From [robert....@redfin.com](https://code.google.com/u/111491601510538702198/) on November 13, 2013 10:20:58_

Based on the fix mentioned by in `#11`, I created a patch for JUnit4TestSuiteChunkerImpl that seems to fix the problem. I ran it on a project internally w/ ~700 tests that used to fail due to this bug, and they now succeed.

I also attempted to figure out how to add a test case to powermock for this issue, but it turned out to be easier to find the location for the fix than it was to find out where I would put a test for it. :)

Patch file is attached.

**Attachment:** [issue-414.patch](http://code.google.com/p/powermock/issues/detail?id=414#hc12)

**Comment by johanhaleby** [comment]
_From [robert....@redfin.com](https://code.google.com/u/111491601510538702198/) on November 13, 2013 10:22:49_

Sorry, I should have been more clear: I created a patch for the issue when running through JUnit. I don't have much/any experience w/ TestNG.

**Comment by johanhaleby** [comment]
_From [Jaepyoun...@gmail.com](https://code.google.com/u/104779365313391969038/) on January 09, 2014 13:16:37_

I have a similar issue. 
My platform is Testng-6.8.7 and Powermock-1.5.2, and Mockito-1.9.5
And if I extends PowerMockTestCase, then the issue is not happening. Only when I use the following. 

@ObjectFactory
	public IObjectFactory getObjectFactory() {
	    return new org.powermock.modules.testng.PowerMockObjectFactory();
	}


The following is the exceptions error. 

java.lang.ExceptionInInitializerError
	at org.mockito.internal.exceptions.stacktrace.ConditionalStackTraceFilter.<init>(ConditionalStackTraceFilter.java:17)
	at org.mockito.exceptions.base.MockitoException.filterStackTrace(MockitoException.java:30)
	at org.mockito.exceptions.base.MockitoException.<init>(MockitoException.java:19)
	at org.mockito.exceptions.misusing.MockitoConfigurationException.<init>(MockitoConfigurationException.java:18)
	at org.mockito.internal.configuration.ClassPathLoader.loadImplementations(ClassPathLoader.java:145)
	at org.mockito.internal.configuration.ClassPathLoader.findPluginImplementation(ClassPathLoader.java:110)
	at org.mockito.internal.configuration.ClassPathLoader.findPlatformMockMaker(ClassPathLoader.java:106)
	at org.mockito.internal.configuration.ClassPathLoader.<clinit>(ClassPathLoader.java:59)
	at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:21)
	at org.mockito.internal.configuration.injection.scanner.MockScanner.<init>(MockScanner.java:22)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.injectMocks(InjectingAnnotationEngine.java:96)
	at org.powermock.api.mockito.internal.configuration.PowerMockitoInjectingAnnotationEngine.process(PowerMockitoInjectingAnnotationEngine.java:35)
	at org.powermock.api.extension.listener.AnnotationEnabler.injectSpiesAndInjectToSetters(AnnotationEnabler.java:57)
	at org.powermock.api.extension.listener.AnnotationEnabler.beforeTestMethod(AnnotationEnabler.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.powermock.reflect.internal.WhiteboxImpl.performMethodInvocation(WhiteboxImpl.java:2014)
	at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:744)
	at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:415)
	at org.powermock.modules.testng.internal.PowerMockTestNGMethodHandler.injectMocksUsingAnnotationEnabler(PowerMockTestNGMethodHandler.java:75)
	at org.powermock.modules.testng.internal.PowerMockTestNGMethodHandler.invoke(PowerMockTestNGMethodHandler.java:47)
	at com.ibaset.solumina.sfcore.application.impl.LoginImplTest_$$_jvstdd8_0.getFoundationVersion_NoDash_LongSameShortEmpty(LoginImplTest_$$_jvstdd8_0.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: java.lang.NullPointerException
	at org.mockito.internal.exceptions.stacktrace.StackTraceFilter.<clinit>(StackTraceFilter.java:21)
	... 48 more

**Comment by johanhaleby** [comment]
_From [khid...@gmail.com](https://code.google.com/u/103319437564523759992/) on September 23, 2014 23:58:48_

Following 2 workarounds helped me get over this:
1. Do not use private static instance field:
   private static final MockMe ME = new MockMe();

2. Make TestNG test method 'final'.  Not sure how this helps, but it did help me.

**Comment by leizhiyuan** [comment]
@johanhaleby  thank you,this problem occured in my project..Make TestNG test method 'final' is ok.

**Comment by dlazerka** [comment]
The simplest example I think:
```java
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.testng.PowerMockObjectFactory;
import org.testng.annotations.ObjectFactory;
import org.testng.annotations.Test;

class DoesntMatter {}

@PrepareForTest(DoesntMatter.class)
public class UnitTest1 {

	//Object mock = PowerMockito.mock(Object.class); // uncommenting this fixes issue

	@ObjectFactory
	public PowerMockObjectFactory getObjectFactory() {
		return new PowerMockObjectFactory();
	}

	@Test
	public void test() throws Exception {
		// do job
	}
}
```
Extending PowerMockTestCase fixes it.
Hope that helps.

**Comment by samrocketman** [comment]
I found that if you add the class you want to `@Mock` with `org.mockito.Mock` to the `PrepareForTest` annotation it works just fine.

e.g.

```java
package org.jenkinsci.plugins;

import jenkins.model.Jenkins;
import junit.framework.TestCase;
import org.jenkinsci.plugins.GithubSecurityRealm.DescriptorImpl;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.powermock.api.mockito.PowerMockito;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;
import static org.mockito.Matchers.anyObject;

@RunWith(PowerMockRunner.class)
@PrepareForTest({Jenkins.class, GithubSecurityRealm.class, DescriptorImpl.class})
public class GithubLogoutActionTest extends TestCase {

    @Mock
    private Jenkins jenkins;

    @Mock
    private GithubSecurityRealm securityRealm;

    @Mock
    private DescriptorImpl descriptor;

    @Before
    public void setUp() throws Exception {
        PowerMockito.mockStatic(Jenkins.class);
        PowerMockito.when(Jenkins.getInstance()).thenReturn(jenkins);
        PowerMockito.when(jenkins.getSecurityRealm()).thenReturn(securityRealm);
        PowerMockito.when(securityRealm.getDescriptor()).thenReturn(descriptor);
        PowerMockito.when(descriptor.getDefaultGithubWebUri()).thenReturn("https://github.com");
    }

    private void mockGithubSecurityRealmWebUriFor(String host) {
        PowerMockito.when(securityRealm.getGithubWebUri()).thenReturn(host);
    }

    @Test
    public void testGetGitHubText_gh() {
        mockGithubSecurityRealmWebUriFor("https://github.com");
        GithubLogoutAction ghlogout = new GithubLogoutAction();
        assertTrue("GitHub".equals(ghlogout.getGitHubText()));
    }

    @Test
    public void testGetGitHubText_ghe() {
        mockGithubSecurityRealmWebUriFor("https://ghe.example.com");
        GithubLogoutAction ghlogout = new GithubLogoutAction();
        assertTrue("GitHub Enterprise".equals(ghlogout.getGitHubText()));
    }
}
```

**Comment by IevgenGoltsev** [comment]
Hello, is it still not solved?
I have `initMocks` and `mockStatic `in the same place (method with `@Before` annotation) and it fails with
`Invoking the beforeTestMethod method on PowerMock test listener org.powermock.api.extension.listener.AnnotationEnabler@3e694b3f failed.`

Thanks.

**Comment by IevgenGoltsev** [comment]
Okay, in my case [mock-maker-inline](https://github.com/powermock/powermock/wiki/mockito#mockito-mock-maker-inline) was a reason.

**Comment by KamalashreeSundar** [comment]
Hi even i had the same issue -
 Invoking the beforeTestMethod method on PowerMock test listener org.powermock.api.extension.listener.AnnotationEnabler@3e694b3f failed. - it was due to the mock-maker-inline adding . 

> Okay, in my case [mock-maker-inline](https://github.com/powermock/powermock/wiki/mockito#mockito-mock-maker-inline) was a reason.

Thanks even I had the same issue , it helped me
