### ISSUE TITLE
@RunWith(PowerMockRunner.class) failed with Junit4 ExpectedException Rule

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#436]
_From [yvesdm](https://code.google.com/u/yvesdm/) on December 07, 2012 14:46:18_

What steps will reproduce the problem? 1. see attached unit test What is the expected output? What do you see instead? As is :
 Running this test with @RunWith(PowerMockRunner.class) will failed
 Running this test without @RunWith(PowerMockRunner.class) will suceed
Expected :
 using @RunWith(PowerMockRunner.class) should not failed the test. What version of the product are you using? On what operating system? junit.version 4.11
powermock.version 1.5
java 1.6.0_18
Windows 7 Please provide any additional information below.

**Attachment:** [ExceptionUnitTest.java](http://code.google.com/p/powermock/issues/detail?id=416)

_Original issue: http://code.google.com/p/powermock/issues/detail?id=416_

**Comment by johanhaleby** [comment]
_From [tim.br...@gmail.com](https://code.google.com/u/100616999449370776195/) on December 11, 2012 08:43:12_

I have a similar issue.  It seems to be a hamcrest version problem.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 21, 2013 23:27:48_

Yes Hamcrest versioning can be a nightmare if you have other projects in your classpath that uses another version of Hamcrest. Unfortunately I don't think PowerMock can do anything about this.

**Comment by johanhaleby** [comment]
_From [sander.s...@jdriven.com](https://code.google.com/u/106471891549992508934/) on March 14, 2013 02:47:25_

I have the same issue, using powermock 1.4.12, junit 4.11 and mockito 1.9.0.
THis results in the following stacktrace:

java.lang.ClassCastException: org.junit.rules.ExpectedException cannot be cast to org.junit.rules.MethodRule
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:79)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:284)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:86)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:49)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:209)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:148)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:122)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:33)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:45)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:120)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:102)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:42)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 14, 2013 23:32:28_

Try latest trunk
