### ISSUE TITLE
java.lang.ClassFormatError: Invalid length xxxx in LocalVariableTable in class file a/b/MyClass

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#449]
_From [wangyu1...@gmail.com](https://code.google.com/u/109551924329177378761/) on February 04, 2013 02:46:47_

What steps will reproduce the problem? 1.use annotation in class
@RunWith(PowerMockRunner.class)
@PrepareForTest({ MyClass.class, AnotherClass.class })

2.run the testcase by junit4 in eclipse

then console display:

java.lang.ClassFormatError: Invalid length 1713 in LocalVariableTable in class file a/b/MyClass.class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:465)
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:222)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:147)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:67)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:247)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:95)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:107)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:31)
	at sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:370)
	at sun.reflect.annotation.AnnotationParser.parseClassValue(AnnotationParser.java:351)
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:653)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:460)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:222)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:69)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:52)
	at java.lang.Class.initAnnotationsIfNecessary(Class.java:3070)
	at java.lang.Class.getAnnotations(Class.java:3050)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.classAnnotations(PowerMockJUnit44RunnerDelegateImpl.java:165)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.getDescription(PowerMockJUnit44RunnerDelegateImpl.java:157)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.getDescription(JUnit4TestSuiteChunkerImpl.java:171)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.getDescription(AbstractCommonPowerMockRunner.java:47)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:49)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

this error occured in both PowerMock 1.4.11 & 1.5, and mockito version is 1.9.0

how can i fix it? there was no error with same usage in past.

_Original issue: http://code.google.com/p/powermock/issues/detail?id=429_

**Comment by johanhaleby** [comment]
_From [wangyu1...@gmail.com](https://code.google.com/u/109551924329177378761/) on February 03, 2013 18:00:09_

then i use javap to process MyClass.class, and i can't find anything in any LocalVariableTable with length 1713

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 27, 2013 05:10:45_

Could be some troubles with Javassist, see issue #355 .

**Comment by shekharhimanshu** [comment]
I am facing the same issue with the latest power mock versions.

PowerMock: 1.6.6
Javassist: 3.20.0-GA
Java: Java 8 Update 111

Any ideas how to solve this?

**Comment by oawang** [comment]
Have you solved it？

**Comment by haseebnk** [comment]
same issue Invalid length 32769 in LocalVariableTypeTable in class file com/sun/xml/bind/v2/runtime/reflect/Lister$IDREFS
