### ISSUE TITLE
powermock @RunWith(PowerMockRunner.class) cause classNotFoundException 

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#456]
_From [klein...@gmail.com](https://code.google.com/u/101205824346129362384/) on March 18, 2013 16:35:19_

Hi,

I am using PowerMock to mock static object.
When I am running a test in Eclipse everything is fine, but running it via ANT (Junit) on my Linux Sabayon I get the following (I get it even when only adding: @RunWith(PowerMockRunner.class)):

java.lang.RuntimeException: Internal error in PowerMock
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:141)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:122)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:120)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:102)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:42)
Caused by: java.lang.ClassNotFoundException: com.oversi.vcache.ttt
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:138)

_Original issue: http://code.google.com/p/powermock/issues/detail?id=436_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 26, 2013 12:49:32_

This is most likely a classpath issue since it works in Eclipse. Please investigate your classpath to find the difference.

**Status:** Invalid
