### ISSUE TITLE
Cannot instantiate com.sun.net.ssl.internal.ssl.Provider when using PowerMockRunner

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#461]
_From [rafal...@gmail.com](https://code.google.com/u/106206838492680896342/) on April 13, 2013 18:12:03_

What steps will reproduce the problem? Run this example:

@RunWith(PowerMockRunner.class)
@PrepareForTest(Dummy.class)
public class PowerMockTest {

    @Before
    public void setUp() {
        Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());
    }

    @Test
    public void test() {
    }
}

class Dummy {
} What is the expected output? What do you see instead? It throws exception:

java.lang.AssertionError: Illegal subclass: class com.sun.net.ssl.internal.ssl.Provider
	at sun.security.ssl.SunJSSE.subclassCheck(SunJSSE.java:232)
	at sun.security.ssl.SunJSSE.<init>(SunJSSE.java:107)
	at com.sun.net.ssl.internal.ssl.Provider.<init>(Provider.java:41)
	at PowerMockTest.setUp(PowerMockTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.internal.runners.MethodRoadie.runBefores(MethodRoadie.java:129)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:93) What version of the product are you using? On what operating system? Windows 7, powermock 1.5

Here are my gradle dependencies:

testCompile 'junit:junit:4.10',
            'org.mockito:mockito-all:1.9.5',
            'org.powermock:powermock-api-mockito:1.5',
            'org.powermock:powermock-module-junit4:1.5' Please provide any additional information below.

_Original issue: http://code.google.com/p/powermock/issues/detail?id=441_

**Comment by johanhaleby** [comment]
_From [rafal...@gmail.com](https://code.google.com/u/106206838492680896342/) on April 13, 2013 09:18:14_

Forgot this: it works on java 6, it doesn't work on java 7 (jdk1.7.0_17)

**Comment by johanhaleby** [comment]
_From [rafal...@gmail.com](https://code.google.com/u/106206838492680896342/) on April 13, 2013 11:58:57_

It turned out it's easy to fix, just add this:

@PowerMockIgnore("com.sun.net.ssl.internal.ssl.Provider")

**Comment by efecanahmetoglu** [comment]
I faced same issue when move to java 17 and exact solution is like that: 
  **POM:**

```
 <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <argLine>
                                --add-opens java.base/java.lang=ALL-UNNAMED
                                --add-opens java.base/java.io=ALL-UNNAMED
                                --add-opens java.base/java.util=ALL-UNNAMED
                                --add-opens java.base/java.base=ALL-UNNAMED
                            </argLine>
                            <skipTests>${skip.unit.tests}</skipTests>
                        </configuration>
 </plugin>
```

**Comment by shivaniy24** [comment]
Hi everyone,

We are migrating our code from java1.8 to jdk17. In the process of doing that  we need to make  
Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider()); java17 compatible.

Found this SSLContext.getInstance("TLS","SunJSSE");, but it only works for single protocol. 
Is there anyway , any function or library I can use which can allow me to pass all the protocols at once ?SSLv3/TLSv1/TLSv1.1/TLSv1.2/TLSv1.3
