### ISSUE TITLE
PowerMock.mockStatic does not work with RETURN_DEEP_STUBS

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#507]
_From [michael....@googlemail.com](https://code.google.com/u/111433003607366612606/) on March 18, 2014 13:49:39_

I'll try the following (quite simple) static method mocking in my test:

@RunWith(PowerMockRunner.class)
@PrepareForTest({ FacesContext.class })
public class MyControllerTest {

@Test
public final void testAnything() {
...
PowerMockito.mockStatic(FacesContext.class, RETURNS_DEEP_STUBS);
PowerMockito.when(FacesContext.getCurrentInstance().getExternalContext().getRequestLocale()).thenReturn(Locale.GERMANY);
...
}

I would expect that I can mock in this way the deep stubbed call to my locale, but I got the following error:

java.lang.NullPointerException
	at org.mockito.internal.stubbing.defaultanswers.ReturnsDeepStubs.getMock(ReturnsDeepStubs.java:47)
	at org.mockito.internal.stubbing.defaultanswers.ReturnsDeepStubs.answer(ReturnsDeepStubs.java:39)
	at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:93)
	at org.powermock.api.mockito.internal.invocation.MockitoMethodInvocationControl.performIntercept(MockitoMethodInvocationControl.java:260)
	at org.powermock.api.mockito.internal.invocation.MockitoMethodInvocationControl.invoke(MockitoMethodInvocationControl.java:192)
	at org.powermock.core.MockGateway.doMethodCall(MockGateway.java:105)
	at org.powermock.core.MockGateway.methodCall(MockGateway.java:60)
	at javax.faces.context.FacesContext.getCurrentInstance(FacesContext.java)
	at my.test.MyControllerTest.testAnything(MyControllerTest.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:310)
	at org.junit.internal.runners.MethodRoadie$2.run(MethodRoadie.java:88)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:96)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:294)
	at ...

I'm using PowerMock in version 1.5.1 and Mockito in version 1.9.5.

Ok, I could find a quick workaround by calling:
...
PowerMockito.mockStatic(FacesContext.class);
FacesContext fContext = Mockito.mock(FacesContext.class, RETURNS_DEEP_STUBS);
PowerMockito.when(FacesContext.getCurrentInstance()).thenReturn(fContext);
Mockito.when(fContext.getExternalContext().getRequestLocale()).thenReturn(Locale.GERMANY);
...

But in my point of view it is an error of PowerMock NOT to support deep stub calls for static methods, isn't it?!

_Original issue: http://code.google.com/p/powermock/issues/detail?id=487_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 20, 2014 23:13:39_

PowerMock has never supported deep stub calls if I can remember it correctly. Please help out by providing a patch.

**Status:** Accepted

**Comment by johanhaleby** [comment]
_From [xmarcus89@googlemail.com](https://code.google.com/u/xmarcus89@googlemail.com/) on August 27, 2014 05:12:18_

I also ran now into this problem. Very annoying as one except it to work similar to Mockito. Good to have this issue found so that I can move on getting a work around.

**Comment by johanhaleby** [comment]
_From [xmarcus89@googlemail.com](https://code.google.com/u/xmarcus89@googlemail.com/) on December 05, 2014 01:19:42_

Yeah, I found my own comment again by googling this issue, wonderful ... I still would love to see this fixed :(

**Comment by johanhaleby** [comment]
_From [chriss....@gmail.com](https://code.google.com/u/116739628974753029977/) on March 10, 2015 01:00:48_

Dear PowerMock-Devs, what must be done to get RETURN_DEEP_STUBS working?  I and maybe other's want to send you pull requests with a fix.

 - Which classes are involved?
 - What should be considered?
 - What should not be done?
 - ...

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 10, 2015 03:32:31_

I think that the best way to find out is to look at the source code for non-static mocks and port it to static mocks as well.

**Comment by johanhaleby** [comment]
_From [chriss....@gmail.com](https://code.google.com/u/116739628974753029977/) on March 12, 2015 13:28:49_

I try to find a solution in the discussion group-> https://groups.google.com/forum/#!topic/powermock/g9gV6cyR-Ng

**Comment by Lakshmi-Arunachalam** [comment]
Has anyone found a solution for this ?

**Comment by senthilmurukang** [comment]
Is there any solution to this issue yet?
