### ISSUE TITLE
Invalid length in LocalVariableTable with javassist-3.14GA

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#517]
_From [Ferrucci...@gmail.com](https://code.google.com/u/115929389490724795639/) on May 07, 2014 05:19:14_

PrepareFotTest a class
I see the exception only for this class,and when I delete the code in the method doCommit,the exception disappeared;

I tried powermock-1.4.10 + mockito-1.9.0 + javassist3.15GA  and pm-1.4.9+m-1.8.5+javassist3.14GA. Both throws the Exception.

The java source of the classes in the attach. Please provide any additional information below. com.alipay.cifcommon.coordinator.test.powermock.RawTypeTest  Time elapsed: 1.022 sec  \<<< ERROR!
java.lang.ClassFormatError: Invalid length 90 in LocalVariableTable in class file com/alipay/cifcommon/coordinator/test/powermock/RawTypeForTest
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:465)
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:210)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:145)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:95)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:107)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:31)
	at sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:370)
	at sun.reflect.annotation.AnnotationParser.parseClassValue(AnnotationParser.java:351)
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:653)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:460)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:222)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:69)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:52)
	at java.lang.Class.initAnnotationsIfNecessary(Class.java:3079)
	at java.lang.Class.getAnnotations(Class.java:3059)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.classAnnotations(PowerMockJUnit44RunnerDelegateImpl.java:163)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.getDescription(PowerMockJUnit44RunnerDelegateImpl.java:155)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:118)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:102)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

_Original issue: http://code.google.com/p/powermock/issues/detail?id=497_

**Comment by johanhaleby** [comment]
_From [Ferrucci...@gmail.com](https://code.google.com/u/115929389490724795639/) on May 06, 2014 20:19:34_

**Attachment:** [RawTypeForTest.java RawTypeTest.java](http://code.google.com/p/powermock/issues/detail?id=497#hc1)

**Comment by johanhaleby** [comment]
_From [Ferrucci...@gmail.com](https://code.google.com/u/115929389490724795639/) on May 06, 2014 23:11:32_

close this, the system classloader load a javassist3.11 class

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 28, 2014 00:22:25_

**Status:** WontFix
