### ISSUE TITLE
PowerMockito.mockStatic() failing for class with large static methods

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#523]
_From [deepakme...@gmail.com](https://code.google.com/u/107304771433987055514/) on June 27, 2014 10:45:57_

What steps will reproduce the problem? 1.call PowerMockito.mockStatic() on a class having a long static method. 2. 3. What is the expected output? What do you see instead? What version of the product are you using? On what operating system? Using latest version(1.9.5) of powermockito on Windows 7 Enterprise. Using Rad to run the test cases. Please provide any additional information below. I was trying to mock a static method of a class. It contains a static method with more that 600 lines.while invoking PowerMockito.mockStatic() on this class got the following exception:- Noticed that when i reduce the number of lines in the method, the static mocking has been successful.
Please let me know a workaround for this problem. If needed I can share the Test class and the class to be tested.
java.lang.IllegalStateException: Failed to transform class with name com.acs.enterprise.mmis.provider.enrollment.view.helper.ProviderEnrollmentHelper. Reason: null
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:214)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:144)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:67)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:660)
	at java.lang.Class.forNameImpl(Native Method)
	at java.lang.Class.forName(Class.java:176)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:126)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:137)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:61)
	at sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:402)
	at sun.reflect.annotation.AnnotationParser.parseClassValue(AnnotationParser.java:383)
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:685)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:492)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:318)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:253)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:100)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:82)
	at java.lang.Class.getDeclaredAnnotations(Class.java:1685)
	at java.lang.Class.getAnnotations(Class.java:1641)
	at java.lang.Class.getAnnotation(Class.java:1621)
	at org.junit.internal.MethodSorter.getDeclaredMethods(MethodSorter.java:52)
	at org.junit.internal.runners.TestClass.getAnnotatedMethods(TestClass.java:45)
	at org.junit.internal.runners.MethodValidator.validateTestMethods(MethodValidator.java:71)
	at org.junit.internal.runners.MethodValidator.validateStaticMethods(MethodValidator.java:44)
	at org.junit.internal.runners.MethodValidator.validateMethodsForDefaultRunner(MethodValidator.java:50)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.validate(PowerMockJUnit44RunnerDelegateImpl.java:108)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.<init>(PowerMockJUnit44RunnerDelegateImpl.java:70)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl.<init>(PowerMockJUnit47RunnerDelegateImpl.java:42)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit49RunnerDelegateImpl.<init>(PowerMockJUnit49RunnerDelegateImpl.java:25)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:80)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:57)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:539)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:149)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:39)
	at org.powermock.tests.utils.impl.AbstractTestSuiteChunkerImpl.createTestDelegators(AbstractTestSuiteChunkerImpl.java:217)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.<init>(JUnit4TestSuiteChunkerImpl.java:59)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.<init>(AbstractCommonPowerMockRunner.java:32)
	at org.powermock.modules.junit4.PowerMockRunner.<init>(PowerMockRunner.java:33)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:80)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:57)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:539)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:29)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:21)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:26)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.<init>(JUnit4TestReference.java:32)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestClassReference.<init>(JUnit4TestClassReference.java:25)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:41)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:31)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.lang.NullPointerException
	at javassist.bytecode.stackmap.Tracer.checkParamTypes(Tracer.java:902)
	at javassist.bytecode.stackmap.Tracer.doInvokeMethod(Tracer.java:801)
	at javassist.bytecode.stackmap.Tracer.doOpcode148_201(Tracer.java:595)
	at javassist.bytecode.stackmap.Tracer.doOpcode(Tracer.java:81)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:187)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.stackmap.MapMaker.make(MapMaker.java:199)
	at javassist.bytecode.st...

_Original issue: http://code.google.com/p/powermock/issues/detail?id=503_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on August 24, 2014 22:39:08_

I suppose that's an issue with Javassist. Please add it to the javassist issue tracker.

**Status:** Accepted
