### ISSUE TITLE
Test with PowerMock fails when run on java 1.7.0_65 

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#524]
_From [begul1234](https://code.google.com/u/begul1234/) on July 17, 2014 10:28:21_

What steps will reproduce the problem? - Have a unit test annotated with @RunWith(PowerMockRunner.class) @PrepareForTest(MyEndpoint.class)
   and use mockStatic(MyEndpoint.class); in the setUp method of the test. What is the expected output? What do you see instead? I would expect that the test runs normally and without error as it did before with older java versions (1.7.0_55 works).

Instead the test fails with the following stacktrace:
java.lang.VerifyError: Bad \<init> method call from inside of a branch Exception Details:   Location:     net/sample/api/endpoint/AbstractB2CJaxRsEndpoint.<init>(Lorg/powermock/core/IndicateReloadClass;)V @41: invokespecial   Reason:     Error exists in the bytecode   Bytecode:     0000000: 2a2b 4e4d 1210 b800 1604 bd00 0d59 032d     0000010: 5313 0126 b800 1bb8 0021 3a05 1905 b200     0000020: 25a5 000e 2a01 c000 27b7 002a a700 0a2c     0000030: 2db7 002a 0157 b1                         Stackmap Table:     full_frame(@47,{UninitializedThis,Object[#39],UninitializedThis,Object[#39],Top,Object[#13]},{})     full_frame(@54,{Object[#2],Object[#39],Object[#2],Object[#39],Top,Object[#13]},{}) 
java.lang.VerifyError: Bad \<init> method call from inside of a branch
Exception Details:
  Location:
    net/sample/api/endpoint/AbstractB2CJaxRsEndpoint.<init>(Lorg/powermock/core/IndicateReloadClass;)V @41: invokespecial
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: 2a2b 4e4d 1210 b800 1604 bd00 0d59 032d
    0000010: 5313 0126 b800 1bb8 0021 3a05 1905 b200
    0000020: 25a5 000e 2a01 c000 27b7 002a a700 0a2c
    0000030: 2db7 002a 0157 b1                      
  Stackmap Table:
    full_frame(@47,{UninitializedThis,Object[#39],UninitializedThis,Object[#39],Top,Object[#13]},{})
    full_frame(@54,{Object[#2],Object[#39],Object[#2],Object[#39],Top,Object[#13]},{})

    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2532)
    at java.lang.Class.getDeclaredConstructors(Class.java:1901)
    at org.mockito.internal.creation.jmock.ClassImposterizer.setConstructorsAccessible(ClassImposterizer.java:75)
    at org.mockito.internal.creation.jmock.ClassImposterizer.imposterise(ClassImposterizer.java:70)
    at org.powermock.api.mockito.internal.mockcreation.MockCreator.createMethodInvocationControl(MockCreator.java:110)
    at org.powermock.api.mockito.internal.mockcreation.MockCreator.mock(MockCreator.java:60)
    at org.powermock.api.mockito.PowerMockito.mockStatic(PowerMockito.java:70)
    at net.sample.api.endpoint.contacting.communication.peer.CommunicationTest.setUp(CommunicationTest.java:82)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.internal.runners.MethodRoadie.runBefores(MethodRoadie.java:132)
    at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:95)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:296)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit49RunnerDelegateImpl$PowerMockJUnit49MethodRunner.executeTestInSuper(PowerMockJUnit49RunnerDelegateImpl.java:116)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit49RunnerDelegateImpl$PowerMockJUnit49MethodRunner.executeTest(PowerMockJUnit49RunnerDelegateImpl.java:77)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:284)
    at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:86)
    at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:49)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:209)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:148)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:122)
    at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:33)
    at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:45)
    at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:120)
    at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:101)
    at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
    at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:53)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:249)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:142)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:113)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:104)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) What version of the product are you using? On what operating system? PowerMock 1.5.5 on MacOSX or Linux Please provide any additional information below.

_Original issue: http://code.google.com/p/powermock/issues/detail?id=504_

**Comment by johanhaleby** [comment]
_From [LifusExi...@gmail.com](https://code.google.com/u/111764941229124992958/) on July 25, 2014 03:27:38_

Most likely, it's a JDK bug

Root cause(?): https://bugs.openjdk.java.net/browse/JDK-8051012 Related issues: https://jira.codehaus.org/browse/GROOVY-6951?page=com.atlassian.jira.plugin.system.issuetabpanels:all-tabpanel http://zeroturnaround.com/forums/topic/verifyerror-bad-method-call-from-inside-of-a-branch/

**Comment by johanhaleby** [comment]
_From [JDever...@gmail.com](https://code.google.com/u/111441683534736501403/) on August 13, 2014 13:34:22_

I believe the original bug was patched in 1.7's 67 patch, but the bug still seems to exist with PowerMock...

**Comment by johanhaleby** [comment]
_From [awo...@fedora-commons.org](https://code.google.com/u/115681902859110929229/) on August 19, 2014 06:29:08_

This is a show-stopper for our use of PowerMock. Are there plans on the horizon? or is the recommendation to move to a different test library?

**Comment by johanhaleby** [comment]
_From [epa...@gmail.com](https://code.google.com/u/107745306852665710942/) on August 19, 2014 13:03:07_

I wonder if PowerMock needs to be rebuilt with a newer JDK version.

**Comment by johanhaleby** [comment]
_From [thinking...@gmail.com](https://code.google.com/u/117686790552813267707/) on August 20, 2014 14:47:48_

There is a work-around for this issue: run the junit tests with a '-noverify' jvm argument

**Comment by johanhaleby** [comment]
_From [lauri.va...@gmail.com](https://code.google.com/u/106930242142434409595/) on August 21, 2014 05:21:03_

I added a comment to https://issues.jboss.org/browse/JASSIST-228 that suggest another workaround for this problem. (unfortunatelly they are maintaining their server currently and i cannot quote myself from there)

However, if you still feel that you need to have your java class file verifyed (hence -noverify is out for you) you can use -XX:-UseSplitVerifier option when you start your tests.

And if you are like me, and start your tests with maven, then you need to add something similar to your pom.xml
    \<build>
        \<plugins>
            \<plugin>
                \<groupId>org.apache.maven.plugins</groupId>
                \<artifactId>maven-surefire-plugin</artifactId>
                \<version>2.10</version>
                \<configuration>
                    \<argLine>-XX:-UseSplitVerifier</argLine>
                \</configuration>
            \</plugin>
        \</plugins>
    \</build>

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on August 24, 2014 23:00:22_

I'm not sure if there's anything I can do from the PowerMock side to improve this?

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on August 24, 2014 23:01:22_

Issue 505 has been merged into this issue.

**Comment by johanhaleby** [comment]
_From [f...@noidea.de](https://code.google.com/u/104544426144312995691/) on August 27, 2014 06:06:57_

You must avoid branching before a super call.

You could change the ExprEditor in the MainMockTransformer Line 269-273 to use no branching. Or use branching only if really needed and verify it. (I don't know how to call the JVM verifier, using CtClasses .toClass().getDeclaredConstructors() would throw a Exception) From thereon you could show a nice error message explaining the details.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on August 27, 2014 10:34:49_

Could you help out and provide a pull request for this? That would be great.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on August 28, 2014 04:39:32_

Hmm I really would like to solve this but I'm not sure how to solve this without branching..

**Comment by johanhaleby** [comment]
_From [f...@noidea.de](https://code.google.com/u/104544426144312995691/) on August 28, 2014 05:18:03_

Just disable constructor mocking if 

		CtClass ctClass = ClassPool.getDefault().makeClass("TestForBadOperandWhenInvokingInit");

		//		java.lang.VerifyError: Bad operand type when invoking \<init>
		ctClass.addConstructor(CtNewConstructor.make(new CtClass[0], new CtClass[0], "{if (1 != 2){ super();}}", ctClass));
		final Class<?> clazz = ctClass.toClass();

		clazz.getDeclaredConstructors();

throws an Exception and log it out. There is already a fix commited for the next JDK version, so this bug should not haunt us for long.

**Comment by johanhaleby** [comment]
_From [matt.mil...@gmail.com](https://code.google.com/u/110683981023740348533/) on August 28, 2014 22:07:07_

I don't believe that this is a bug in the JDK. Oracle has decided to make their byte code verification rules stricter-details here http://www.takipiblog.com/oracles-latest-java-8-update-broke-your-tools-how-did-it-happen/ .

I also don't believe that there will be a fix in future versions of java as it is not a bug it is a feature. Oracle Java 8u20 still has this "feature".

The suggestion to use the SplitVerifier may work in Java 7 but I believe that the SplitVerifier has been removed in java 8. There is the option to turn off verification completely for tests (ie -noverify) but the confidence is lost that your code will work in production without this option and I don't think disabling bytecode verification in production is a great idea.

The OpenJDK team may of reverted the change but I don't think oracle will be so nice :)

The only real option is to fix the offending PowerMock class.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on August 28, 2014 22:22:57_

If you're right we need to figure out a way to fix it. How it works now is that before the call to super the MockGateway is invoked to decide whether or not to call the super method or call another constructor (generated by PowerMock). This is used for constructor suppression (suppress(constructor(X.class))) if I remember it correctly. All method invocations, field invocations etc works in the same way (they all ask the MockGateway if they should continue or replace the call with a mock). For constructors I'm not sure how to solve this unless we insert this if statement (which I believe is the cause of the error) before the super call in the constructor byte-code. If you have any ideas for a workaround I would be really happy. 

A really ugly work-around would be to let the user somehow configure PowerMock not to byte-code manipulate constructors (if you don't need to use this functionality). That way I assume that some errors can go away but PowerMock will be left in a degraded state. Not sure if I want to go down this route.. However I've been thinking about implementing something like this before to speed up the byte-code manipulation (such as turing off field interception which is quite slow and not used very often afaik).

**Status:** Accepted

**Comment by johanhaleby** [comment]
_From [jam...@gmail.com](https://code.google.com/u/105234704620134800598/) on September 16, 2014 03:41:59_

Hey guys, any progress on this?
It is affecting us too.

Thanks.

**Comment by johanhaleby** [comment]
_From [BinisBe...@gmail.com](https://code.google.com/u/110129984734501862367/) on September 19, 2014 05:25:47_

ctClass.addConstructor(CtNewConstructor.make(new CtClass[0], new CtClass[0], "{if (1 != 2){ super();}}", ctClass));

Looks like this line makes new constructor with code. Right?

{if (1 != 2){ super();}}". Not sure why 1 != 2 check is needed but this is what is causing the problem. the first thing you have to invoke in the constructor is the super constructor. So probably it should be something like this {super(); if (1 != 2) {}}

**Comment by johanhaleby** [comment]
_From [f...@noidea.de](https://code.google.com/u/104544426144312995691/) on September 19, 2014 05:29:50_

This might be the simplified version you could use to reproduce the error.. 
The original code is:

code.append("if(value == ").append(MockGateway.class.getName()).append(".PROCEED) {");
code.append("	$_ = $proceed($$);");
code.append("} else {");
code.append("	$_ = ").append(getCorrectReturnValueType(returnTypeAsCtClass)).append(";");
code.append("}}");

It is there to decide if another constructor should be called.. that code must be changed to call super() first. YOu would loose the ability of on demand constructor mocking.. or you would have to replace the mocked constructors during mocking.

**Comment by johanhaleby** [comment]
_From [matt.mil...@gmail.com](https://code.google.com/u/110683981023740348533/) on September 23, 2014 18:30:00_

So I had a chat to some of of the developers here and I've learnt that the Oracle JDK is built on top of OpenJDK so any fixes made in OpenJDK will find their way through to the Oracle JDK. Therefore this "feature" has been reverted as per this issue https://bugs.openjdk.java.net/browse/JDK-8051012 and we just need to wait for the relevant version to be released. For java 8 it looks like 8u20 b31 has it fixed, the latest public release is for 8u20 is b26 so the fix hasn't been released yet. I couldn't find a release date for build 31 anywhere.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 23, 2014 22:10:50_

Thanks a lot for sharing this.

**Comment by johanhaleby** [comment]
_From [jrh...@gmail.com](https://code.google.com/u/110694536384347452794/) on October 14, 2014 13:48:02_

As an FYI: this appears to no longer be an issue on Oracle JDK7u72.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 14, 2014 22:12:09_

Thanks, good to know

**Comment by johanhaleby** [comment]
_From [jeff.pa...@gmail.com](https://code.google.com/u/110524760043098435677/) on October 15, 2014 15:43:35_

I'm still getting it with Oracle MacOS, java full version "1.7.0_72-b14"

**Comment by johanhaleby** [comment]
_From [jrh...@gmail.com](https://code.google.com/u/110694536384347452794/) on October 16, 2014 06:13:04_

That's weird - same OS and same build and update version here. I'm not sure what the difference is there.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 16, 2014 06:40:35_

Perhaps you have different test scenarios? It works in some cases but fails in others?! But then it could be another issue altogether?

**Comment by johanhaleby** [comment]
_From [emla...@gmail.com](https://code.google.com/u/114133180998616662731/) on October 16, 2014 15:09:31_

Oracle released 8U25 on October 14th and this jdk fixed this error for me.

**Comment by johanhaleby** [comment]
_From [Cameron...@gmail.com](https://code.google.com/u/100855158659276862866/) on October 23, 2014 14:21:26_

Simply to give another voice, installing jdk1.7.0_72 fixed this for me as well.

**Comment by johanhaleby** [comment]
_From [japear...@agiledigital.com.au](https://code.google.com/u/106993804961547904027/) on November 06, 2014 22:07:34_

For reference, the bug that is apparently fixed is: http://bugs.java.com/view_bug.do?bug_id=8051012 It is referenced from this page: http://www.oracle.com/technetwork/java/javase/2col/7u72-bugfixes-2298229.html I presume the bug isn't marked as resolved, because update 72, is some weird sort of halfway release, where Oracle recommends you use update 71 unless you need fixes from 72: http://www.oracle.com/technetwork/java/javase/7u72-relnotes-2296190.html

**Comment by johanhaleby** [comment]
_From [rubenale...@gmail.com](https://code.google.com/u/115919830955751925820/) on November 17, 2014 16:02:48_

This issue is present for me I tried 72.
It works with the UseSplitVerifier option. But, that will be deprecated: https://code.google.com/p/powermock/issues/detail?id=504 So, unless this is fixed, will have to migrate to a different framework. I'll take a look to the code later on to see if there is something I can help with.

**Comment by johanhaleby** [comment]
_From [iamascr...@gmail.com](https://code.google.com/u/101255884936038115663/) on January 04, 2015 15:41:14_

fwiw - I was experiencing the issue on 7u71, but it is ok on 7u72.

**Comment by johanhaleby** [comment]
_From [kguel...@gmail.com](https://code.google.com/u/108490384398856647879/) on January 12, 2015 03:37:31_

7u72 fixed this for me.

**Comment by johanhaleby** [comment]
_From [q...@cyngn.com](https://code.google.com/u/103598819907142777392/) on January 20, 2015 10:41:18_

for Java SE 8u20
java version "1.8.0_20"
Java(TM) SE Runtime Environment (build 1.8.0_20-b26)

add the following to pom.xml
 \<plugin>
                \<groupId>org.apache.maven.plugins</groupId>
                \<artifactId>maven-surefire-plugin</artifactId>
                \<version>2.12.4</version>
                \<configuration>
                    \<argLine>-noverify</argLine>
                \</configuration>
            \</plugin>


It should work if you are using Java SE 8u25

java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

**Comment by johanhaleby** [comment]
_From [chirag.o...@gmail.com](https://code.google.com/u/112535738277772410972/) on February 23, 2015 23:14:33_

For Java SE 8u25, is it working other except option -noverify ?

**Comment by johanhaleby** [comment]
_From [f...@noidea.de](https://code.google.com/u/104544426144312995691/) on May 08, 2015 00:47:57_

I would close this issue as it is either fixed with jdk 7u72, jdk 8u25 or can be circumvented with -noverify.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 08, 2015 02:26:01_

Ok I'm closing it for now.

**Status:** WontFix
