### ISSUE TITLE
Incompatibility with mockito 1.10.9 and 1.10.10

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#544]
_From [tibokr...@googlemail.com](https://code.google.com/u/107064315374216084770/) on October 30, 2014 17:05:48_

I used mockito 1.10.8 with powermock-api-mockito:1.5.6, and it worked fine.

I tried upgrading to mockito 1.10.9 and 1.10.10, but I got:

java.lang.IllegalAccessError: org/mockito/internal/creation/cglib/CGLIBHacker
        at org.mockito.internal.creation.MethodInterceptorFilter.<init>(MethodInterceptorFilter.java:27)
        at org.powermock.api.mockito.internal.mockcreation.PowerMockMethodInterceptorFilter.<init>(PowerMockMethodInterceptorFilter.java:18)
        at org.powermock.api.mockito.internal.mockcreation.MockCreator.createMethodInvocationControl(MockCreator.java:109)
        at org.powermock.api.mockito.internal.mockcreation.MockCreator.mock(MockCreator.java:60)
        at org.powermock.api.mockito.PowerMockito.mock(PowerMockito.java:143)

and also

java.lang.NoClassDefFoundError: Could not initialize class org.mockito.internal.creation.jmock.ClassImposterizer
        at org.mockito.internal.creation.CglibMockMaker.createMock(CglibMockMaker.java:23)
        at org.powermock.api.mockito.internal.mockmaker.PowerMockMaker.createMock(PowerMockMaker.java:43)
        at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:32)
        at org.mockito.internal.MockitoCore.mock(MockitoCore.java:59)
        at org.mockito.Mockito.mock(Mockito.java:1258)

I assume you don't need an example to reproduce, any existing unit tests probably break as well.

_Original issue: http://code.google.com/p/powermock/issues/detail?id=524_

**Comment by johanhaleby** [comment]
_From [lobsterl...@gmail.com](https://code.google.com/u/116501746944533352111/) on December 22, 2014 10:11:47_

1.10.9 or 1.10.10 are no longer available in Central, so I jumped from 1.10.8 to 1.10.16 or 1.10.17 and have the following problem. powermock-api-mockito 1.6.0, junit 4.11.

java.lang.NoClassDefFoundError: org/mockito/internal/creation/CglibMockMaker
	at org.powermock.api.mockito.internal.mockmaker.PowerMockMaker.<init>(PowerMockMaker.java:40)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at java.lang.Class.newInstance(Class.java:438)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadImpl(PluginLoader.java:61)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:24)
	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:12)
	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:11)
	at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:24)
	at org.mockito.internal.configuration.injection.scanner.MockScanner.<init>(MockScanner.java:22)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.injectMocks(InjectingAnnotationEngine.java:96)
	at org.powermock.api.mockito.internal.configuration.PowerMockitoInjectingAnnotationEngine.process(PowerMockitoInjectingAnnotationEngine.java:35)
	at org.powermock.api.extension.listener.AnnotationEnabler.injectSpiesAndInjectToSetters(AnnotationEnabler.java:60)
	at org.powermock.api.extension.listener.AnnotationEnabler.beforeTestMethod(AnnotationEnabler.java:55)
	at org.powermock.tests.utils.impl.PowerMockTestNotifierImpl.notifyBeforeTestMethod(PowerMockTestNotifierImpl.java:90)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:292)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:127)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:282)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:86)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:49)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:207)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:146)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:120)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:33)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:45)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:122)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:106)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.ClassNotFoundException: org.mockito.internal.creation.CglibMockMaker
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:178)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 44 more
Caused by: java.lang.ClassNotFoundException: org.mockito.internal.creation.CglibMockMaker
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:178)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 44 more

**Comment by johanhaleby** [comment]
_From [michael....@gmail.com](https://code.google.com/u/107878492561907402444/) on January 05, 2015 03:58:40_

any news on this issue? just upgraded from mockito 1.9.5 to 1.10.19 and powermock 1.5 to 1.6.1 (for junit 4.12) and getting the same error:

java.lang.NoClassDefFoundError: org/mockito/internal/creation/CglibMockMaker
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.powermock.api.mockito.internal.mockmaker.PowerMockMaker.<init>(PowerMockMaker.java:40)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:379)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadImpl(PluginLoader.java:61)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:24)
	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:12)
	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:11)
	at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:24)
	at org.mockito.internal.stubbing.defaultanswers.ReturnsEmptyValues.<init>(ReturnsEmptyValues.java:58)
	at org.mockito.internal.stubbing.defaultanswers.ReturnsMoreEmptyValues.<init>(ReturnsMoreEmptyValues.java:51)
	at org.mockito.internal.stubbing.defaultanswers.ReturnsSmartNulls.<init>(ReturnsSmartNulls.java:40)
	at org.mockito.Answers.<clinit>(Answers.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at java.lang.Class.getEnumConstantsShared(Class.java:3128)
	at java.lang.Class.enumConstantDirectory(Class.java:3149)
	at java.lang.Enum.valueOf(Enum.java:231)
	at sun.reflect.annotation.AnnotationParser.parseEnumValue(AnnotationParser.java:475)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:340)
	at java.lang.reflect.Method.getDefaultValue(Method.java:741)
	at sun.reflect.annotation.AnnotationType.<init>(AnnotationType.java:128)
	at sun.reflect.annotation.AnnotationType.getInstance(AnnotationType.java:85)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:263)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:117)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:70)
	at java.lang.reflect.Field.declaredAnnotations(Field.java:1128)
	at java.lang.reflect.Field.getDeclaredAnnotations(Field.java:1121)
	at java.lang.reflect.AccessibleObject.getAnnotations(AccessibleObject.java:196)
	at org.junit.runners.model.FrameworkField.getAnnotations(FrameworkField.java:31)
	at org.junit.runners.model.TestClass.addToAnnotationLists(TestClass.java:84)
	at org.junit.runners.model.TestClass.scanAnnotatedMembers(TestClass.java:71)
	at org.junit.runners.model.TestClass.<init>(TestClass.java:57)
	at org.junit.runners.ParentRunner.createTestClass(ParentRunner.java:88)
	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:83)
	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:65)
	at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl$1.<init>(JUnit45AndHigherRunnerImpl.java:23)
	at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.<init>(JUnit45AndHigherRunnerImpl.java:23)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.mockito.internal.runners.util.RunnerProvider.newInstance(RunnerProvider.java:39)
	at org.mockito.internal.runners.RunnerFactory.create(RunnerFactory.java:28)
	at org.mockito.runners.MockitoJUnitRunner.<init>(MockitoJUnitRunner.java:57)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:262)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:158)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:86)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)

**Comment by johanhaleby** [comment]
_From [michael....@gmail.com](https://code.google.com/u/107214710339689336387/) on January 08, 2015 04:05:49_

I have the same issue. Compatibility with all Versions of Mockito >=1.10.9 seems to be broken.

**Comment by johanhaleby** [comment]
_From [marcos.p...@edulify.com](https://code.google.com/u/112014879472532076453/) on January 13, 2015 10:28:10_

Same thing here. The last mockito version that properly works with powermock is 1.10.8.

**Comment by johanhaleby** [comment]
_From [bokor.an...@gmail.com](https://code.google.com/u/104892756965298686198/) on January 27, 2015 02:44:25_

Hi,

Putting mockito-core into the pom.xml solved for me.
Mockito core uses different CGLib version or something like that.
So put mockito-core before powermock and see the result.
It is good for temporary workaround.

**Comment by johanhaleby** [comment]
_From [jrh...@gmail.com](https://code.google.com/u/110694536384347452794/) on January 27, 2015 06:19:48_

I use mockito-core in my projects, but I experienced this problem, too. What version of mockito-core are you using?

**Comment by johanhaleby** [comment]
_From [brice.du...@gmail.com](https://code.google.com/u/109451107923311766648/) on January 29, 2015 02:53:10_

Nothing to do with upgraded CGLIB. The thing is that mockito changed / cleaned some of it's internal. In order to better isolate CGLIB stuff, that includes renaming, changing packages, using package visibility, etc.

PowerMock rely on a lot of mockito internals, with recent refactoring on Mockito side I have the feeling that PowerMock will have to repackage mockito, at least the classes that powermock uses.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 30, 2015 00:32:36_

Brice has submitted a pull request that includes some of the Mocktio internals. I accept it for now as a workaround but a better solution is probably required otherwise PowerMock will move away from original Mockito too much.

**Status:** Fixed

**Comment by johanhaleby** [comment]
_From [konrad.j...@acrolinx.com](https://code.google.com/u/109697452943845442647/) on February 20, 2015 07:34:00_

I'm confused this tickets state was set to "Fixed". I still have to use mockito-1.10.8. Any official progress on this?

**Comment by johanhaleby** [comment]
_From [chunkia...@gmail.com](https://code.google.com/u/107008145228952135689/) on February 25, 2015 00:31:30_

Hi, I am facing the same issue. Just voicing out again, I don't think the workaround is right. Any comments on reopening this issue

**Comment by johanhaleby** [comment]
_From [babbupan...@gmail.com](https://code.google.com/u/101228483922660902096/) on February 26, 2015 17:54:23_

I face similar issues, adding mockito-core to POM doesn't help either.

**Comment by johanhaleby** [comment]
_From [pascal.g...@gmail.com](https://code.google.com/u/116517631323802657057/) on February 27, 2015 08:46:33_

I experience the same issue. Any news on this ?

**Comment by johanhaleby** [comment]
_From [marcus.f...@gmail.com](https://code.google.com/u/114580180880165340222/) on March 16, 2015 04:57:11_

This issue is still not fixed. Who is responsible to correct the status from fixed to open?

**Comment by johanhaleby** [comment]
_From [lrichard...@gmail.com](https://code.google.com/u/100556472637838911160/) on March 16, 2015 07:45:55_

Apparently, with powermock 1.6.2, you need to use a version of mockito more recent than 1.10.8. It seems OK with mockito 1.10.19 for instance.

**Comment by johanhaleby** [comment]
_From [tibokr...@googlemail.com](https://code.google.com/u/107064315374216084770/) on March 16, 2015 09:39:24_

powermock 1.6.2 with mockito 1.10.19 works for me, too.
As a side-note, 1.6.2 does not appear here: http://mvnrepository.com/artifact/org.powermock

**Comment by johanhaleby** [comment]
_From [jrh...@gmail.com](https://code.google.com/u/110694536384347452794/) on March 26, 2015 08:31:10_

\> As a side-note, 1.6.2 does not appear here: http://mvnrepository.com/artifact/org.powermock May have just taken it a bit for it to catch up. I see 1.6.2 now.

**Comment by johanhaleby** [comment]
_From [orbf...@gmail.com](https://code.google.com/u/117717982879348527659/) on March 29, 2015 14:09:37_

Will this be fixed with 2.0, or do we still have to use the mockito-core/PowerMock workarounds? I really need the Mockito rule, but I can't upgrade PowerMock due to EasyMock dependencies.
