### ISSUE TITLE
Failed to transform class with name com.ibm.ecm.extension.PluginServiceCallbacks. Reason: com.ibm.mm.sdk.server.DKDatastoreICM

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#546]
_From [gdel...@gmail.com](https://code.google.com/u/108881632138955056358/) on November 27, 2014 10:23:14_

What steps will reproduce the problem? 1.Preparing a class @PrepareForTest(PluginServiceCallbacks.class) What is the expected output? What do you see instead? Expect it to prepare without exception. Instead fail with 
java.lang.IllegalStateException: Failed to transform class with name...
I tried with a PowerMock.mock and prepare the class since I has issue with Mockito, hoping it could work :) What version of the product are you using? On what operating system? powermockito 1.5.6 - Mockito 1.9.5 - Window 7 - JDK IBM 32bits Please provide any additional information below. This is a simple class, so I also tried with @Mock from Mockito without preparing the class, I know it doesn't really concern you but I thought it could help though. When mocking with Mockito, I get a ClassNotFoundException (see stack below. It makes sense because this is a plug-in running in a J2EE environment with some other dependencies provided. However for the test I just want to mock the class for one method so I though the dependency wouldn't be a problem for a mock.

Maybe I can't mock such a class or did something wrong? Thanks a lot, PowerMock helps us a lot!

Stack trace for PowerMockito :
java.lang.IllegalStateException: Failed to transform class with name com.ibm.ecm.extension.PluginServiceCallbacks. Reason: com.ibm.mm.sdk.server.DKDatastoreICM
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:256)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:180)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:643)
	at java.lang.Class.getDeclaredFieldsImpl(Native Method)
	at java.lang.Class.getDeclaredFields(Class.java:609)
	at org.powermock.reflect.internal.WhiteboxImpl.findAllFieldsUsingStrategy(WhiteboxImpl.java:484)
	at org.powermock.reflect.internal.WhiteboxImpl.getFieldsAnnotatedWith(WhiteboxImpl.java:2176)
	at org.powermock.reflect.internal.WhiteboxImpl.getFieldsAnnotatedWith(WhiteboxImpl.java:2161)
	at org.powermock.reflect.Whitebox.getFieldsAnnotatedWith(Whitebox.java:568)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:76)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:282)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:86)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:49)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:207)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:146)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:120)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:33)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:45)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:122)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:104)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:53)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: javassist.NotFoundException: com.ibm.mm.sdk.server.DKDatastoreICM
	at javassist.ClassPool.get(ClassPool.java:450)
	at javassist.bytecode.Descriptor.toCtClass(Descriptor.java:592)
	at javassist.bytecode.Descriptor.getReturnType(Descriptor.java:489)
	at javassist.CtBehavior.getReturnType0(CtBehavior.java:306)
	at javassist.CtMethod.getReturnType(CtMethod.java:217)
	at org.powermock.core.transformers.impl.MainMockTransformer.modifyMethod(MainMockTransformer.java:172)
	at org.powermock.core.transformers.impl.MainMockTransformer.allowMockingOfStaticAndFinalAndNativeMethods(MainMockTransformer.java:142)
	at org.powermock.core.transformers.impl.MainMockTransformer.transform(MainMockTransformer.java:65)
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:251)
	... 28 more

Stack trace for Mockito (@Mock)
java.lang.NoClassDefFoundError: com.ibm.ecm.util.DocumentContent
	at java.lang.J9VMInternals.verifyImpl(Native Method)
	at java.lang.J9VMInternals.verify(J9VMInternals.java:73)
	at java.lang.J9VMInternals.prepare(J9VMInternals.java:459)
	at java.lang.Class.getDeclaredConstructors(Class.java:535)
	at org.mockito.internal.creation.jmock.ClassImposterizer.setConstructorsAccessible(ClassImposterizer.java:75)
	at org.mockito.internal.creation.jmock.ClassImposterizer.imposterise(ClassImposterizer.java:70)
	at org.powermock.api.mockito.internal.mockcreation.MockCreator.createMethodInvocationControl(MockCreator.java:111)
	at org.powermock.api.mockito.internal.mockcreation.MockCreator.mock(MockCreator.java:60)
	at org.powermock.api.mockito.PowerMockito.mock(PowerMockito.java:203)
	at org.powermock.api.extension.listener.AnnotationEnabler.standardInject(AnnotationEnabler.java:106)
	at org.powermock.api.extension.listener.AnnotationEnabler.beforeTestMethod(AnnotationEnabler.java:54)
	at org.powermock.tests.utils.impl.PowerMockTestNotifierImpl.notifyBeforeTestMethod(PowerMockTestNotifierImpl.java:90)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:292)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:127)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:282)
	at org.junit.interna...

_Original issue: http://code.google.com/p/powermock/issues/detail?id=526_

**Comment by johanhaleby** [comment]
_From [gdel...@gmail.com](https://code.google.com/u/108881632138955056358/) on November 28, 2014 05:11:15_

Hi again,

actually this is not related to Mockito or PowerMock, I describe the problem here and gave a work around in the Mockito forum if it can help someone: https://github.com/mockito/mockito/issues/127 This issue can be close :)
