### ISSUE TITLE
Tests Classes cannot inherit another class if we want to use @PowerMockRunnerDelegate with a runner that extends ParentRunner

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#550]
_From [Alex.bel...@gmail.com](https://code.google.com/u/111596358441680892977/) on December 04, 2014 10:33:27_

What steps will reproduce the problem? 1.Create a test class (MyTest.java) that inherits another one (MyAbstractTestClass.java)
2.On MyTest.java add the annotations @RunWith(PowerMockRunner.class)and @PowerMockRunnerDelegate(SpringJUnit4ClassRunner.class)
3.Create a test method in MyTest.java (the method may be empty)
4.Run the test What is the expected output? What do you see instead? The expected output is a successfull run, but instead it fails with an Exception : java.lang.IllegalArgumentException: Test class can only have one constructor What version of the product are you using? On what operating system? PowerMock 1.6.0
Mockito 1.10.8
Junit 4.11
Spring 3.1.4
Windows 7 64bits Please provide any additional information below. When a testClass inherits another one PowerMock adds a new constructor that takes a IndicateReloadClass as parameter. But when we try to instanciate a new SpringJUnit4ClassRunner, which extends org.junit.runners.ParentRunner, it tries to build a new MyTest, which now has 2 constructors and fails.

**Attachment:** [powermock-delegateRunner.7z](http://code.google.com/p/powermock/issues/detail?id=530)

_Original issue: http://code.google.com/p/powermock/issues/detail?id=530_

**Comment by johanhaleby** [comment]
_From [selivar...@gmail.com](https://code.google.com/u/112871058288137163442/) on February 18, 2015 03:19:12_

Any workarounds except of removing base class?

**Comment by 7robertodantas** [comment]
I am also facing this issue. Trying to run 
```java
@RunWith(PowerMockRunner.class)
@PowerMockRunnerDelegate(Parameterized.class)
public class SomeTest extends TestCommon { }
```

```
java.lang.IllegalArgumentException: Test class can only have one constructor
	at org.junit.runners.model.TestClass.<init>(TestClass.java:34)
	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:65)
	at org.junit.runners.Suite.<init>(Suite.java:112)
	at org.junit.runners.Parameterized.<init>(Parameterized.java:129)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.powermock.reflect.internal.WhiteboxImpl.createInstance(WhiteboxImpl.java:1428)
	at org.powermock.reflect.internal.WhiteboxImpl.invokeConstructor(WhiteboxImpl.java:1301)
	at org.powermock.reflect.Whitebox.invokeConstructor(Whitebox.java:497)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner$1.call(DelegatingPowerMockRunner.java:96)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner$1.call(DelegatingPowerMockRunner.java:93)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner.withContextClassLoader(DelegatingPowerMockRunner.java:127)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner.createDelegate(DelegatingPowerMockRunner.java:92)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner.<init>(DelegatingPowerMockRunner.java:60)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:156)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:40)
	at org.powermock.tests.utils.impl.AbstractTestSuiteChunkerImpl.createTestDelegators(AbstractTestSuiteChunkerImpl.java:244)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.<init>(JUnit4TestSuiteChunkerImpl.java:61)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.<init>(AbstractCommonPowerMockRunner.java:32)
	at org.powermock.modules.junit4.PowerMockRunner.<init>(PowerMockRunner.java:34)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:31)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:24)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:29)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:24)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:87)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:73)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:46)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:523)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
```
