### ISSUE TITLE
junit 4.12 throws Field 'fTestClass' was not found in class org.junit.internal.runners.MethodValidator exception

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#551]
_From [cheis...@squareup.com](https://code.google.com/u/116971474335108991911/) on December 05, 2014 22:07:58_

What steps will reproduce the problem? 1. If you use PowerMock with junit 4.12 it will throw a org.powermock.reflect.exceptions.FieldNotFoundException  when the test is starting What version of the product are you using? On what operating system? PowerMock 1.6.0 Please provide any additional information below. More of the stacktrace:

org.powermock.reflect.exceptions.FieldNotFoundException: Field 'fTestClass' was not found in class org.junit.internal.runners.MethodValidator.
	at org.powermock.reflect.internal.WhiteboxImpl.getInternalState(WhiteboxImpl.java:581)
	at org.powermock.reflect.Whitebox.getInternalState(Whitebox.java:308)
	at org.powermock.modules.junit4.internal.impl.testcaseworkaround.PowerMockJUnit4MethodValidator.validateTestMethods(PowerMockJUnit4MethodValidator.java:79)
	at org.powermock.modules.junit4.internal.impl.testcaseworkaround.PowerMockJUnit4MethodValidator.validateInstanceMethods(PowerMockJUnit4MethodValidator.java:49)
	at org.junit.internal.runners.MethodValidator.validateMethodsForDefaultRunner(MethodValidator.java:51)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.validate(PowerMockJUnit44RunnerDelegateImpl.java:108)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.<init>(PowerMockJUnit44RunnerDelegateImpl.java:70)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl.<init>(PowerMockJUnit47RunnerDelegateImpl.java:42)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit49RunnerDelegateImpl.<init>(PowerMockJUnit49RunnerDelegateImpl.java:25)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:156)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:40)
	at org.powermock.tests.utils.impl.AbstractTestSuiteChunkerImpl.createTestDelegators(AbstractTestSuiteChunkerImpl.java:244)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.<init>(JUnit4TestSuiteChunkerImpl.java:61)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.<init>(AbstractCommonPowerMockRunner.java:32)
	at org.powermock.modules.junit4.PowerMockRunner.<init>(PowerMockRunner.java:34)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)

_Original issue: http://code.google.com/p/powermock/issues/detail?id=531_

**Comment by johanhaleby** [comment]
_From [jrh...@gmail.com](https://code.google.com/u/110694536384347452794/) on December 12, 2014 08:15:46_

Looks like the field has been renamed to just "testClass" in JUnit 4.12.

**Comment by johanhaleby** [comment]
_From [nykolas....@gmail.com](https://code.google.com/u/115053539830017864760/) on December 23, 2014 10:31:59_

This should be changed to High priority since there is no way to run PowerMock with JUnit 4.12.

**Comment by johanhaleby** [comment]
_From [nykolas....@gmail.com](https://code.google.com/u/115053539830017864760/) on December 23, 2014 10:35:36_

Also, changing to JUnit 4.11 to workaround this problem causes another problem:
org.powermock.reflect.exceptions.FieldNotFoundException: No instance field named "fAnnotations" could be found in the class hierarchy of org.junit.runner.Description.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 03, 2015 00:12:23_

**Status:** Fixed

**Comment by johanhaleby** [comment]
_From [reshm...@gmail.com](https://code.google.com/u/110929373442646471578/) on February 10, 2015 18:59:01_

In https://github.com/junit-team/junit/releases , the version is 4.12-SNAPSHOT. Hence the fix 
static {
        if(JUnitVersion.isGreaterThanOrEqualTo("4.12")) {
            TEST_CLASS_FIELD = "testClass";
            CLASS_UNDER_TEST_FIELD = "klass";
            ERRORS_FIELD = "errors";
        }
        else {
            TEST_CLASS_FIELD = "fTestClass";
            CLASS_UNDER_TEST_FIELD = "fClass";
            ERRORS_FIELD = "fErrors";
        }
    }
doesn't apply to this version as JUnitVersion.isGreaterThanOrEqualTo("4.12") gives false in this case.

**Comment by johanhaleby** [comment]
_From [roa.sig...@gmail.com](https://code.google.com/u/100154878271891710028/) on March 30, 2015 10:30:40_

Any update?  This is still not fixed with latest version of junit and PowerMock.

**Comment by johanhaleby** [comment]
_From [pundir.f...@gmail.com](https://code.google.com/u/102328562419408271008/) on April 01, 2015 10:35:00_

JUnit 4.12 and powermock 1.6.2 not working. Please provide us fix to move ahead.

**Comment by johanhaleby** [comment]
_From [dandr...@gmail.com](https://code.google.com/u/102322308238166139631/) on April 01, 2015 11:09:19_

Please change the status from 'fixed' this issue still exists with junit-4.12 and Powermock-1.6.2.

**Comment by johanhaleby** [comment]
_From [magicknifeV](https://code.google.com/u/magicknifeV/) on April 15, 2015 01:26:48_

When using powermock-1.6.2 together with junit-4.12 I saw org.powermock.reflect.exceptions.FieldNotFoundException: Field 'fTestClass' was not found in class

**Comment by johanhaleby** [comment]
_From [rogerpack2005](https://code.google.com/u/rogerpack2005/) on June 18, 2015 08:30:17_

this worked with 1.6.1 ?

**Comment by johanhaleby** [comment]
_From [this...@redmart.com](https://code.google.com/u/113409625764630817287/) on July 16, 2015 03:07:28_

Try to use below version and it solved my issue.
junit: 4.11
powermock-api-mockito: 1.5.6
powermock-module-junit4: 1.5.6

**Comment by smithap** [comment]
is there no fix for this?

do we have to use old versions of stuff?

**Comment by johanhaleby** [comment]
Please help out with a pull request

**Comment by smithap** [comment]
Sorry - what is a "pull request" ?

Do you want a failing example?

**Comment by johanhaleby** [comment]
Sure I failing example would also be of help. https://help.github.com/articles/using-pull-requests/

**Comment by llozesdome** [comment]
It's fixed using 

junit: 4.12
powermock-api-mockito: 1.6.1
powermock-module-junit4: 1.6.1

http://stackoverflow.com/questions/26192929/unable-to-run-junit-test-with-powermockrunner

**Comment by mdfarooque** [comment]
I was also facing the same issue and got resolved using below dependency(NOTE: exact version match):
```
<dependency>
	<groupId>junit</groupId>
	<artifactId>junit</artifactId>
	<version>4.12</version>
</dependency>
<dependency>
	<groupId>org.powermock</groupId>
	<artifactId>powermock-api-mockito</artifactId>
	<version>1.6.1</version>
	<scope>test</scope>
</dependency>
<dependency>
	<groupId>org.powermock</groupId>
	<artifactId>powermock-module-junit4</artifactId>
	<version>1.6.1</version>
	<scope>test</scope>
</dependency>
```

Taken help from : [https://stackoverflow.com/questions/26192929/unable-to-run-junit-test-with-powermockrunner](https://stackoverflow.com/questions/26192929/unable-to-run-junit-test-with-powermockrunner
)
