### ISSUE TITLE
Support PowerMock to run Android JUNIT tests

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#559]
_From [shashank.visweswara@gmail.com](https://code.google.com/u/shashank.visweswara@gmail.com/) on February 09, 2015 13:08:01_

What steps will reproduce the problem? 1. Try to mock any Android final class What is the expected output? What do you see instead? Expect the class to get mocked. What version of the product are you using? On what operating system? 1.6.1 on Win7 64 bit and running against Android 4.0 (API 16) Please provide any additional information below. I get the below stack trace. Apparently PowerMock uses javaassist to modify byte codes, however since Android uses DEX code, can PowerMock be modified to work with dexmaker-1.0.jar and dexmaker-mockito-1.0.jar similar to how Mockito does it ?

java.lang.ExceptionInInitializerError
at org.mockito.internal.creation.jmock.ClassImposterizer.createProxyClass(ClassImposterizer.java:96)
at org.mockito.internal.creation.jmock.ClassImposterizer.imposterise(ClassImposterizer.java:60)
at org.powermock.api.mockito.internal.mockcreation.MockCreator.createMethodInvocationControl(MockCreator.java:109)
at org.powermock.api.mockito.internal.mockcreation.MockCreator.mock(MockCreator.java:57)
at org.powermock.api.mockito.PowerMockito.mock(PowerMockito.java:143)
at com.mcafee.endpointassist.test.unit.service.TestBluetoothConnectionListener.setUp(TestBluetoothConnectionListener.java:49)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:190)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:175)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1584)
Caused by: java.lang.VerifyError: org/mockito/cglib/core/ReflectUtils
at org.mockito.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:167)
at org.mockito.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
at org.mockito.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:217)
at org.mockito.cglib.core.KeyFactory$Generator.create(KeyFactory.java:145)
at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:117)
at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:109)
at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:105)
at org.mockito.cglib.proxy.Enhancer.<clinit>(Enhancer.java:70)
... 15 more

_Original issue: http://code.google.com/p/powermock/issues/detail?id=539_

**Comment by johanhaleby** [comment]
_From [john.tw...@gmail.com](https://code.google.com/u/102023276761303206015/) on February 24, 2015 14:01:14_

I think this might be similar, but I'm getting the below exception : 
java.lang.VerifyError: org/mockito/cglib/core/ReflectUtils

which occurs with a failure to setup: dexmaker-1.0.jar and dexmaker-mockito-1.0.jar
However I HAVE set those up properly, because my exissting mockito tests work fine. Power mock seems to be ignoring them.

\---------

java.lang.VerifyError: org/mockito/cglib/core/ReflectUtils
at org.mockito.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:167)
at org.mockito.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
at org.mockito.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:217)
at org.mockito.cglib.core.KeyFactory$Generator.create(KeyFactory.java:145)
at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:117)
at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:109)
at org.mockito.cglib.core.KeyFactory.create(KeyFactory.java:105)
at org.mockito.cglib.proxy.Enhancer.<clinit>(Enhancer.java:70)
at org.mockito.internal.creation.jmock.ClassImposterizer.createProxyClass(ClassImposterizer.java:85)
at org.mockito.internal.creation.jmock.ClassImposterizer.imposterise(ClassImposterizer.java:62)
at org.powermock.api.mockito.internal.mockcreation.MockCreator.createMethodInvocationControl(MockCreator.java:109)
at org.powermock.api.mockito.internal.mockcreation.MockCreator.mock(MockCreator.java:57)
at org.powermock.api.mockito.PowerMockito.mockStatic(PowerMockito.java:70)
at tests.ExampleTest.testRegisterService(ExampleTest.java:186)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)

**Comment by johanhaleby** [comment]
_From [isma...@gmail.com](https://code.google.com/u/116051930856033245541/) on April 13, 2015 13:25:47_

I'm having the exact same issue. 

My tests using Mockito are running fine, but when I try to do a PowerMockito.spy I get an exception:
java.lang.VerifyError: org/mockito/cglib/core/ReflectUtils

Has anyone been able to fix this?

**Comment by imSunny** [comment]
I am also having the same issue.

My existing setup to run Instrumented test cases using Mockito() works fine but when I use Power Mock to mock static method then I am getting the error.

ava.lang.VerifyError: org/mockito/cglib/core/ReflectUtils

Does it mean that Power Mockito can not be used for Instrumented Test cases???

Does any one knows about it?

**Comment by renaudcerrato** [comment]
Any comments about running PowerMock on instrumented tests on Android?

**Comment by n1c086** [comment]
I also have the same problem on Android platform.
When I import Powermock, it automatically imports Javassist, Mockito etc.. and does not import the dexmaker library.
This is the test I run that throws your exception (Mockito is imported from PowerMock, it is a dependency):
`           Mockito m = new Mockito();
            LinkedList mockedList = m.mock(LinkedList.class);
            m.when(mockedList.get(0)).thenReturn("first");
            System.out.println(mockedList.get(0));
            System.out.println(mockedList.get(999));
`
It is the official test.
If I run the same test importing directly Mockito and DexMaker, it works!
Moreover, the error you described before is the same if I use Mockito without Dexmaker.
Is there any news about this?
