### ISSUE TITLE
Powermock affect the Unmarshal convert *.xml to  *.class

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#561]
_From [suiwenf...@gmail.com](https://code.google.com/u/101779847304793642162/) on February 11, 2015 05:46:00_

In my project,i need to convert config.xml to config.class before runtime using cglib. And maybe it is conflict with Powermock.

`My Code`
----Java
@RunWith(PowerMockRunner.class)
@PrepareForTest(ForecastUtils.class)
public class GenerateExcelFileTest {
	
	@Before public void before() throws Exception{
		EasyConfiguration.setConfigHome("config.xml");
		EasyConfiguration.init();
		EnvironmentServices.getInstance().init();
		PowerMockito.mockStatic(ForecastUtils.class);
	}
	
	@Test public void test() throws Exception{
		ProcessContext context = mock(ProcessContext.class);

\---
`Trace`
\---
javax.xml.bind.UnmarshalException: unexpected element (uri:" http://www.retailsolutions.com/Schemas/1.0/config_properties ", local:"domain"). Expected elements are \<{}domain>
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:662)
	at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:258)
	at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:253)
	at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportUnexpectedChildElement(Loader.java:120)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext$DefaultRootLoader.childElement(UnmarshallingContext.java:1063)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:498)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:480)
	at com.sun.xml.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:150)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:218)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:190)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:140)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:123)
	at com.rsi.common.util.EasyConfiguration.init(EasyConfiguration.java:89)
	at com.rsi.pem.service.GenerateExcelFileTest.before(GenerateExcelFileTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.internal.runners.MethodRoadie.runBefores(MethodRoadie.java:133)
	at org.junit.internal.runners.MethodRoadie.runBeforesThenTestThenAfters(MethodRoadie.java:96)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:294)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:127)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:282)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:87)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:50)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:207)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:146)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:120)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:34)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:44)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:122)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:106)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
\---

_Original issue: http://code.google.com/p/powermock/issues/detail?id=541_

**Comment by willitscale** [comment]
I know this is quite an old post, but I've had similar issues which was fixed by having PowerMock ignore various libraries.

I fixed it with the following:
```
@PowerMockIgnore({
        "javax.xml.*",
        "org.xml.*",
        "org.w3c.*"
})
```

You may need to include more excludes as mine has 11 in total, but those are specific to the application I'm working on.

**Comment by Warkeeper** [comment]
> I know this is quite an old post, but I've had similar issues which was fixed by having PowerMock ignore various libraries.
> 
> I fixed it with the following:
> 
> ```
> @PowerMockIgnore({
>         "javax.xml.*",
>         "org.xml.*",
>         "org.w3c.*"
> })
> ```
> 
> You may need to include more excludes as mine has 11 in total, but those are specific to the application I'm working on.

This works in my project which uses JAXBContext to unmarshell XML data. ( I'm using mockito 2.28.2 and powermock 2.0.2 )
Thanks a lot.

**Comment by Macs75** [comment]
> I know this is quite an old post, but I've had similar issues which was fixed by having PowerMock ignore various libraries.
> 
> I fixed it with the following:
> 
> ```
> @PowerMockIgnore({
>         "javax.xml.*",
>         "org.xml.*",
>         "org.w3c.*"
> })
> ```
> 
> You may need to include more excludes as mine has 11 in total, but those are specific to the application I'm working on.



> I know this is quite an old post, but I've had similar issues which was fixed by having PowerMock ignore various libraries.
> 
> I fixed it with the following:
> 
> ```
> @PowerMockIgnore({
>         "javax.xml.*",
>         "org.xml.*",
>         "org.w3c.*"
> })
> ```
> 
> You may need to include more excludes as mine has 11 in total, but those are specific to the application I'm working on.

I was banging my head, for 2 days and this saved me, thank you!
