### ISSUE TITLE
createPartialMock should support private constructors with no arguments

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#57]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 24, 2008 14:56:14_

E.g. MyClass myClassMock = PowerMock.createPartialMock(MyClass.class, new
String[]{"loadMyClassDLL"}, null); 

For ctor:
    private MyClass() {
        this.initialized = false;
        this.connectedDUTs = new HashSet<Byte>();
    }

Generates the following error: 
java.lang.NullPointerException
        at org.powermock.Whitebox.getArgumentsAsString(Whitebox.java:526)
        at
org.powermock.Whitebox.throwExceptionIfConstructorWasNotFound(Whitebox.java:512)
        at
org.powermock.Whitebox.findConstructorOrThrowException(Whitebox.java:499)
        at org.powermock.PowerMock.createPartialMock(PowerMock.java:636)
        at
se.ericsson.eab.sdk.jMyClasswrapper.MyClassTest.connectToDUTFail(MyClassTest.java:358)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at

_Original issue: http://code.google.com/p/powermock/issues/detail?id=37_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 26, 2008 01:00:22_

Added PowerMock API method "createPartialMockAndInvokeDefaultConstructor" that
invokes a default constructor after mock creation (even if it's private).

**Status:** Fixed
