### ISSUE TITLE
Making RobolectricTestRunner a runner delegate for Powermock causes strange errors in argument matching

### ISSUE THREAD

**Issue by aberent** [jayway/powermock#574]
Making RobolectricTestRunner a runner delegate for Powermock causes strange errors in argument matching for PowerMockito.when.

The code:

```java
import static org.mockito.Matchers.anyInt;
import static org.powermock.api.mockito.PowerMockito.doNothing;
import static org.powermock.api.mockito.PowerMockito.spy;
import static org.powermock.api.mockito.PowerMockito.verifyPrivate;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;
import org.powermock.modules.junit4.PowerMockRunnerDelegate;
import org.robolectric.RobolectricTestRunner;

/**
 * Example of powermock and robolectric incompatibility
 */
@RunWith(PowerMockRunner.class)
@PowerMockRunnerDelegate(RobolectricTestRunner.class)
@PrepareForTest(Dummy1Test.Dummy2.class)
public class Dummy1Test {
    public class Dummy2 {

        public final void  privateFunc(int i) {
        }

        public void testFunc() {
            privateFunc(42);
        }

    }

    @Test
    public void test() throws Exception {
        Dummy2 d2= spy(new Dummy2());
        doNothing().when(d2, "privateFunc", anyInt());
        d2.testFunc();
        verifyPrivate(d2).invoke("privateFunc", 42);
    }

}
```

Fails wiith:

```
org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
Invalid use of argument matchers!
0 matchers expected, 1 recorded:
-> at Dummy1Test.test(Dummy1Test.java:34)

This exception may occur if matchers are combined with raw values:
    //incorrect:
    someMethod(anyObject(), "raw String");
When using matchers, all arguments have to be provided by matchers.
For example:
    //correct:
    someMethod(anyObject(), eq("String by matcher"));

For more info see javadoc for Matchers class.

	at Dummy1Test.test(Dummy1Test.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:236)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:158)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner$2.call(DelegatingPowerMockRunner.java:143)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner$2.call(DelegatingPowerMockRunner.java:136)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner.withContextClassLoader(DelegatingPowerMockRunner.java:127)
	at org.powermock.modules.junit4.internal.impl.DelegatingPowerMockRunner.run(DelegatingPowerMockRunner.java:136)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:106)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

If I remove the 
@PowerMockRunnerDelegate(RobolectricTestRunner.class) the test works.

**Comment by aberent** [comment]
Since I don't know if this is a Robolectric bug or a Powermock bug I have just created a corresponding Robolectric bug https://github.com/robolectric/robolectric/issues/1974

**Comment by aberent** [comment]
The old way of doing this (using `PowerMockRule()` as described in https://github.com/robolectric/robolectric/wiki/Using-PowerMock) works, so it seems that this is purely a problem with @PowerMockRunnerDelegate(RobolectricTestRunner.class). As such I have closed the Robolectric bug.

**Comment by JavierSP1209** [comment]
For me, using the `@PowerMockRunnerDelegate` will make `@PrepareForTest` not to work, I post a question on stackoverflow with more details [http://stackoverflow.com/questions/36157099/robolectric-powermock-mockito-not-working](url)

**Comment by thekingnothing** [comment]
@JavierSP1209/@aberent 
 
I think issue not in `@PowerMockRunnerDelegate`, but it order of runners. I didn't see source code of `RobolectricTestRunner.class` but I can guess what it also somehow works with class loader an erase PowerMock changes. When `PowerMockRule` is used, then PowerMock applied its changes after runner initialised test.

**Comment by JavierSP1209** [comment]
I just remove the `@PowerMockRunnerDelegate` and `@RunWith(MyCustomRunner.class)` and the result is the same, in order to fix the last issue (`You might experience classloading issues...`) I add the class that was failing to @PowerMockIgnore() but I don't thing is the best solution because I cannot add each class each time it fails :/
