### ISSUE TITLE
Mockito.when throws NPE if incorrect object is passed.

### ISSUE THREAD

**Issue by thekingnothing** [jayway/powermock#632]
Code example: 

```
public class MockStaticNotPreparedTest {

    @Rule
    public PowerMockRule rule = new PowerMockRule();

    @Rule
    public ExpectedException expectedException = ExpectedException.none();

    @Test
    public void testWhenNotPrepared() throws Exception {

        final String expected = "Hello world";
        final String argument = "hello";

        //SuppressMethod suppressMethod = mock(SuppressMethod.class);
        SuppressMethod suppressMethod = new SuppressMethod();

        //PowerMockito.when(suppressMethod.getBoolean()).thenReturn(true);
        Mockito.when(suppressMethod.getBoolean()).thenReturn(true);

    }

}
```

StackTrace:  

> java.lang.ExceptionInInitializerError
> 	at org.mockito.internal.exceptions.stacktrace.ConditionalStackTraceFilter.<init>(ConditionalStackTraceFilter.java:17)
> 	at org.mockito.exceptions.base.MockitoException.filterStackTrace(MockitoException.java:41)
> 	at org.mockito.exceptions.base.MockitoException.<init>(MockitoException.java:30)
> 	at org.mockito.exceptions.misusing.MockitoConfigurationException.<init>(MockitoConfigurationException.java:18)
> 	at org.mockito.internal.configuration.plugins.PluginLoader.loadImpl(PluginLoader.java:66)
> 	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:24)
> 	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:12)
> 	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:11)
> 	at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:24)
> 	at org.mockito.internal.MockitoCore.<init>(MockitoCore.java:44)
> 	at org.mockito.Mockito.<clinit>(Mockito.java:975)
> 	at org.powermock.modules.test.junit4.rule.objenesis.MockStaticNotPreparedTest.testWhenNotPrepared(MockStaticNotPreparedTest.java:45)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
> 	at org.powermock.modules.junit4.rule.PowerMockStatement$1.run(PowerMockRule.java:65)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.powermock.reflect.internal.WhiteboxImpl.performMethodInvocation(WhiteboxImpl.java:1898)
> 	at org.powermock.reflect.internal.WhiteboxImpl.doInvokeMethod(WhiteboxImpl.java:801)
> 	at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:666)
> 	at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:401)
> 	at org.powermock.classloading.ClassloaderExecutor.execute(ClassloaderExecutor.java:98)
> 	at org.powermock.classloading.ClassloaderExecutor.execute(ClassloaderExecutor.java:78)
> 	at org.powermock.modules.junit4.rule.PowerMockStatement.evaluate(PowerMockRule.java:57)
> 	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:110)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
> 	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
> 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
> 	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
> 	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
> Caused by: java.lang.NullPointerException
> 	at org.mockito.internal.configuration.plugins.Plugins.getStackTraceCleanerProvider(Plugins.java:17)
> 	at org.mockito.internal.exceptions.stacktrace.StackTraceFilter.<clinit>(StackTraceFilter.java:21)
> 	... 51 more
> 
> 
> Process finished with exit code 255

Dependencies: 

       <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-classloading-objenesis</artifactId>
            <version>${project.version}</version>
        </dependency>

**Comment by thekingnothing** [comment]
Defect in mockito. Pull request is raised mockito/mockito#368
