### ISSUE TITLE
invokeMethod throws NPE when an argument is null when the method cannot be found

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#64]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 27, 2008 14:18:47_

java.lang.NullPointerException
at org.powermock.Whitebox.getArgumentsAsString(Whitebox.java:529)
at org.powermock.Whitebox.throwExceptionIfMethodWasNotFound(Whitebox.java:508)
at org.powermock.Whitebox.findMethodOrThrowException(Whitebox.java:425)
at org.powermock.Whitebox.doInvokeMethod(Whitebox.java:341)
at org.powermock.Whitebox.invokeMethod(Whitebox.java:277)

_Original issue: http://code.google.com/p/powermock/issues/detail?id=44_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 29, 2008 07:23:17_

invokeMethod no longer throws NullPointerException when an argument is null when the
method cannot be found

**Status:** Fixed
