### ISSUE TITLE
PowerMock Agent and TestNG 6.9.+

### ISSUE THREAD

**Issue by thekingnothing** [jayway/powermock#640]
PowerMock agent doesn't work with latest version of TestNG 6.9.10. Without using agent all works fine. And with old version TestNG (6.8.21) also works fine 

With using java agent the following exception: 

> objc[56954]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
> java.lang.VerifyError: Expecting a stackmap frame at branch target 11
> Exception Details:
>   Location:
>     org/testng/internal/ObjectFactoryImpl.newInstance(Ljava/lang/reflect/Constructor;[Ljava/lang/Object;)Ljava/lang/Object; @0: aload_1
>   Reason:
>     Expected stackmap frame at this location.
>   Bytecode:
>     0x0000000: 2b04 b600 1f2b 2cb6 0022 b04e 2bb6 0026
>     0x0000010: b800 2cb0 4e2b b600 26b8 002c b04e bb00
>     0x0000020: 2e59 bb00 3059 b700 3112 33b6 0037 2bc6
>     0x0000030: 000d 2bb6 0026 b600 3da7 0005 123f b600
>     0x0000040: 37b6 0042 2db7 0045 bf                 
>   Exception Handler Table:
>     bci [0, 10] => handler: 11
>     bci [0, 10] => handler: 20
>     bci [0, 10] => handler: 29
> 
> 	at org.powermock.modules.testng.PowerMockObjectFactory.<init>(PowerMockObjectFactory.java:37)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at java.lang.Class.newInstance(Class.java:442)
> 	at org.testng.xml.TestNGContentHandler.xmlSuite(TestNGContentHandler.java:205)
> 	at org.testng.xml.TestNGContentHandler.startElement(TestNGContentHandler.java:519)
> 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
> 	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.startElement(XMLDTDValidator.java:745)
> 	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:380)
> 	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:614)
> 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3135)
> 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:880)
> 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
> 	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
> 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
> 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
> 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
> 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
> 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
> 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
> 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
> 	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
> 	at org.testng.xml.XMLParser.parse(XMLParser.java:39)
> 	at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:16)
> 	at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:9)
> 	at org.testng.xml.Parser.parse(Parser.java:172)
> 	at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:305)
> 	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:44)
> 	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:122)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by thekingnothing** [comment]
Demo
https://github.com/thekingnothing/testng-sample
