### ISSUE TITLE
jacoco offline instrumentation incompatibility with powermock byte-code manipulation when using @SuppressStaticInitializationFor

### ISSUE THREAD

**Issue by astafev** [jayway/powermock#645]
Hi, there is a test project: https://github.com/astafev/jacoco-offline-powermock-junit

The problem:
if use @SuppressStaticInitializationFor("StaticClass") and execute mockStatic(StaticClass.class) in the test method, it's impossible to instantiate StaticClass, the exception:

```
java.lang.NullPointerException
    at StaticClass.<init>(StaticClass.java:1)
```

The problem occurs only when StaticClass is patched with jacoco offline instrumentation.

**Comment by astafev** [comment]
I've just understood the reasons - jacoco offline instrumentation adds static method $jacocoInit, which is invoked in the beginning of every method. So mockStatic just replaces this method.

Maybe it's worth in case of synthetic methods invoke original methods?

Now the problem can be bypassed with using spy method instead of mockStatic.

**Comment by thekingnothing** [comment]
`mockStatic` doesn't replace the `$jacocoInit`. This method simple is mocked as other static methods, what's why `spy` is work fine. 

To fit the issue the `org.powermock.api.mockito.internal.mockcreation.MockCreator.createMock` method should know that for the `$jacocoInit` method invocation either shouldn't be create or should call real method. 

I sugest implement it via pluggable filter and a new component like **powermock-jacoco** which contains filter for jacoco method which should be skipped.

**Comment by astafev** [comment]
Sounds good, but, IMHO, it seems to be too much if jacoco instrumentation will be the only case of usage of this filter.
Hardly anyone would want to work with synthetic method $jacocoInit in his code). I mean it may be ok to skip this method always. But of course it's up to you.

**Comment by thekingnothing** [comment]
I sure that not only Jacoco has same issue. And that I know - core should know nothing about any libraries, because it breaks inversion of control principal. This feature could be useful for users.

**Comment by thekingnothing** [comment]
My thoughts: add new interface like `MockMethodFilters` and load implementations of the filter in runtime during start powermock into Repository. For now list of filters will be hardcode and contains only filter for Jacoco, but in future it will be configurable either via annotation or by adding implementation to class path.

**Comment by thekingnothing** [comment]
@andreicristianpetcu I think this is a good issue to start :)

**Comment by andreicristianpetcu** [comment]
I have been digging in and I found that the `$jacocoInit` method is called in [doMethodCall](https://github.com/jayway/powermock/blob/62236dbbb76953158f3a28c0d3a04980f7b9d171/core/src/main/java/org/powermock/core/MockGateway.java#L66).

I'm not quite sure how to proceed. Do I need to hook the MockMethodFilters interface there or somewhere else? This is the stack trace of the call.

```java
        at org.powermock.core.MockGateway.doMethodCall(MockGateway.java:69)
        at org.powermock.core.MockGateway.methodCall(MockGateway.java:63)
        at StaticClass.$jacocoInit(StaticClass.java)
        at StaticClass.<init>(StaticClass.java)
        at StaticClassTestngTest.test(StaticClassTestngTest.java:13)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
        at org.testng.TestRunner.privateRun(TestRunner.java:782)
        at org.testng.TestRunner.run(TestRunner.java:632)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
        at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
        at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
        at org.testng.SuiteRunner.run(SuiteRunner.java:268)
        at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
        at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
        at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
        at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
        at org.testng.TestNG.run(TestNG.java:1064)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by andreicristianpetcu** [comment]
@thekingnothing how do you propose I get the list of all the classes? Some people [recommend](http://stackoverflow.com/a/15313028) to use the [Reflections](https://github.com/ronmamo/reflections) library.

Should I add a library? Is Reflections ok or should I make my own class finder to find the list of classes implementing the interface?

**Comment by andreicristianpetcu** [comment]
I implemented [my hackis method](https://github.com/andreicristianpetcu/powermock/blob/fa6bf4abb31c59befb137bc350b142938ec16900/core/src/main/java/org/powermock/core/classloader/ClasspathClassFinder.java#L15-L27) that finds all classes implementing my MockMethodFilters interface. An I also wrote [some tests](https://github.com/andreicristianpetcu/powermock/blob/fa6bf4abb31c59befb137bc350b142938ec16900/core/src/test/java/org/powermock/core/classloader/ClasspathClassFinderTest.java#L14-L46) for it but I think the Reflections one is a lot better and think it is better to drop mine and use Reflections but it is your decision.

**Comment by johanhaleby** [comment]
@andreicristianpetcu I don't think we should bring in Reflections for this. Reflections contains a lot more stuff than this and in some sense it tries to solve the same problems as `powermock-reflect`. I think we could take inspiration from Reflections perhaps but inmho we should avoid third-party dependencies as a much as possible.

**Comment by andreicristianpetcu** [comment]
Ok. I will try to do this. I'll keep you posted with the update.

This is not the only project I am working on in my spare time so the speed of development is not exactly stellar :D

**Comment by johanhaleby** [comment]
@andreicristianpetcu Thanks for your understanding and for your help so far

**Comment by astafev** [comment]
there's a trick to solve the problem with current version:
```
PowerMockito.mockStatic(clazz, new Answer<Object>() {
        @Override
        public Object answer(InvocationOnMock invocation) throws Throwable {
            if (invocation.getMethod().getName().equals("$jacocoInit")) {
                return CALLS_REAL_METHODS.answer(invocation);
            }
            return RETURNS_DEFAULTS.answer(invocation);
        }
    }
);
```

Probably it can be also done also by overriding default answer in mocktio (via global config). Then existing code with mockStatic won't be changed.

**Comment by andreicristianpetcu** [comment]
Thank you @astafev I have a WIP for which I did not have time lately but [I picked it up again](https://github.com/andreicristianpetcu/powermock/commits/master). As I said before, I have other FLOSS projects on my mind but right now I want to fix this issue.

**Comment by andreicristianpetcu** [comment]
@thekingnothing I have a problem and maybe you can help me: I can scan the classpath of classes implementing my interface but I can only see them if they get instantiated.

If I [comment this line](https://github.com/andreicristianpetcu/powermock/blob/b9787c28f978aeab3c1bcfa93ae255fa5b05e7ad/core/src/test/java/org/powermock/core/classloader/ClasspathClassFinderTest.java#L33), the test will fail. Also if I revert [this commit](https://github.com/andreicristianpetcu/jacoco-offline-powermock-junit/commit/56fb309ffea4718f721f2b160632fec0476783d3) the tests will fail.

Now either I can't see non-loaded java classes due to a Java limitation or due to my implementation's limitation. I'm trying to understand this and find a workaround. Is there a way that I can register some sort of a listener when the JVM starts, the unit tests start or powermock starts its instrumentation?

Do you have any other ideas? Thank you!

**Comment by thekingnothing** [comment]
@andreicristianpetcu 
You may check source code of [ClassPathScanningCandidateComponentProvider](https://github.com/spring-projects/spring-framework/blob/master/spring-context/src/main/java/org/springframework/context/annotation/ClassPathScanningCandidateComponentProvider.java). It's the Spring class which scans file system and looking for class file, so as result it can find not loaded classes. 

But, I'm not sure that we really need feature. For us will be enough that we have list of filter in a properties file or hard-coded in some class constants.

**Comment by thekingnothing** [comment]
Fixed by ignoring all synthetic methods/fields, as it was recommended by Jacoco team.
