### ISSUE TITLE
TestNG  SkipException doesn't work with PowerMock 

### ISSUE THREAD

**Issue by thekingnothing** [jayway/powermock#647]
TestNG let a use skip a test by throwing `org.testng.SkipException` or any child of exception. But this doesn't work with PowerMock. 

> org.testng.SkipException: Skipp test
> 
> 	at samples.testng.FinalTest.mockingFinalClassesAndMethodsWorkWithTestNGAndEasyMock(FinalTest.java:29)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
> 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
> 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
> 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
> 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
> 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
> 	at org.testng.TestRunner.privateRun(TestRunner.java:782)
> 	at org.testng.TestRunner.run(TestRunner.java:632)
> 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
> 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
> 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
> 	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
> 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
> 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
> 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
> 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
> 	at org.testng.TestNG.run(TestNG.java:1064)
> 	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
> 	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:122)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

Code: 

```
@PrepareForTest(FinalDemo.class)
public class FinalTest extends PowerMockTestCase {

    @Test
    public void mockingFinalClassesAndMethodsWorkWithTestNGAndEasyMock() throws Exception {
        throw new SkipException("Skip test");
    }
}
```

It doesn't work because TestNG handle `SkipException` via `SkipException.class.isAssignableFrom`. But won't work in case if exception is thrown with another class loader, which different from `org.testng.internal.Invoker`.

**Comment by thekingnothing** [comment]
Create a issue fro TestNG 
https://github.com/cbeust/testng/issues/1003
