### ISSUE TITLE
The doCallRealMethod with verify reports incorrect invocation count

### ISSUE THREAD

**Issue by donnfelker** [jayway/powermock#649]
I'm using the `doCallRealMethod()` to create a partial mock. Later in the test I want to verify that the real method was in fact called, 1 time. Unfortunately, powermock is stating the method is called 3 times (I've verified that the code does not in-fact do this). 

### What steps will reproduce the problem?
Open the attached zip file and run the `ExampleRealmTest#shouldVerifyTransactionWasCreated` test.

### What is the expected output?
The test should pass. 

### What do you see instead?
```
org.mockito.exceptions.verification.TooManyActualInvocations: 
realm.executeTransaction(null);
Wanted 1 time:
-> at io.realm.examples.unittesting.ExampleRealmTest.shouldVerifyTransactionWasCreated(ExampleRealmTest.java:83)
But was 3 times. Undesired invocation:
-> at io.realm.examples.unittesting.repository.DogRepositoryImpl.createDog(DogRepositoryImpl.java:27)
```

### What version of the product are you using?
1.6.4

### On what operating system?
Mac OSX 10.10.5

### Please provide any additional information below. 
I have verified that this method is only called once. In the attached example project I have two tests `thisFails` and `thisPasses` to illustrate how the test passes when using a normal mock. As soon as I use a partial though the test fails. 

Example project: 
[examples.zip](https://github.com/jayway/powermock/files/179817/examples.zip)

**Comment by thekingnothing** [comment]
Unfortunately, I cannot run your example, because it required Android SDK. I'll try reproduce the issue without using Robolectric and other Android relative stuff

**Comment by thekingnothing** [comment]
By the way, did you try use `@PowerMockRunnerDelegate` instead rules?
