### ISSUE TITLE
Upload artifacts to the central repository

### ISSUE THREAD

**Issue by johanhaleby** [jayway/powermock#65]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 28, 2008 08:27:59_

Upload artifacts to the central repository

_Original issue: http://code.google.com/p/powermock/issues/detail?id=45_

**Comment by johanhaleby** [comment]
_From [jan.kron...@gmail.com](https://code.google.com/u/111289048178412145391/) on April 27, 2009 09:56:49_

**Labels:** Milestone-Release1.3

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 07, 2009 12:18:15_

We cannot depend on third-party repos in that case which we currently do because of
Javassist

**Labels:** -Milestone-Release1.3 Milestone-Release2.0

**Comment by johanhaleby** [comment]
_From [lukewpat...@gmail.com](https://code.google.com/u/115628002144849920714/) on October 30, 2009 10:03:50_

For those interested in this issue, here is the blocking Javassist issue to vote for: https://jira.jboss.org/jira/browse/JASSIST-96

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 09, 2010 12:26:42_

Issue 238 has been merged into this issue.

**Comment by johanhaleby** [comment]
_From [m.kaepp...@gmail.com](https://code.google.com/u/112265135089213955243/) on July 01, 2010 00:29:47_

Any progress on this?

**Comment by johanhaleby** [comment]
_From [matt.blanchette@gmail.com](https://code.google.com/u/matt.blanchette@gmail.com/) on September 15, 2010 19:45:06_

I believe the referenced Javassist issue has been resolved: http://repo1.maven.org/maven2/org/javassist/javassist/3.13.0-GA/

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 15, 2010 23:14:03_

This is great news!! THanks for letting us know.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 15, 2010 23:15:28_

**Labels:** -Milestone-Release2.0 Milestone-Release1.5

**Comment by johanhaleby** [comment]
_From [martinb...@gmail.com](https://code.google.com/u/112298975922274940309/) on September 23, 2010 12:33:28_

As I'm working in a formalized Maven environment, my only option is to use packaged from the main Maven repo. I would very much like to see PowerMock in that repo. The facilities to mock static and final methods will greatly help my unit testing.

Thank you!

**Comment by johanhaleby** [comment]
_From [pja...@gmail.com](https://code.google.com/u/113036422892402586175/) on October 08, 2010 11:11:51_

Central has some additional requirements[1] that aren't met by the current trunk, the most pervasive of which is that all projects must have a \<description>, \<licenses> and \<scm>.

I'm attaching a patch that adds the missing elements.  Note that examples/tutorial/pom.xml doesn't use the powermock parent, so I added \<licenses> and \<scm> there, copied from the top-level pom.xml.  (It may be necessary to add \<developers> to examples/tutorial/pom.xml as well.)  A better solution might be to just use the powermock parent, the same as the other projects.

There's also a bit of cleanup, removing \<url> elements that incorrectly point to Maven's website.  It's not necessary to remove them, but it's better not to have them in the project.

[1] https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide#SonatypeOSSMavenRepositoryUsageGuide-6.CentralSyncRequirement

**Attachment:** [powermock-central-reqs.patch](http://code.google.com/p/powermock/issues/detail?id=45#hc11)

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 09, 2010 07:54:55_

Thanks a lot! Just committed the patched version.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 09, 2010 08:48:12_

Added sonatype parent pom to our root pom.xml and I've also added a JIRA ticket for PowerMock at Sonatype.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 12, 2010 13:21:20_

I run into the following exception when I try to do mvn release:perform:

 [FATAL ERROR] org.apache.maven.plugins.site.SiteMojo#execute() caused a linkage error (java.lang.ExceptionInInitializerError) and may be out-of-date. Check the realms:
    [FATAL ERROR] Plugin realm = app0.child-container[org.apache.maven.plugins:maven-site-plugin:2.1.1]
    urls[0] = file:/home/johan/.m2/repository/org/apache/maven/plugins/maven-site-plugin/2.1.1/maven-site-plugin-2.1.1.jar
    urls[1] = file:/home/johan/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
    urls[2] = file:/home/johan/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.1/plexus-utils-1.5.1.jar
    urls[3] = file:/home/johan/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.1.3/doxia-module-xhtml-1.1.3.jar
    urls[4] = file:/home/johan/.m2/repository/org/apache/maven/doxia/doxia-core/1.1.3/doxia-core-1.1.3.jar
    urls[5] = file:/home/johan/.m2/repository/xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.jar
    urls[6] = file:/home/johan/.m2/repository/xml-apis/xml-apis/1.3.04/xml-apis-1.3.04.jar
    urls[7] = file:/home/johan/.m2/repository/commons-lang/commons-lang/2.1/commons-lang-2.1.jar
    urls[8] = file:/home/johan/.m2/repository/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar
    urls[9] = file:/home/johan/.m2/repository/commons-codec/commons-codec/1.2/commons-codec-1.2.jar
    urls[10] = file:/home/johan/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.1.3/doxia-module-apt-1.1.3.jar
    urls[11] = file:/home/johan/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.1.3/doxia-module-xdoc-1.1.3.jar
    urls[12] = file:/home/johan/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.1.3/doxia-module-fml-1.1.3.jar
    urls[13] = file:/home/johan/.m2/repository/org/apache/maven/doxia/doxia-decoration-model/1.1.3/doxia-decoration-model-1.1.3.jar
    urls[14] = file:/home/johan/.m2/repository/org/apache/maven/doxia/doxia-site-renderer/1.1.3/doxia-site-renderer-1.1.3.jar
    urls[15] = file:/home/johan/.m2/repository/org/codehaus/plexus/plexus-i18n/1.0-beta-7/plexus-i18n-1.0-beta-7.jar
    urls[16] = file:/home/johan/.m2/repository/org/codehaus/plexus/plexus-velocity/1.1.8/plexus-velocity-1.1.8.jar
    urls[17] = file:/home/johan/.m2/repository/org/apache/velocity/velocity/1.5/velocity-1.5.jar
    urls[18] = file:/home/johan/.m2/repository/commons-collections/commons-collections/3.2/commons-collections-3.2.jar
    urls[19] = file:/home/johan/.m2/repository/oro/oro/2.0.8/oro-2.0.8.jar
    urls[20] = file:/home/johan/.m2/repository/org/apache/maven/shared/maven-doxia-tools/1.2.1/maven-doxia-tools-1.2.1.jar
    urls[21] = file:/home/johan/.m2/repository/commons-io/commons-io/1.4/commons-io-1.4.jar
    urls[22] = file:/home/johan/.m2/repository/org/codehaus/plexus/plexus-archiver/1.0-alpha-7/plexus-archiver-1.0-alpha-7.jar
    urls[23] = file:/home/johan/.m2/repository/org/mortbay/jetty/jetty/6.1.5/jetty-6.1.5.jar
    urls[24] = file:/home/johan/.m2/repository/org/mortbay/jetty/jetty-util/6.1.5/jetty-util-6.1.5.jar
    urls[25] = file:/home/johan/.m2/repository/org/mortbay/jetty/servlet-api-2.5/6.1.5/servlet-api-2.5-6.1.5.jar
    [FATAL ERROR] Container realm = plexus.core
    urls[0] = file:/usr/share/maven2/lib/maven-debian-uber.jar
    [INFO] ------------------------------------------------------------------------
    [ERROR] FATAL ERROR
    [INFO] ------------------------------------------------------------------------
    [INFO] null
    Invalid class loader hierarchy.  You have more than one version of 'org.apache.commons.logging.Log' visible, which is not allowed.
    [INFO] ------------------------------------------------------------------------
    [INFO] Trace
    java.lang.ExceptionInInitializerError
    	at org.apache.maven.plugin.javadoc.JavadocUtil.fetchURL(JavadocUtil.java:730)
    	at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.isValidJavadocLink(AbstractJavadocMojo.java:4680)
    	at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.addLinkArguments(AbstractJavadocMojo.java:3229)
    	at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.addStandardDocletOptions(AbstractJavadocMojo.java:3885)
    	at org.apache.maven.plugin.javadoc.AbstractJavadocMojo.executeReport(AbstractJavadocMojo.java:1761)
    	at org.apache.maven.plugin.javadoc.TestJavadocReport.executeReport(TestJavadocReport.java:149)
    	at org.apache.maven.plugin.javadoc.JavadocReport.generate(JavadocReport.java:122)
    	at org.apache.maven.plugins.site.ReportDocumentRenderer.renderDocument(ReportDocumentRenderer.java:164)
    	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.renderModule(DefaultSiteRenderer.java:330)
    	at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render(DefaultSiteRenderer.java:134)
    	at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:158)
    	at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:120)
    	at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
    	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
    	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
    	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
    	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
    	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
    	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
    	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
    	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
    	at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
    	at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    	at java.lang.reflect.Method.invoke(Method.java:597)
    	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
    	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
    	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
    	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
    Caused by: org.apache.commons.logging.LogConfigurationException: org.apache.commons.logging.LogConfigurationException: org.apache.commons.logging.LogConfigurationException: Invalid class loader hierarchy.  You have more than one version of 'org.apache.commons.logging.Log' visible, which is not ...

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 12, 2010 13:21:20_

...allowed. (Caused by org.apache.commons.logging.LogConfigurationException: Invalid class loader hierarchy.  You have more than one version of 'org.apache.commons.logging.Log' visible, which is not allowed.) (Caused by org.apache.commons.logging.LogConfigurationException: org.apache.commons.logging.LogConfigurationException: Invalid class loader hierarchy.  You have more than one version of 'org.apache.commons.logging.Log' visible, which is not allowed. (Caused by org.apache.commons.logging.LogConfigurationException: Invalid class loader hierarchy.  You have more than one version of 'org.apache.commons.logging.Log' visible, which is not allowed.))
    	at org.apache.commons.logging.impl.LogFactoryImpl.newInstance(LogFactoryImpl.java:543)
    	at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:235)
    	at org.apache.commons.logging.impl.LogFactoryImpl.getInstance(LogFactoryImpl.java:209)
    	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:351)
    	at org.apache.commons.httpclient.HttpClient.<clinit>(HttpClient.java:66)
    	... 31 more
    Caused by: org.apache.commons.logging.LogConfigurationException: org.apache.commons.logging.LogConfigurationException: Invalid class loader hierarchy.  You have more than one version of 'org.apache.commons.logging.Log' visible, which is not allowed. (Caused by org.apache.commons.logging.LogConfigurationException: Invalid class loader hierarchy.  You have more than one version of 'org.apache.commons.logging.Log' visible, which is not allowed.)
    	at org.apache.commons.logging.impl.LogFactoryImpl.getLogConstructor(LogFactoryImpl.java:397)
    	at org.apache.commons.logging.impl.LogFactoryImpl.newInstance(LogFactoryImpl.java:529)
    	... 35 more
    Caused by: org.apache.commons.logging.LogConfigurationException: Invalid class loader hierarchy.  You have more than one version of 'org.apache.commons.logging.Log' visible, which is not allowed.
    	at org.apache.commons.logging.impl.LogFactoryImpl.getLogConstructor(LogFactoryImpl.java:385)
    	... 36 more
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 1 minute 50 seconds
    [INFO] Finished at: Tue Oct 12 22:13:01 CEST 2010
    [INFO] Final Memory: 214M/624M
    [INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Maven execution failed, exit code: '1'


Does anyone know how to fix this?

**Comment by johanhaleby** [comment]
_From [franci...@gmail.com](https://code.google.com/u/113865493528058686158/) on October 12, 2010 23:37:59_

mvn site build works fine here using Apache Maven 2.2.1

You could try an older version of the site plugin.

You could try building with maven 3 which has way better error reporting.

eg:
[INFO] Scanning for projects...
Downloading: http://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/5/oss-parent-5.pom Downloaded: http://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/5/oss-parent-5.pom (4 KB at 4.8 KB/sec)
[WARNING]
[WARNING] Some problems were encountered while building the effective
model for org.powermock:powermock-core:jar:1.5-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for
org.apache.maven.plugins:maven-compiler-plugin is missing. @
org.powermock:powermock:1.5-SNAPSHOT,
/home/francisdb/workspace/powermock-read-only/pom.xml, line 94, column
21
[WARNING] 'build.plugins.plugin.version' for
org.codehaus.mojo:rat-maven-plugin is missing. @
org.powermock:powermock:1.5-SNAPSHOT,
/home/francisdb/workspace/powermock-read-only/pom.xml, line 143,
column 21
[WARNING] 'build.plugins.plugin.version' for
org.apache.maven.plugins:maven-jar-plugin is missing. @ line 38,
column 12
[WARNING] 'build.plugins.plugin.version' for
org.apache.maven.plugins:maven-source-plugin is missing. @
org.powermock:powermock:1.5-SNAPSHOT,
/home/francisdb/workspace/powermock-read-only/pom.xml, line 105,
column 21
[WARNING] The expression ${version} is deprecated. Please use
${project.version} instead.
[WARNING] 'reporting.plugins.plugin.version' for
org.apache.maven.plugins:maven-javadoc-plugin is missing.
[WARNING] 'reporting.plugins.plugin.version' for
org.apache.maven.plugins:maven-surefire-report-plugin is missing.
[WARNING] 'reporting.plugins.plugin.version' for
org.apache.maven.plugins:maven-pmd-plugin is missing.
[WARNING] 'reporting.plugins.plugin.version' for
org.apache.maven.plugins:maven-jxr-plugin is missing.
[WARNING] 'reporting.plugins.plugin.version' for
org.apache.maven.plugins:maven-project-info-reports-plugin is missing.
[WARNING] 'reporting.plugins.plugin.version' for
org.codehaus.mojo:findbugs-maven-plugin is missing.
[WARNING]
[WARNING] Some problems were encountered while building the effective
model for org.powermock:powermock-api-easymock:jar:1.5-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for
org.apache.maven.plugins:maven-compiler-plugin is missing. @
org.powermock:powermock:1.5-SNAPSHOT,
/home/francisdb/workspace/powermock-read-only/pom.xml, line 94, column
21
[WARNING] 'build.plugins.plugin.version' for
org.codehaus.mojo:rat-maven-plugin is missing. @
org.powermock:powermock:1.5-SNAPSHOT,
/home/francisdb/workspace/powermock-read-only/pom.xml, line 143,
column 21
[WARNING] 'build.plugins.plugin.version' for
org.apache.maven.plugins:maven-source-plugin is missing. @
org.powermock:powermock:1.5-SNAPSHOT,
/home/francisdb/workspace/powermock-read-only/pom.xml, line 105,
column 21
[WARNING] The expression ${version} is deprecated. Please use
${project.version} instead.
[WARNING] 'reporting.plugins.plugin.version' for
org.apache.maven.plugins:maven-javadoc-plugin is missing.
[WARNING] 'reporting.plugins.plugin.version' for
org.apache.maven.plugins:maven-surefire-report-plugin is missing.
[WARNING] 'reporting.pl

further I see a lot of these:

INFO] Generating "About" report.
[WARNING] Deprecated API called - not org.apache.maven.doxia.sink.Sink
instance and no SinkFactory available. Please update this plugin.
[INFO] Generating "Source Repository" report.
[WARNING] Deprecated API called - not org.apache.maven.doxia.sink.Sink
instance and no SinkFactory available. Please update this plugin.
[INFO] Generating "Plugin Management" report.
[WARNING] Deprecated API called - not org.apache.maven.doxia.sink.Sink
instance and no SinkFactory available. Please update this plugin.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 13, 2010 12:22:21_

I simply removed site creation because we don't use it. PowerMock has now been uploaded to Sonatype and we're awaiting central synchronization. See https://issues.sonatype.org/browse/OSSRH-881 .

**Status:** Started

**Comment by johanhaleby** [comment]
_From [franci...@gmail.com](https://code.google.com/u/113865493528058686158/) on October 13, 2010 13:06:39_

great news

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 14, 2010 05:15:51_

PowerMock (1.4.6) is now in the central repo :) Thanks a lot for your help everyone! Note that the groupId has changed for most components to "org.powermock" so the getting started page is obsolete. I'll try to fix this later today and announce the new release.

**Status:** Accepted

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 17, 2010 13:03:34_

**Status:** Fixed
