### ISSUE TITLE
java.lang.VerifyError when trying to mock Android's Bundle constructor

### ISSUE THREAD

**Issue by muddin1** [jayway/powermock#650]
`VerifyError` when using `@PrepareForTest(android.os.Bundle.class)` and `PowerMockito.whenNew(android.os.Bundle.class).with[No]Arguments()`

```
java.lang.VerifyError: Bad <init> method call from inside of a branch
Exception Details:
  Location:
    SuperBundleCreatingClass.<init>(Lorg/powermock/core/IndicateReloadClass;)V @40: invokespecial
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: 2a2b 4e4d 1210 b800 1604 bd00 0d59 032d
    0x0000010: 5312 63b8 001b b800 213a 0519 05b2 0025
    0x0000020: a500 0e2a 01c0 0027 b700 2aa7 000a 2c2d
    0x0000030: b700 2a01 57b1                         
  Stackmap Table:
    full_frame(@46,{UninitializedThis,Object[#39],UninitializedThis,Object[#39],Top,Object[#13]},{})
    full_frame(@53,{Object[#2],Object[#39],Object[#2],Object[#39],Top,Object[#13]},{})


	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2658)
	at java.lang.Class.getDeclaredConstructors(Class.java:2007)
	at org.powermock.reflect.internal.WhiteboxImpl.findConstructorOrThrowException(WhiteboxImpl.java:1024)
	at org.powermock.api.support.membermodification.MemberMatcher.constructor(MemberMatcher.java:274)
```

Expected output: allows mocking the `Bundle` constructors.
Version: Powermock api and junit4 module 1.6.4
OS: JDK8 update 20 on Mac, unit testing Android code

### Test code
``` java

import android.os.Bundle;

@RunWith(PowerMockRunner.class)
@PrepareForTest(ClassCreatingBundle.class)
public class BundleTest {
    @Before
    public void setUp() throws Exception {
        PowerMockito.whenNew(Bundle.class).withAnyArguments().thenReturn(PowerMockito.mock(Bundle.class));
    }
}
```

**Comment by muddin1** [comment]
Upgrading to jdk1.8.0_77 fixes this. Was previously jdk 8 20.
