### ISSUE TITLE
Cannot mock the javafx class after it was prepared for test. 

### ISSUE THREAD

**Issue by thekingnothing** [jayway/powermock#654]
What steps will reproduce the problem?
Try to run the following test. 
```
import javafx.scene.layout.Region;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;

import static org.junit.Assert.assertNotNull;
import static org.powermock.api.mockito.PowerMockito.mock;

@RunWith(PowerMockRunner.class)
@PrepareForTest(Region.class)
public class ValueBlockTest {
    private Region mockTopLevelPane;

    @Before
    public void Setup() {
        mockTopLevelPane = mock(Region.class);
    }

    @Test
    public void nothing() {
        assertNotNull(mockTopLevelPane);
    }

}
```
What is the expected output?

Test is passed.

What do you see instead?

> java.lang.VerifyError: Inconsistent stackmap frames at branch target 1135
> Exception Details:
>   Location:
>     javafx/scene/Node.updateLocalToParentTransform()V @1135: ldc_w
>   Reason:
>     Type top (current frame, locals[8]) is not assignable to 'java/util/Iterator' (stack map, locals[8])
>   Current Frame:
>     bci: @1125
>     flags: { }
>     locals: { 'javafx/scene/Node', integer, double, double_2nd, 'java/util/Iterator', top, top, top, top, top, 'java/util/Iterator', integer, null, 'java/lang/Object' }
>     stack: { 'java/util/Iterator', null }
>   Stackmap Frame:
>     bci: @1135
>     flags: { }
>     locals: { 'javafx/scene/Node', integer, double, double_2nd, 'java/util/Iterator', top, top, top, 'java/util/Iterator', integer, null, 'java/lang/Object' }
>     stack: { }
>    ....
> 	at java.lang.Class.getDeclaredConstructors0(Native Method)
> 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
> 	at java.lang.Class.getDeclaredConstructors(Class.java:2020)
> 	at org.powermock.api.mockito.repackaged.ClassImposterizer.setConstructorsAccessible(ClassImposterizer.java:86)
> 	at org.powermock.api.mockito.repackaged.ClassImposterizer.imposterise(ClassImposterizer.java:72)
> 	at org.powermock.api.mockito.internal.mockcreation.MockCreator.createMethodInvocationControl(MockCreator.java:122)
> 	at org.powermock.api.mockito.internal.mockcreation.MockCreator.createMock(MockCreator.java:70)
> 	at org.powermock.api.mockito.internal.mockcreation.MockCreator.mock(MockCreator.java:47)
> 	at org.powermock.api.mockito.PowerMockito.mock(PowerMockito.java:144)
> 

What version of the product are you using?
PowerMock 1.6.4/Mockito 1.10.19
On what operating system?
Please provide any additional information below. 

If remove the `Region.class` from `@PrepareForTest` all works fine. Mockito also can mock this class.

**Comment by andrewdavidmackenzie** [comment]
Thanks!
