### ISSUE TITLE
ProxyFrameworkImpl could not be located in classpath.

### ISSUE THREAD

**Issue by CaiqueBrito** [jayway/powermock#679]
Hello,

I downloaded the powermock-easymock-junit-1.6.5.zip, write my code but i cant execute, 
Don`t know why appears this message, i look inside .jar and there is the ProxyFrameworkImpl.class
i'm looking to the following error:

 `java.lang.IllegalStateException: Extension API internal error: org.powermock.api.extension.proxyframework.ProxyFrameworkImpl could not be located in classpath.
at org.powermock.reflect.proxyframework.ProxyFrameworkHelper.register(ProxyFrameworkHelper.java:35)
at org.powermock.reflect.proxyframework.ClassLoaderRegisterProxyFramework.registerProxyframework(ClassLoaderRegisterProxyFramework.java:28)
at org.powermock.tests.utils.impl.AbstractCommonTestSuiteChunkerImpl.registerProxyframework(AbstractCommonTestSuiteChunkerImpl.java:101)
at org.powermock.tests.utils.impl.AbstractCommonTestSuiteChunkerImpl.chunkClass(AbstractCommonTestSuiteChunkerImpl.java:114)
at org.powermock.tests.utils.impl.AbstractCommonTestSuiteChunkerImpl.<init>(AbstractCommonTestSuiteChunkerImpl.java:60)
at org.powermock.tests.utils.impl.AbstractCommonTestSuiteChunkerImpl.<init>(AbstractCommonTestSuiteChunkerImpl.java:54)
at org.powermock.tests.utils.impl.AbstractTestSuiteChunkerImpl.<init>(AbstractTestSuiteChunkerImpl.java:58)
at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.<init>(JUnit4TestSuiteChunkerImpl.java:59)
at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.<init>(AbstractCommonPowerMockRunner.java:32)
at org.powermock.modules.junit4.PowerMockRunner.<init>(PowerMockRunner.java:34)
at java.lang.reflect.Constructor.newInstance(Native Method)
at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
at android.support.test.internal.runner.junit4.AndroidAnnotatedBuilder.runnerForClass(AndroidAnnotatedBuilder.java:51)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
at org.junit.runner.Computer.getRunner(Computer.java:40)
at org.junit.runner.Computer$1.runnerForClass(Computer.java:31)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:101)
at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:87)
at org.junit.runners.Suite.<init>(Suite.java:81)
at org.junit.runner.Computer.getSuite(Computer.java:28)
at android.support.test.internal.runner.TestRequestBuilder.classes(TestRequestBuilder.java:791)
at android.support.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:754)
at android.support.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:341)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:238)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1970)`

follow my test code:

@RunWith(PowerMockRunner.class)
@PrepareForTest(ObtainIPService.class)
public class ObtainIPUnit{

```
@Test
public void obtainIP() throws SocketException {

    mockStatic(ObtainIPService.class);
    expect(ObtainIPService.obtainIP()).andReturn("192.168.0.132");

    Log.i("UNITTEST", ObtainIPService.obtainIP());

    assertNotNull("The value is null", ObtainIPService.obtainIP());
}
```

}

Will be waiting for answer.
Kind regards.

**Comment by thekingnothing** [comment]
It looks like you have an issue with your class path. Please, check if the `powermock-api-easymock.jar` is added to your class path.

**Comment by CaiqueBrito** [comment]
@thekingnothing 

I'm using `powermock-easymock-1.6.5-full.jar`.
inside jar there is a `api` package, on my Mac i'm using the same jars and it's working like charm, do you have some clue to solve it?

Thanks.

**Comment by nataliabarbosa** [comment]
I am having the same problem. How can I fix this?
I am using the dependencies on an Android project to try mock server return.

**Comment by reytum** [comment]
You need to add the below dependency in your gradle
`androidTestImplementation 'org.powermock:powermock-core:1.7.0RC2'`
