### ISSUE TITLE
Problem when building Mocktio2 with gradle

### ISSUE THREAD

**Issue by HGyllensvard** [jayway/powermock#681]
Hi PowerMock team,

I've never used Powermock but I ran into some trouble getting it up and running. 
I am aware that the support for Mockito v2 is experimental and maybe I'm a bit too deep for my own good. :)

The initial building of the project works fine. 

After that I have only added the
@RunWith(PowerMockRunner.class), not using any other features so far. 
When I execute the test I get the following stacktrace:

`org.powermock.reflect.exceptions.FieldNotFoundException: No instance field named "reporter" could be found in the class hierarchy of org.mockito.internal.MockitoCore.
	at org.powermock.reflect.internal.matcherstrategies.FieldNameMatcherStrategy.notFound(FieldNameMatcherStrategy.java:40)
	at org.powermock.reflect.internal.WhiteboxImpl.findSingleFieldUsingStrategy(WhiteboxImpl.java:492)
	at org.powermock.reflect.internal.WhiteboxImpl.findFieldInHierarchy(WhiteboxImpl.java:445)
	at org.powermock.reflect.internal.WhiteboxImpl.findFieldInHierarchy(WhiteboxImpl.java:433)
	at org.powermock.reflect.internal.WhiteboxImpl.getInternalState(WhiteboxImpl.java:417)
	at org.powermock.reflect.Whitebox.getInternalState(Whitebox.java:292)
	at org.powermock.api.extension.reporter.MockingFrameworkReporterFactoryImpl$MockitoMockingFrameworkReporter.getMockitoReporter(MockingFrameworkReporterFactoryImpl.java:28)
	at org.powermock.api.extension.reporter.MockingFrameworkReporterFactoryImpl$MockitoMockingFrameworkReporter.enable(MockingFrameworkReporterFactoryImpl.java:38)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:120)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:53)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)`

I'm building through Android studio 2.1 and my dependencies are:

    testCompile 'junit:junit:4.12'
    testCompile 'org.mockito:mockito-core:2.0.78-beta'
    testCompile 'org.powermock:powermock-api-mockito2:1.6.5'
    testCompile 'org.powermock:powermock-module-junit4:1.6.5'

I'm using windows 10.

Now I looked in the Mockito project and found this commit where the Reporter class is refactored and moved which I would guess at least in part is the cause for the error:
https://github.com/mockito/mockito/commit/e2b7ee2597bb4aa1d840b0af1e902d1445be9767

I quickly tried to downgrade the verion of Mockito to 2.0.0-beta (didn't check exact version the change was introduced in) and the error disappeared.

If this is not the cause or related to it I'm out of ideas.

Thank you!

**Comment by thekingnothing** [comment]
Hi! 
Thank you for reporting this issue. 
Your right that have the issue due to that Mockito 2 has been changed since last PowerMock release and some class either was deleted or was moved. We'll fix the issue in the release PowerMock where we're planning to implement full supporting Mockito 2.

**Comment by HGyllensvard** [comment]
Hi,

Of course, I completely understand you're waiting with this.

At least there's a short-term workaround to downgrade the mockito2-beta version.

Maybe I missed it, but a potential improvement until the implementation is done could be to add which the latest beta version that the experimental powermock build has been built against in the wiki, so if more people come around they know straight away that if they go above that number they are more likely to encounter more problems.

**Comment by thekingnothing** [comment]
Information about which version of Mockito 2 is supported has been added.

**Comment by paulbrittain** [comment]
Getting this error with:

```
testCompile 'org.mockito:mockito-core:2.12.0'

testCompile group: 'org.mockito', name: 'mockito-all', version: '1.10.8'

testCompile "org.powermock:powermock-api-mockito:1.7.1"

testCompile "org.powermock:powermock-module-junit4:1.7.1"
```

**Comment by wuhao028** [comment]
getting this error with:
    testCompile 'junit:junit:4.12'
    testCompile 'org.mockito:mockito-core:2.13.0'
    testCompile 'org.powermock:powermock-api-mockito:1.7.3'
    testCompile 'org.powermock:powermock-module-junit4:1.7.3'

**Comment by zilong** [comment]
update cglib version

**Comment by ranjit92** [comment]
Hi Team, I am also getting the same error with the below version.
Please suggest the compatible version.

[INFO] +- org.easymock:easymock:jar:3.3.1:test
[INFO] +- org.powermock:powermock-module-junit4:jar:2.0.7:test
[INFO] |  +- org.powermock:powermock-module-junit4-common:jar:2.0.7:test
[INFO] |  |  +- org.powermock:powermock-reflect:jar:2.0.7:test
[INFO] |  |  \- org.powermock:powermock-core:jar:2.0.7:test
[INFO] +- org.powermock:powermock-api-easymock:jar:1.7.1:test
[INFO] |  +- org.powermock:powermock-api-support:jar:1.7.1:test
[INFO] +- org.mockito:mockito-core:jar:3.1.0:test
[INFO] +- org.powermock:powermock-api-mockito2:jar:2.0.7:test
[INFO] |  +- org.mockito:mockito-junit-jupiter:jar:3.1.0:test
[INFO] |  +- org.mockito:mockito-core:jar:3.1.0:test
