### ISSUE TITLE
@PrepareForTest annotation exception even when I'm using this annotation

### ISSUE THREAD

**Issue by ahmed-alstaty** [jayway/powermock#690]
Can you see anything in the logs? Can you debug why this happens? No

Is this question about PowerMock usage?
yes

The better way to ask question:
- The mailing-list : https://groups.google.com/forum/#!forum/powermock / powermock@googlegroups.com
- [Stackoverflow](http://stackoverflow.com/questions/tagged/powermock) with the tag 'powermock'. (Make sure you **include a short code snippet to demonstrate the problem** and if you have an exception then make sure **include stack trace**.)
## None of the above, want to create a GitHub issue

In order to help us to clarify issue can you answer the following question:

What steps will reproduce the problem?
I'm only trying to mock static methods and following the steps written in the document, an exception about the need to use @PrepareForTest annotation is always appear even I'm using the annotation
What is the expected output?
Mocking for the static methods should be valid and work correctly 
What do you see instead?
Exception about the need to use @PrepareForTest annotation
What version of the product are you using?
1.6.5
On what operating system?
Windows, Eclipse IDE
Please provide any additional information below. 

Stack trace : 

at org.powermock.api.mockito.expectation.reporter.MockitoPowerMockReporter.classNotPrepared(MockitoPowerMockReporter.java:31)
    at org.powermock.api.mockito.internal.mockcreation.MockTypeValidatorFactory$DefaultMockTypeValidator.validate(MockTypeValidatorFactory.java:38)
    at org.powermock.api.mockito.internal.mockcreation.AbstractMockCreator.validateType(AbstractMockCreator.java:18)
    at org.powermock.api.mockito.internal.mockcreation.MockCreator.createMock(MockCreator.java:57)
    at org.powermock.api.mockito.internal.mockcreation.MockCreator.mock(MockCreator.java:47)
    at org.powermock.api.mockito.PowerMockito.mockStatic(PowerMockito.java:71)
    at com.tradeos.b2b.finance.logic.AccountBalanceLogicTest.getInvoiceNumberTest(AccountBalanceLogicTest.java:82)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
    at org.testng.TestRunner.privateRun(TestRunner.java:782)
    at org.testng.TestRunner.run(TestRunner.java:632)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
    at org.testng.SuiteRunner.run(SuiteRunner.java:268)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
    at org.testng.TestNG.run(TestNG.java:1064)
    at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)

**Comment by thekingnothing** [comment]
Could you provide more information at lease code snippet. The exception is thrown if a class is not loaded by powermock class loader and as result cannot be mocked correctly.

**Comment by ahmed-alstaty** [comment]
@thekingnothing , Kindly see the following code snippet : 

 */
@RunWith(PowerMockRunner.class)
@PrepareForTest({ ZohoTransactionsLogic.class, ZohoTransactionsLogic.class })
public class AccountBalanceLogicTest extends TUnitTest {
	@Test
	@PrepareForTest({ ZohoTransactionsLogic.class, ZohoTransactionsLogic.class })
	public void getInvoiceNumberTest() {
		SoftObject mockedSoftObject = Mockito.mock(SoftObject.class);
		List<SoftObject> invoices = new ArrayList<SoftObject>();
		SoftObject invoice = new SoftObject();
		invoice.set(ZohoConstants.Invoice.TOTAL_PARAM, 100);
		invoices.add(invoice);
		invoice.set(ZohoConstants.Invoice.TOTAL_PARAM, 150);
		invoices.add(invoice);
		invoice.set(ZohoConstants.Invoice.TOTAL_PARAM, 200);
		invoices.add(invoice);
		invoice.set(ZohoConstants.Invoice.TOTAL_PARAM, 300);
		invoices.add(invoice);
		PowerMockito.mockStatic(MoneyAmountController.class);
		PowerMockito.mockStatic(ZohoTransactionsLogic.class);
		PowerMockito.when(ZohoTransactionsLogic.getContactInvoices(mockedSoftObject)).thenReturn(invoices);
		MoneyAmount result = AccountBalanceLogic.getInvoicedAmount(mockedSoftObject);
	}
}

**Comment by thekingnothing** [comment]
I not sure, maybe it's a copy-past issue, but I see you twice use `@PrepareForTest` on class and method level. And the annotation contains duplication: `{ ZohoTransactionsLogic.class, ZohoTransactionsLogic.class }`. Seems to me it should be: @PrepareForTest({ ZohoTransactionsLogic.class, MoneyAmountController.class })`

**Comment by ahmed-alstaty** [comment]
You are totally right, I've shared the code snippet with you just to simplify the idea, I've tried to put the annotation on the class level, on the method level, and on both test and class level. but sadly it does not work, also the duplication was by mistake. but I tried it without the duplication. and it didn't work. 

Worthy to mention that I'm using google app engine development environment if that can help with your advises.

**Comment by thekingnothing** [comment]
> Worthy to mention that I'm using google app engine development environment if that can help with your advises.

It could important information. PowerMock's ClassLoader adds an interface to all class which modifies during loading (not all classes are modified by class loader, only these classes that are specified in `@PrepareForTest`).  So if class not implement the interface, PowerMock decides that class has not been modified. It could be in case if the class is re-loaded with some other class loader and it could depend on environment. 

This checking has been added only in last version, so you may try to downgrade previous version.

**Comment by gauravsak** [comment]
@ahmed-alstaty Could you please confirm that you have the `@PrepareForTest` annotation only at class-level and it looks like `@PrepareForTest({ ZohoTransactionsLogic.class, MoneyAmountController.class })`?

**Comment by ahmed-alstaty** [comment]
@gauravsak , Yes, I've tried both on class level and on the test method level. I'm sure I've tried the right code, and followed the right way of usage for power Mock, I'm sorry for posting code could cause confusion, but believe me it's my mistake and the code was written right while I'm testing. Posted code is not the desired one.

**Comment by gauravsak** [comment]
@ahmed-alstaty Could you please edit your original post and post the right code to avoid further confusion? Thanks.

**Comment by thekingnothing** [comment]
Not response for a long time, so close

**Comment by headiem** [comment]
I am having the same issue any solution?

**Comment by roberto-rodriguez** [comment]
Same issue here:


 
@RunWith(PowerMockRunner.class) 
@PrepareForTest({Context.class,ReceiveSettlementConfirmations.class,SettlementMask.class})
public class ReceiveSettlementConfirmationsTest
{


    @Before 
    public void before() throws IOException, Exception
    { 
        try{
            mockStatic(Context.class);

...






Error:
Context not prepared for test.
