### ISSUE TITLE
StackOverflowError mocking final class extending non-public abstract class overriding equals method

### ISSUE THREAD

**Issue by rage-shadowman** [jayway/powermock#701]
If I try to mock a final class that extends a non-public abstract class that overrides the equals method, I get a `StackOverflowError`.

Failing test included below:

OverridesEquals.java
```java
package mockito.failure.test;

abstract class OverridesEquals {
	@Override
	public boolean equals (final Object other) {
		return this == other;
	}
}
```

MapWrapper.java
```java
package mockito.failure.test;

import java.io.Serializable;
import java.util.Collections;
import java.util.Map;

public final class MapWrapper extends OverridesEquals {
	private final Map<String, Serializable> data;

	MapWrapper(final Map<String, Serializable> data) {
		this.data = Collections.unmodifiableMap(data);
	}

	public Object get(final String key) {
		if (key == null || key.isEmpty()) {
			return null;
		}
		return data.get(key);
	}
}
```

MapWrapperTest.java
```java
package mockito.failure.test;

import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.powermock.api.mockito.PowerMockito;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;

@RunWith(PowerMockRunner.class)
@PrepareForTest({MapWrapper.class})
public class MapWrapperTest
{
	@Test
	public void testPowerMock () throws Exception
	{
		MapWrapper mocked = PowerMockito.mock(MapWrapper.class);
		PowerMockito.doReturn("1234").when(mocked).get("numbers");
		Assert.assertEquals("1234", mocked.get("numbers"));
	}
}
```
Using maven dependencies:
```XML
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.powermock</groupId>
      <artifactId>powermock-api-mockito2</artifactId>
      <version>1.6.5</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.powermock</groupId>
      <artifactId>powermock-module-junit4</artifactId>
      <version>1.6.5</version>
      <scope>test</scope>
    </dependency>
```

Error snippet:
```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.804 sec <<< FAILURE!
testPowerMock(mockito.failure.test.MapWrapperTest)  Time elapsed: 0.723 sec  <<< ERROR!
java.lang.StackOverflowError
        at java.security.AccessController.doPrivileged(Native Method)
        at org.powermock.reflect.internal.WhiteboxImpl.getAllMethods(WhiteboxImpl.java:1519)
        at org.powermock.reflect.internal.WhiteboxImpl.getMethods(WhiteboxImpl.java:1786)
        at org.powermock.reflect.internal.WhiteboxImpl.getMethods(WhiteboxImpl.java:1825)
        at org.powermock.reflect.internal.WhiteboxImpl.getBestMethodCandidate(WhiteboxImpl.java:983)
        at org.powermock.core.MockGateway.doMethodCall(MockGateway.java:92)
        at org.powermock.core.MockGateway.methodCall(MockGateway.java:189)
        at mockito.failure.test.MapWrapper.equals(MapWrapper.java)
        at org.mockito.internal.invocation.InvocationMatcher.matches(InvocationMatcher.java:56)
        at org.mockito.internal.stubbing.InvocationContainerImpl.findAnswerFor(InvocationContainerImpl.java:79)
        at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:91)
        at org.powermock.api.mockito.internal.invocation.MockitoMethodInvocationControl.performIntercept(MockitoMethodInvocationControl.java:267)
        at org.powermock.api.mockito.internal.invocation.MockitoMethodInvocationControl.invoke(MockitoMethodInvocationControl.java:193)
        at org.powermock.core.MockGateway.doMethodCall(MockGateway.java:132)
        at org.powermock.core.MockGateway.methodCall(MockGateway.java:189)
        at mockito.failure.test.MapWrapper.equals(MapWrapper.java)
        at org.mockito.internal.invocation.InvocationMatcher.matches(InvocationMatcher.java:56)
        at org.mockito.internal.stubbing.InvocationContainerImpl.findAnswerFor(InvocationContainerImpl.java:79)
        at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:91)
        at org.powermock.api.mockito.internal.invocation.MockitoMethodInvocationControl.performIntercept(MockitoMethodInvocationControl.java:267)
        at org.powermock.api.mockito.internal.invocation.MockitoMethodInvocationControl.invoke(MockitoMethodInvocationControl.java:193)
        at org.powermock.core.MockGateway.doMethodCall(MockGateway.java:132)
        at org.powermock.core.MockGateway.methodCall(MockGateway.java:189)
        at mockito.failure.test.MapWrapper.equals(MapWrapper.java)
...looping into equals method continues for a while...
```

**Comment by thekingnothing** [comment]
Issue resolved only for Mockito 1.10.x, because Mockito 2 is already release, and there is no sense to fix bug for beta version.
