### ISSUE TITLE
Apache Cxf fail when use PowerMockRunner

### ISSUE THREAD

**Issue by JustBePlayer** [jayway/powermock#711]
I am trying to test one component of my application which use Apache Cxf as a client to create service port. I read the documentation of Apache Cxf where is mentioned that EasyMock is preferable mock framework, but in my situation I need to use the PowerMock extension for it (I want to mock static methods and use MockPolicy). I use JaxWsProxyFactoryBean class to create service port and when run test whit EasyMockRunner everything works fine, but with PowerMockRunner the same test fails with this error.
```

Oct 31, 2016 9:27:18 AM org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean buildServiceFromClass
INFO: Creating Service {urn:... from class defpack.MyService
java.lang.RuntimeException: Invalid schema document passed to AbstractDataBinding.addSchemaDocument, not in W3C schema namespace: schema
at org.apache.cxf.databinding.AbstractDataBinding.addSchemaDocument(AbstractDataBinding.java:110)
at org.apache.cxf.databinding.AbstractDataBinding.addSchemaDocument(AbstractDataBinding.java:96)
at org.apache.cxf.jaxb.JAXBDataBinding.initialize(JAXBDataBinding.java:388)
at org.apache.cxf.service.factory.AbstractServiceFactoryBean.initializeDataBindings(AbstractServiceFactoryBean.java:86)
at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.buildServiceFromClass(ReflectionServiceFactoryBean.java:469)
at org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.buildServiceFromClass(JaxWsServiceFactoryBean.java:696)
at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.initializeServiceModel(ReflectionServiceFactoryBean.java:529)
at org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean.create(ReflectionServiceFactoryBean.java:262)
at org.apache.cxf.jaxws.support.JaxWsServiceFactoryBean.create(JaxWsServiceFactoryBean.java:199)
at org.apache.cxf.frontend.AbstractWSDLBasedEndpointFactory.createEndpoint(AbstractWSDLBasedEndpointFactory.java:102)
at org.apache.cxf.frontend.ClientFactoryBean.create(ClientFactoryBean.java:91)
at org.apache.cxf.frontend.ClientProxyFactoryBean.create(ClientProxyFactoryBean.java:157)
at org.apache.cxf.jaxws.JaxWsProxyFactoryBean.create(JaxWsProxyFactoryBean.java:142)

```

**Comment by thekingnothing** [comment]
If it fails only with `PowerMockRunner` then it could means, that PowerMock reloads some class which should not be reloaded. 
There are known issues with PowerMock and XML. Sometimes you need add "javax.management", "javax.xml.", "org.w3c.", "org.apache.apache.", "com.sun.*" to `@PowerMockIgnore` (#475). In other case enough to add ""org.xml.*", "javax.xml.*" (https://www.jayway.com/2011/05/19/powermock-for-integration-testing/). 

Also you may try to use [PowerMock Agent](https://github.com/jayway/powermock/wiki/PowerMockAgent) instead jUnit runner.

**Comment by vish01** [comment]
Adding  "com.sun." to @PowerMockIgnore fixed my issue as well. Thank you @thekingn0thing!
