### ISSUE TITLE
Mock static URLEncoder.encode(String,String) won't work

### ISSUE THREAD

**Issue by pauloleitemoreira** [jayway/powermock#719]
When I try to mock `URLEncoder.encode(String,String)`, PowerMockito give me an exception. I don't know why, because I didn't call any method yet.

```java
@RunWith(PowerMockRunner.class)
@PrepareForTest({URLEncoder.class})
public class Tests {
    @Test
    public void test() throws Exception{
        PowerMockito.mockStatic(URLEncoder.class);
        PowerMockito.doThrow(new UnsupportedEncodingException())
                .when(URLEncoder.class, "encode", Matchers.anyString(), Matchers.anyString());
    }
}
```

# The exception:

```
java.io.UnsupportedEncodingException:
    at java.net.URLEncoder.encode(URLEncoder.java:214)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.powermock.reflect.internal.WhiteboxImpl.performMethodInvocation(WhiteboxImpl.java:1819)
    at org.powermock.reflect.internal.WhiteboxImpl.doInvokeMethod(WhiteboxImpl.java:801)
    at org.powermock.reflect.internal.WhiteboxImpl.invokeMethod(WhiteboxImpl.java:781)
    at org.powermock.reflect.Whitebox.invokeMethod(Whitebox.java:466)
    at org.powermock.api.mockito.internal.expectation.PowerMockitoStubberImpl.when(PowerMockitoStubberImpl.java:113)
    at anypackage.test(Tests.java:38)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.internal.runners.TestMethod.invoke(TestMethod.java:68)
```
PowerMockito is calling `URLEncoder.encode(String,String)` method, but I didn't make any call yet. Maybe it is architectural concept,, but at first perception it sounds weird.

# Weirdness
To try to figure out what I was doing wrong, I decided to write a static method with the same signature of `URLEncoder.encode(String,String)`, and to my surprise, it works and  didn't give me an exception:

```java
@RunWith(PowerMockRunner.class)
@PrepareForTest({AnyClass.class})
public class Tests {
    @Test
    public void test() throws Exception{
        PowerMockito.mockStatic(AnyClass.class);
        PowerMockito.doThrow(new UnsupportedEncodingException())
                .when(AnyClass.class, "anyMethod", Matchers.anyString(), Matchers.anyString());
    }
}


class AnyClass{
    public static String anyMethod(String a, String b) throws UnsupportedEncodingException{
        throw new UnsupportedEncodingException();
    }
}
```

Why I cannot mock static `URLEncoder.encode(String,String)`? Am I doing something wrong?

*Junit version: 4.12*
*PowerMockito version: 1.6.6*
*Mockito version: 2.0.42-beta*

**Comment by thekingnothing** [comment]
You added the `URLEncoder`, but a **ClassThatCallsTheSystemClass** should be prepared for test not a `URLEncoder` [documentation](https://github.com/jayway/powermock/wiki/MockSystem). 

[Here](https://blog.jayway.com/2009/05/17/mocking-static-methods-in-java-system-classes/) you may find explanation how it works and why you need added `ClassThatCallsTheSystemClass` instead `URLEncoder`

By the way, `URLEncoder` is used to verify this feature, so you may find [example](https://github.com/jayway/powermock/blob/b0c906905f43dae8ffb6346e73d96ad152985369/modules/module-test/mockito/junit4-agent/src/test/java/samples/powermockito/junit4/agent/SystemClassUserTest.java) in  our tests.

**Comment by brian-spinos** [comment]
Still not working...

**Comment by ltChinaCoder** [comment]
similar case..
when i  used with junit, it's ok, but  with spock,it always throwed a expection(org.mockito.exceptions.misusing.MissingMethodInvocationException: 
when() requires an argument which has to be 'a method call on a mock'.)
   My goal is to mockurlencoder's method.
